import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {importAesKey,encryptSecret} from '../src/oauth.js';
import {sha256} from '../src/security.js';
import {WORKFLOW_STAGES,approvedContext,normalizeWorkflowConfig,approvalStatus,fingerprint,renderWorkflowMessage,freshEvidence} from '../src/approved-workflow-engine.js';
import {handleApprovedWorkflowRoute} from '../src/approved-workflow-routes.js';
import {executeWorkflowStage,runApprovedWorkflows} from '../src/approved-workflow-runner.js';
import {workflowAuthorized,workflowDeliveryAuthorized} from '../src/approved-workflow-store.js';
import {runOutreachAutomation as runWithVerification} from '../src/outreach-automation-runner.js';
class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[];}bind(...a){this.args=a;return this;}async first(){return this.db.prepare(this.sql).get(...this.args)||null;}async all(){return {results:this.db.prepare(this.sql).all(...this.args)};}async run(){const result=this.db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(result.changes)}};}}
class DB{constructor(){this.raw=new DatabaseSync(':memory:');for(const file of ['0001_initial.sql','0009_customer_saas.sql','0011_master_crm.sql','0013_workspace_service_integrations.sql','0023_hunter_service_integration.sql','0015_outreach_automation.sql','0022_crm_public_contact_sources.sql','0024_automation_brand_html.sql','0025_contact_suppression.sql','0027_approved_workflow.sql'])this.raw.exec(fs.readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));}prepare(sql){return new Statement(this.raw,sql);}async batch(statements){this.raw.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.raw.exec('COMMIT');return results;}catch(e){this.raw.exec('ROLLBACK');throw e;}}}
const main={website:'https://seller.example/',approved:true,profile:{companyName:'Fixture Industrial',priorityOffers:'industrial automation; custom machinery',idealCustomer:'manufacturers',decisionMakers:'COO',targetMarkets:'Sweden',exclusions:'',opportunityValue:'€50,000',customerPainPoints:'production flow downtime'},market:{strategyApproved:true,icps:[{id:'core',description:'manufacturers',active:true}],signals:[{id:'expansion',name:'Facility expansion',active:true,weight:10,keywords:'new factory; capacity expansion'},{id:'modernization',name:'Modernization',active:true,weight:9,keywords:'automation investment; equipment upgrade'}]}};
const config=normalizeWorkflowConfig({companies:{limit:1,queries:1},buyers:{roles:['COO'],confirmContacts:true},triggers:{minimumScore:50,maxEvidenceAgeDays:90},messages:{subject:'Hello {{company}}',body:'Hello {{firstName}}, {{sender}} offers {{offer}}. Source: {{evidenceUrl}}'},delivery:{timezone:'UTC',dailyLimit:5,sendWindowStart:'09:00',sendWindowEnd:'17:00'}});
async function fixture(){const db=new DB();db.raw.exec("INSERT INTO users(id,email,display_name) VALUES('u1','owner@fixture.test','Owner');INSERT INTO workspaces(id,name,market,owner_user_id) VALUES('w1','First','SE','u1'),('w2','Second','FI','u1');INSERT INTO workspace_members(workspace_id,user_id,role) VALUES('w1','u1','owner');INSERT INTO gmail_connections(workspace_id,user_id,google_email,status) VALUES('w1','u1','owner@fixture.test','connected');");db.raw.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,'u1',datetime('now','+1 day'))").run(await sha256('token'));db.raw.prepare("INSERT INTO customer_workspace_state(workspace_id,payload_json) VALUES('w1',?)").run(JSON.stringify({main}));const key=btoa(String.fromCharCode(...new Uint8Array(32).fill(7)));db.raw.prepare("INSERT INTO workspace_service_integrations(workspace_id,provider,encrypted_api_key,key_hint) VALUES('w1','hunter',?,'test')").run(await encryptSecret('test-hunter',await importAesKey(key)));return {OAUTH_TOKEN_ENCRYPTION_KEY:key,DB:db,AUTOMATIC_GMAIL_DELIVERY_MODE:'manual_only',APPROVED_WORKFLOW_DELIVERY_MODE:'enabled'};}
async function call(env,body,workspace='w1'){return handleApprovedWorkflowRoute(new Request('https://api.test/api/approved-workflow?workspace_id='+workspace,{method:body?'POST':'GET',headers:{Cookie:'leadintel_session=token','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env,{});}
async function approve(env){let res=await call(env,{action:'save',revision:0,config});assert.equal(res.status,200);let value=await res.json();for(const stage of WORKFLOW_STAGES){res=await call(env,{action:'approve-stage',revision:value.revision,stage});assert.equal(res.status,200,await res.clone().text());value=await res.json();}res=await call(env,{action:'activate',revision:value.revision,approved:true});assert.equal(res.status,200,await res.clone().text());return res.json();}
async function generateResearch(env,workspaceId,prompt){
 if(prompt.startsWith('Compare verified'))return JSON.stringify({matches:[]});
 const seller=JSON.parse(prompt.split('Seller: ')[1].split('. Companies: ')[0]),companies=JSON.parse(prompt.split('. Companies: ')[1]);
 return JSON.stringify({companies:companies.map(c=>({domain:c.domain,fit:100,purchase:seller.offers[0],reason:'The documented production process uses this equipment.',buyerRole:'manufacturer',needStatus:'inferred',relevantSignalUrls:(c.signals||[]).flatMap(s=>s.evidence.map(e=>e.url)),evidence:c.evidence.filter(e=>new URL(e.url).hostname===c.domain).map(e=>({url:e.url,quote:e.text.slice(0,300)}))}))});
}
test('approval snapshots ignore key order and invalidate affected downstream stages',async()=>{const context=approvedContext(main),stages=await approvalStatus(context,config),approvals=Object.fromEntries(stages.map(s=>[s.stage,{hash:s.hash}]));const changed=normalizeWorkflowConfig({...config,messages:{...config.messages,body:'Changed'}});const status=await approvalStatus(context,changed,approvals);assert.ok(status.slice(0,5).every(s=>s.approved));assert.ok(status.slice(5).every(s=>!s.approved));assert.equal(await fingerprint({b:2,a:1}),await fingerprint({a:1,b:2}));assert.throws(()=>normalizeWorkflowConfig({messages:{body:'{{secret}}'}}),/Unknown/);assert.throws(()=>renderWorkflowMessage('Hello {{firstName}}',{}),/Missing/);assert.equal(freshEvidence({evidence:[{url:'https://a.test',date:''}]},90).length,0);});
test('stage order, final approval, stale writes and workspace isolation are enforced',async()=>{const env=await fixture();assert.equal((await call(env,null,'w2')).status,401);assert.equal((await call(env,{action:'save',revision:0,config})).status,200);assert.equal((await call(env,{action:'approve-stage',revision:1,stage:'messages'})).status,409);assert.equal((await call(env,{action:'activate',revision:1,approved:true})).status,409);assert.equal((await call(env,{action:'save',revision:0,config})).status,409);env.DB.raw.exec('DELETE FROM approved_workflows');const value=await approve(env);assert.equal(value.status,'automatic');assert.equal(env.DB.raw.prepare('SELECT enabled FROM outreach_automation_policies').get().enabled,1);});
test('pause and manual takeover stop execution; context changes require renewed approval',async()=>{const env=await fixture();const v=await approve(env);assert.equal(await workflowAuthorized(env,'w1',v.revision),true);for(const action of ['pause','manual']){assert.equal((await call(env,{action,revision:v.revision})).status,200);assert.equal(await workflowAuthorized(env,'w1',v.revision),false);assert.equal((await call(env,{action:'resume',revision:v.revision})).status,200);}const changed={...main,profile:{...main.profile,priorityOffers:'Different offer'}};env.DB.raw.prepare("UPDATE customer_workspace_state SET payload_json=? WHERE workspace_id='w1'").run(JSON.stringify({main:changed}));assert.equal(await workflowAuthorized(env,'w1',v.revision),false);assert.equal(env.DB.raw.prepare('SELECT status FROM approved_workflows').get().status,'needs_review');assert.equal((await call(env,{action:'resume',revision:v.revision})).status,409);});
test('server checkpoints all stages once and schedules cycles without repeated confirmation',async()=>{const env=await fixture();await approve(env);const calls=[];const execute=async(stage,{guard,result})=>{await guard();calls.push(stage);return {...result,stage};};assert.equal((await runApprovedWorkflows(env,{execute})).completed,1);assert.deepEqual(calls,WORKFLOW_STAGES);await runApprovedWorkflows(env,{execute});assert.equal(calls.length,8);const run=env.DB.raw.prepare('SELECT * FROM approved_workflow_runs').get();assert.equal(run.status,'completed');assert.equal(run.stage_index,8);assert.equal(await workflowDeliveryAuthorized(env,{workspace_id:'w1',workflow_run_id:run.id,workflow_revision:1}),true);await call(env,{action:'stop',revision:1});assert.equal(await workflowDeliveryAuthorized(env,{workspace_id:'w1',workflow_run_id:run.id,workflow_revision:1}),false);});
test('provider failure blocks and explicit retry resumes the saved stage',async()=>{const env=await fixture();await approve(env);let broken=true;const calls=[];const execute=async(stage,{result})=>{calls.push(stage);if(stage==='buyers'&&broken)throw new Error('Provider credits exhausted');return result;};assert.equal((await runApprovedWorkflows(env,{execute})).blocked,1);const run=env.DB.raw.prepare('SELECT * FROM approved_workflow_runs').get();assert.equal(run.stage_index,3);await runApprovedWorkflows(env,{execute});assert.equal(calls.length,4);broken=false;assert.equal((await call(env,{action:'retry',revision:1,runId:run.id})).status,200);assert.equal((await runApprovedWorkflows(env,{execute})).completed,1);assert.deepEqual(calls.slice(4),WORKFLOW_STAGES.slice(3));});
test('pause during a stage prevents downstream work and a completion claim',async()=>{const env=await fixture();await approve(env);const calls=[];await runApprovedWorkflows(env,{execute:async(stage,{result})=>{calls.push(stage);if(stage==='companies')await call(env,{action:'pause',revision:1});return result;}});assert.deepEqual(calls,['profile','strategy','companies']);assert.equal(env.DB.raw.prepare('SELECT status FROM approved_workflow_runs').get().status,'blocked');});
test('native research, verified buyer, message, CRM and delivery run with mocked providers',async()=>{
  const env=await fixture();await approve(env);env.DB.raw.exec("INSERT INTO crm_companies(id,workspace_id,normalized_domain,company_name,lifecycle_status,first_seen_at,last_seen_at,created_at,updated_at) VALUES('c1','w1','nordicmachines.se','Nordic Machines','prospect',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO crm_contacts(id,workspace_id,company_id,name,title,work_email,normalized_email,email_status,created_at,updated_at) VALUES('p1','w1','c1','Alex Example','COO','alex@nordicmachines.se','alex@nordicmachines.se','verified',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);");
  const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({data:[{url:'https://industrialjournal.se/nordic-investment',title:'Nordic Machines investment confirmed',markdown:'Nordic Machines announced a new factory in Sweden. The project expands manufacturing capacity with industrial automation and custom machinery, according to the company investment announcement.',date:new Date().toISOString()},{url:'https://nordicmachines.se/news',title:'Nordic Machines factory expansion',description:'Swedish manufacturer expanding capacity',markdown:'Swedish manufacturer in Sweden with 100 employees announces a new factory and capacity expansion with industrial automation and custom machinery. Production equipment upgrade and automation investment budget €100,000.',date:new Date().toISOString()}]}),{status:200});};
  try{assert.equal((await runApprovedWorkflows(env,{execute:(stage,args)=>executeWorkflowStage(stage,{...args,generateResearch})})).completed,1);const run=env.DB.raw.prepare('SELECT * FROM approved_workflow_runs').get(),result=JSON.parse(run.result_json);assert.equal(result.candidates.length,1,JSON.stringify(result));assert.equal(result.queued,1);assert.ok(calls>=2);assert.equal(env.DB.raw.prepare('SELECT workflow_run_id FROM outreach_automation_sequences').get().workflow_run_id,run.id);const now=new Date();now.setUTCDate(now.getUTCDate()+((4-now.getUTCDay()+7)%7));now.setUTCHours(12,0,0,0);env.DB.raw.prepare('UPDATE outreach_automation_queue SET scheduled_send_at=?').run(now.toISOString());let sent=0;const response=await runOutreachAutomation(env,{now,sendMessage:async({queue})=>{sent++;assert.match(queue.body,/Alex/);return {id:'mock-gmail',threadId:'mock-thread'};},onSent:async()=>{}});assert.equal(response.sent,1);assert.equal(sent,1);await runOutreachAutomation(env,{now,sendMessage:async()=>{sent++;}});assert.equal(sent,1);}finally{globalThis.fetch=oldFetch;}
});
test('expired execution leases block automatic replay and revoked ownership stops execution',async()=>{const env=await fixture();await approve(env);env.DB.raw.exec("INSERT INTO approved_workflow_runs(id,workspace_id,revision,status,lease_token,lease_until) VALUES('stale','w1',1,'running','old','2000-01-01T00:00:00.000Z')");let calls=0;const outcome=await runApprovedWorkflows(env,{execute:async()=>{calls++;return {};}});assert.equal(outcome.blocked,1);assert.equal(calls,0);assert.match(env.DB.raw.prepare("SELECT error_message FROM approved_workflow_runs WHERE id='stale'").get().error_message,/interrupted/);env.DB.raw.exec("UPDATE workspace_members SET role='sales' WHERE workspace_id='w1'");assert.equal(await workflowAuthorized(env,'w1',1),false);assert.equal((await call(env,{action:'pause',revision:1})).status,403);});
test('direct delivery-setting changes invalidate the final workflow approval',async()=>{const env=await fixture();await approve(env);env.DB.raw.exec("INSERT INTO approved_workflow_runs(id,workspace_id,revision,status,stage_index) VALUES('done','w1',1,'completed',8);UPDATE outreach_automation_policies SET workspace_daily_limit=10 WHERE workspace_id='w1'");assert.equal(await workflowDeliveryAuthorized(env,{workspace_id:'w1',workflow_run_id:'done',workflow_revision:1}),false);const row=env.DB.raw.prepare('SELECT status,approved_at FROM approved_workflows').get();assert.equal(row.status,'needs_review');assert.equal(row.approved_at,null);assert.equal((await call(env,{action:'resume',revision:1})).status,409);});
test('confirmed Step 2 targeting overrides stale generated profile across industries',()=>{const first=approvedContext({...main,answers:{priority_offers:'CRM implementation',ideal_customer:'Property agencies',buyer_roles:'Managing Director'},targetMarkets:['Portugal']});const renamed=approvedContext({...main,profile:{...main.profile,companyName:'Another seller'},answers:{priority_offers:'CRM implementation',ideal_customer:'Property agencies',buyer_roles:'Managing Director'},targetMarkets:['Portugal']});assert.equal(first.profile.priorityOffers,'CRM implementation');assert.equal(first.profile.idealCustomer,'Property agencies');assert.equal(first.profile.priorityOffers,renamed.profile.priorityOffers);assert.equal(first.profile.idealCustomer,renamed.profile.idealCustomer);assert.equal(first.profile.targetMarkets,'Portugal');});
test('renewing changed context starts a new revision and cannot resume old stage results',async()=>{const env=await fixture();await approve(env);env.DB.raw.exec("INSERT INTO approved_workflow_runs(id,workspace_id,revision,status,stage_index,result_json) VALUES('old','w1',1,'blocked',3,'{\"candidates\":[{\"company\":\"Old context\"}]}')");const changed={...main,profile:{...main.profile,idealCustomer:'Different manufacturers'}};env.DB.raw.prepare('UPDATE customer_workspace_state SET payload_json=?').run(JSON.stringify({main:changed}));assert.equal(await workflowAuthorized(env,'w1',1),false);const response=await call(env,{action:'approve-stage',revision:1,stage:'profile'});assert.equal(response.status,200,await response.clone().text());const value=await response.json();assert.equal(value.revision,2);assert.equal(value.approvedAt,null);assert.equal(value.stages[0].approved,true);assert.ok(value.stages.slice(1).every(s=>!s.approved));assert.equal(env.DB.raw.prepare("SELECT status FROM approved_workflow_runs WHERE id='old'").get().status,'stopped');});

test('qualification priority and selectable thresholds persist and invalidate company/downstream approvals',async()=>{
 const env=await fixture();await approve(env);
 const next={...config,qualificationVersion:2,companies:{...config.companies,researchPriority:'signals'},triggers:{...config.triggers,minimumScore:90}};
 const saved=await call(env,{action:'save',revision:1,config:next});assert.equal(saved.status,200);const data=await saved.json();assert.equal(data.status,'needs_review');assert.equal(data.config.companies.researchPriority,'signals');assert.equal(data.config.triggers.minimumScore,90);assert.equal(data.approvedAt,null);
 assert.ok(data.stages.slice(0,2).every(s=>s.approved));assert.ok(data.stages.slice(2).every(s=>!s.approved));assert.equal(await workflowAuthorized(env,'w1',1),false);
 const read=await (await call(env)).json();assert.equal(read.config.triggers.minimumScore,90);assert.equal(read.config.companies.researchPriority,'signals');
 const stored=JSON.parse(env.DB.raw.prepare('SELECT config_json FROM approved_workflows WHERE workspace_id=?').get('w1').config_json);assert.equal(stored.triggers.minimumScore,90);assert.equal(stored.companies.researchPriority,'signals');
 assert.throws(()=>normalizeWorkflowConfig({...next,triggers:{...next.triggers,minimumScore:75}}),/70, 80 or 90/);
 assert.throws(()=>normalizeWorkflowConfig({...next,companies:{...next.companies,researchPriority:'unknown'}}),/Lookalike/);
});

test('Lookalike without buying signals stays outside automatic buyer and message flow',async()=>{
 const env=await fixture(),guard=async()=>{};
 const model={active:true,dna:{active:true,referenceProfiles:[{rowId:'r',companyName:'Reference',dimensions:[{key:'industry',values:['renewable energy']},{key:'productionModel',values:['modular components']},{key:'capabilities',values:['steel structures']}]}]}};
 model.dna.referenceProfiles[0].sourceEvidence=model.dna.referenceProfiles[0].dimensions.map(d=>({field:d.key,url:'https://reference.example/about',quote:'Reference manufactures '+d.values[0]+' for customers.'}));
 const context={...approvedContext(main),signals:[],profile:{companyName:'Seller',website:'seller.example',targetMarkets:'Sweden',idealCustomer:'renewable energy manufacturers',priorityOffers:'steel structures; modular components',referenceSimilarityModel:model}};
 const config=normalizeWorkflowConfig({qualificationVersion:2,companies:{limit:1,queries:2,researchPriority:'lookalike'},triggers:{minimumScore:90},buyers:{roles:['COO']},messages:{subject:'Hello {{company}}',body:'Hello {{firstName}}. Relevant source: {{evidenceUrl}}'}});
 const official={url:'https://nordic.se/products',title:'Nordic products',markdown:'Nordic manufactures steel structures and modular components for renewable energy equipment in Sweden. Its factory supports wind energy manufacturers with engineered components.'};
 const independent={url:'https://industry.example/nordic',title:'Nordic renewable energy equipment',markdown:'Nordic manufactures modular components and steel structures for renewable energy projects in Sweden, according to its industry association listing. The company supplies wind energy manufacturers.'};
 const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({data:[official,independent]}),{status:200});
 try{
  const result=await executeWorkflowStage('companies',{env,row:{workspace_id:'w1'},context,config,result:{},guard,generateResearch});
  assert.equal(result.candidates.length,0);assert.ok(result.reviewCompanies.length);assert.equal(result.shortfall,1);
  assert.ok(result.reviewCompanies.every(c=>!c.qualification.eligible));
  assert.ok(result.reviewCompanies.some(c=>c.qualification.gaps.includes('No recent verified buying signal')));
 }finally{globalThis.fetch=original;}
});
test('automatic buyers research a public pool and prioritize kept verified buyers in the same workspace',async()=>{
 const env=await fixture();
 env.DB.raw.exec("INSERT INTO crm_companies(id,workspace_id,normalized_domain,company_name,lifecycle_status,first_seen_at,last_seen_at,created_at,updated_at) VALUES('c1','w1','example.com','Example','prospect',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO crm_contacts(id,workspace_id,company_id,name,title,normalized_email,email_status,linkedin_url,created_at,updated_at) VALUES('a','w1','c1','First Buyer','COO','first@example.com','verified','https://linkedin.com/in/first',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('b','w1','c1','Saved Buyer','COO','saved@example.com','verified','https://linkedin.com/in/saved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
 const payload={main,discovery:{selectedProspects:[{domain:'example.com',people:[{name:'Saved Buyer',title:'COO',publicLinkedinUrl:'https://linkedin.com/in/saved',kept:true}]}]}};
 env.DB.raw.prepare('UPDATE customer_workspace_state SET payload_json=? WHERE workspace_id=?').run(JSON.stringify(payload),'w1');
 const oldFetch=globalThis.fetch;let apollo=0,publicSearches=0;
 globalThis.fetch=async(url)=>{if(String(url).includes('apollo.io')){apollo++;throw new Error('Unexpected enrichment');}publicSearches++;return new Response(JSON.stringify({data:Array.from({length:20},(_,i)=>({url:`https://linkedin.com/in/person-${i}`,title:`Anna Buyer${String.fromCharCode(65+i)} – COO at Example`}))}),{status:200});};
 try{
  const result=await executeWorkflowStage('buyers',{env,row:{workspace_id:'w1'},context:approvedContext(main),config,result:{candidates:[{company:'Example',domain:'example.com'}]},guard:async()=>{}});
  assert.equal(result.candidates[0].contact.name,'Saved Buyer');assert.equal(result.candidates[0].buyerDiscovery.pool.length,20);assert.equal(result.candidates[0].people.length,6);assert.equal(apollo,0);assert.ok(publicSearches>0);
 }finally{globalThis.fetch=oldFetch;}
});
test('automatic buyers retain public suggestions for review without approved enrichment or verified emails',async()=>{
 const env=await fixture(),oldFetch=globalThis.fetch;let apollo=0;
 globalThis.fetch=async(url)=>{if(String(url).includes('apollo.io'))apollo++;return new Response(JSON.stringify({data:[{url:'https://linkedin.com/in/anna',title:'Anna Buyer – COO at Example'}]}),{status:200});};
 try{
  const manualConfig=normalizeWorkflowConfig({...config,buyers:{roles:['COO'],enrich:false}});
  const result=await executeWorkflowStage('buyers',{env,row:{workspace_id:'w1'},context:approvedContext(main),config:manualConfig,result:{candidates:[{company:'Example',domain:'example.com'}]},guard:async()=>{}});
  assert.equal(result.candidates.length,0);assert.equal(result.reviewBuyers.length,1);assert.equal(result.reviewBuyers[0].people[0].name,'Anna Buyer');assert.equal(apollo,0);
 }finally{globalThis.fetch=oldFetch;}
});

function runOutreachAutomation(env,options={}){return runWithVerification(env,{verifyEmail:async()=>({verified:true,provider:'test'}),...options});}


test('automatic companies stage persists only gate-passing qualified candidates to CRM before Buyers',async()=>{
  const source=fs.readFileSync(new URL('../src/approved-workflow-runner.js',import.meta.url),'utf8');
  const companiesBlock=source.slice(source.indexOf("if(stage==='companies')"),source.indexOf("if(stage==='buyers')"));
  assert.match(companiesBlock,/assessed\.filter\(c=>c\.qualification\.eligible\)/);
  assert.match(companiesBlock,/config\.crm\.saveQualified/);
  assert.match(companiesBlock,/source:'approved_workflow_qualified'/);
  assert.match(companiesBlock,/automaticQualifiedSave:true/);
  assert.ok(companiesBlock.indexOf("assessed.filter(c=>c.qualification.eligible)")<companiesBlock.indexOf("source:'approved_workflow_qualified'"));
});

test('automatic CRM save contract defaults on and minimum qualification remains 80 unless explicitly approved otherwise',()=>{
  const defaults=normalizeWorkflowConfig({companies:{researchPriority:'balanced'},buyers:{roles:['COO']},messages:{subject:'Hi {{company}}',body:'Hi {{firstName}} {{evidenceUrl}}'}});
  assert.equal(defaults.triggers.minimumScore,80);
  assert.equal(defaults.crm.saveQualified,true);
});
