import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {confirmPublicWorkEmail,loadConfirmationLevel} from '../src/public-email-confirmation.js';
import {getCrmCompany,upsertCrmCompany,upsertCrmContacts} from '../src/crm.js';
import {enrichCrmContact} from '../src/crm-routes.js';
import {apolloCapabilities,handleServiceIntegrationRoute} from '../src/service-integrations.js';
import {verifyAutomaticEmail} from '../src/automatic-email-verification.js';
import {sha256} from '../src/security.js';
import {normalizeWorkflowConfig} from '../src/approved-workflow-engine.js';
const P=globalThis.LeadIntelContactPolicy;
class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[];}bind(...a){this.args=a;return this;}async first(){return this.db.prepare(this.sql).get(...this.args)||null;}async all(){return {results:this.db.prepare(this.sql).all(...this.args)};}async run(){const r=this.db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes)}};}}
class DB{constructor(){this.raw=new DatabaseSync(':memory:');for(const file of ['0001_initial.sql','0009_customer_saas.sql','0011_master_crm.sql','0012_crm_contact_enrichment.sql','0013_workspace_service_integrations.sql','0023_hunter_service_integration.sql','0022_crm_public_contact_sources.sql','0015_outreach_automation.sql','0027_approved_workflow.sql'])this.raw.exec(fs.readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));this.raw.exec("CREATE TABLE enrichment_policies(workspace_id TEXT PRIMARY KEY,daily_credit_limit INTEGER DEFAULT 3,monthly_credit_limit INTEGER DEFAULT 30,retry_after_days INTEGER DEFAULT 30,allow_personal_email INTEGER DEFAULT 0,phone_lookup_mode TEXT DEFAULT 'on_request')");}prepare(sql){return new Statement(this.raw,sql);}async batch(rows){return Promise.all(rows.map(s=>s.run()));}}
const context={workspaceId:'w1',userId:'u1',role:'owner'},input={name:'Anna Andersson',email:'anna.andersson@example.com',source_url:'https://example.com/team',title:'Procurement Director'};
async function fixture(){const db=new DB();db.raw.exec("INSERT INTO users(id,email,display_name) VALUES('u1','owner@example.com','Owner');INSERT INTO workspaces(id,name,market,owner_user_id) VALUES('w1','First','SE','u1'),('w2','Second','FI','u1');INSERT INTO workspace_members(workspace_id,user_id,role) VALUES('w1','u1','owner');INSERT INTO workspace_service_integrations(workspace_id,provider,encrypted_api_key,key_hint) VALUES('w1','apollo','fixture','test');");db.raw.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,'u1',datetime('now','+1 day'))").run(await sha256('token'));db.raw.exec("INSERT INTO enrichment_policies(workspace_id) VALUES('w1')");const env={DB:db,APOLLO_API_KEY:'fixture',APOLLO_WEBHOOK_URL:'https://api.test/webhook',APOLLO_WEBHOOK_SIGNING_SECRET:'fixture-secret'};const company=(await upsertCrmCompany(db,context,{company_name:'Example',domain:'example.com'})).company;return {env,company};}
const page=async()=>({markdown:'Anna Andersson, Procurement Director. Email: anna.andersson@example.com',metadata:{sourceURL:input.source_url}});
test('public attribution persists and reloads without pretending to verify a mailbox',async()=>{const {env,company}=await fixture();const c=await confirmPublicWorkEmail(env,context,company.id,input,{loadPage:page});assert.equal(c.email_status,'public_confirmed');assert.equal(P.accepted(c,'example.com','public_confirmed'),true);assert.equal(P.accepted(c,'example.com','provider_verified'),false);await confirmPublicWorkEmail(env,context,company.id,input,{loadPage:async()=>{throw Error('must reuse current confirmation');}});assert.equal(env.DB.raw.prepare("SELECT COUNT(*) n FROM crm_activities WHERE activity_type='contact.public_email_confirmed'").get().n,1);await upsertCrmContacts(env.DB,context,company.id,[{...input,work_email:input.email,email_status:'public_unverified',source:'public_research'}]);assert.equal((await getCrmCompany(env.DB,context,company.id)).contacts[0].email_status,'public_confirmed');});
test('guesses, generic inboxes, third-party and redirected pages cannot promote a buyer',async()=>{for(const bad of [{...input,source_url:'https://directory.example/team'},{...input,email:'info@example.com'},{...input,name:'Anna'}]){const {env,company}=await fixture();await assert.rejects(confirmPublicWorkEmail(env,context,company.id,bad,{loadPage:page}));}for(const data of [{markdown:'Mark Johnson mark@example.com'},{markdown:'Anna Andersson anna.andersson@example.com',metadata:{sourceURL:'https://evil.example/'}}]){const {env,company}=await fixture();await assert.rejects(confirmPublicWorkEmail(env,context,company.id,input,{loadPage:async()=>data}),/did not confirm/);assert.equal((await getCrmCompany(env.DB,context,company.id)).contacts.length,0);}});
test('delivery applies public policy, freshness and workspace isolation with no paid requests',async()=>{const {env,company}=await fixture();const c=await confirmPublicWorkEmail(env,context,company.id,input,{loadPage:page});let calls=0;const options={companyDomain:'example.com',confirmationLevel:'public_confirmed',readPolicy:async()=>({enabled:false}),fetcher:async()=>{calls++;throw Error('no provider');}};const result=await verifyAutomaticEmail(env,'w1',input.email,options);assert.equal(result.verified,true);assert.equal(result.mailbox_verified,false);assert.equal((await verifyAutomaticEmail(env,'w1',input.email,{...options,confirmationLevel:'provider_verified'})).verified,false);assert.equal((await verifyAutomaticEmail(env,'w2',input.email,options)).verified,false);env.DB.raw.prepare("UPDATE crm_contacts SET verified_at='2020-01-01T00:00:00Z' WHERE id=?").run(c.id);assert.equal((await verifyAutomaticEmail(env,'w1',input.email,options)).verified,false);assert.equal(calls,0);});
test('new and legacy workflow defaults preserve their confirmation requirements',async()=>{const {env}=await fixture();assert.equal(await loadConfirmationLevel(env,'w1'),'public_confirmed');assert.equal(normalizeWorkflowConfig({}).buyers.confirmationLevel,'public_confirmed');assert.equal(normalizeWorkflowConfig({buyers:{roles:['COO']}}).buyers.confirmationLevel,'provider_verified');});
test('paid Apollo capabilities are off by default and cannot reserve credits',async()=>{const {env,company}=await fixture();assert.deepEqual(await apolloCapabilities(env,'w1'),{discovery:true,email:false,phone:false});for(const phone_lookup of [false,true]){const r=await enrichCrmContact(new Request('https://api.test/internal',{method:'POST',body:JSON.stringify({name:input.name,person_id:'p1',phone_lookup})}),env,{}, {context},company.id);assert.equal(r.status,409);assert.equal((await r.json()).code,'CRM_APOLLO_CAPABILITY_DISABLED');}assert.equal(env.DB.raw.prepare('SELECT COUNT(*) n FROM crm_enrichment_requests').get().n,0);});
test('owner Apollo settings persist separate permissions and limits without creating Hunter configuration',async()=>{const {env}=await fixture();const r=await handleServiceIntegrationRoute(new Request('https://api.test/api/integrations/services/apollo/settings?workspace_id=w1',{method:'PUT',headers:{Cookie:'leadintel_session=token','Content-Type':'application/json'},body:JSON.stringify({discovery:true,email:true,phone:false,daily_limit:2,monthly_limit:10})}),env,{});assert.equal(r.status,200,await r.clone().text());assert.deepEqual(await apolloCapabilities(env,'w1'),{discovery:true,email:true,phone:false});assert.equal((await apolloCapabilities(env,'w2')).email,false);assert.equal(env.DB.raw.prepare("SELECT daily_credit_limit FROM enrichment_policies WHERE workspace_id='w1'").get().daily_credit_limit,2);assert.equal(env.DB.raw.prepare("SELECT COUNT(*) n FROM workspace_service_integrations WHERE provider='hunter'").get().n,0);});
test('legacy standalone delivery approval never silently accepts public confirmation',async()=>{const {env}=await fixture();env.DB.raw.exec("INSERT INTO outreach_automation_policies(workspace_id,mode,enabled) VALUES('w1','automatic',1)");assert.equal(await loadConfirmationLevel(env,'w1'),'provider_verified');});

test('optional Hunter cannot bypass expired public identity evidence',async()=>{const {env,company}=await fixture();const c=await confirmPublicWorkEmail(env,context,company.id,input,{loadPage:page});env.DB.raw.prepare("UPDATE crm_contacts SET verified_at='2020-01-01T00:00:00Z' WHERE id=?").run(c.id);let calls=0;const result=await verifyAutomaticEmail(env,'w1',input.email,{companyDomain:'example.com',readPolicy:async()=>({enabled:true}),fetcher:async()=>{calls++;throw Error('must not spend');}});assert.equal(result.verified,false);assert.match(result.reason,/Recheck/);assert.equal(calls,0);});
