import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {runOutreachAutomation} from '../src/outreach-automation-runner.js';
import {pollOutreachReplies} from '../src/outreach-automation-replies.js';

let DatabaseSync=null;try{({DatabaseSync}=await import('node:sqlite'));}catch{}
const sqliteTest=(name,fn)=>test(name,{skip:DatabaseSync?false:'requires Node sqlite'},fn);
class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[];}bind(...args){this.args=args;return this;}async first(){return this.db.prepare(this.sql).get(...this.args)??null;}async all(){return {results:this.db.prepare(this.sql).all(...this.args)};}async run(){const r=this.db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes||0)}};}}
class DB{constructor(){this.raw=new DatabaseSync(':memory:');this.raw.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE workspaces(id TEXT PRIMARY KEY);CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE gmail_connections(workspace_id TEXT PRIMARY KEY,user_id TEXT,google_email TEXT,encrypted_refresh_token TEXT,scopes TEXT,status TEXT,history_id TEXT,connected_at TEXT,updated_at TEXT,disconnected_at TEXT);
CREATE TABLE gmail_messages(id TEXT PRIMARY KEY,workspace_id TEXT,idempotency_key TEXT,domain TEXT,recipient TEXT,subject TEXT,gmail_message_id TEXT,gmail_thread_id TEXT,sent_by TEXT,sent_at TEXT,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,idempotency_key));
CREATE TABLE crm_companies(id TEXT PRIMARY KEY,workspace_id TEXT,normalized_domain TEXT,company_name TEXT,lifecycle_status TEXT,deleted_at TEXT,pipeline_stage TEXT,updated_at TEXT);
CREATE TABLE audit_events(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,event_type TEXT,entity_type TEXT,entity_id TEXT,metadata_json TEXT);
INSERT INTO workspaces VALUES('w1');INSERT INTO users VALUES('u1');INSERT INTO gmail_connections(workspace_id,user_id,google_email,encrypted_refresh_token,status) VALUES('w1','u1','sender@example.com','x','connected');`);this.raw.exec(fs.readFileSync(new URL('../migrations/0015_outreach_automation.sql',import.meta.url),'utf8'));}prepare(sql){return new Statement(this.raw,sql);}async batch(rows){this.raw.exec('BEGIN');try{const out=[];for(const row of rows)out.push(await row.run());this.raw.exec('COMMIT');return out;}catch(e){this.raw.exec('ROLLBACK');throw e;}}}
function seedPolicy(db,{mode='automatic',enabled=1,paused=0,emergency=0}={}){db.raw.prepare(`INSERT INTO outreach_automation_policies(workspace_id,mode,enabled,paused,emergency_stop,workspace_daily_limit,mailbox_daily_limit,working_days_json,timezone,send_window_start,send_window_end,min_delay_minutes,max_delay_minutes,max_followups,followup_delays_days_json,reply_poll_interval_minutes,updated_by) VALUES('w1',?,?,?,?,20,20,'[1,2,3,4,5]','Europe/Riga','09:00','16:30',8,18,2,'[3,7]',60,'u1')`).run(mode,enabled,paused,emergency);}
function seedSequence(db){db.raw.prepare(`INSERT INTO crm_companies(id,workspace_id,normalized_domain,company_name,lifecycle_status,deleted_at,pipeline_stage,updated_at) VALUES('c1','w1','example.com','Example','prospect',NULL,'Ready for Outreach',CURRENT_TIMESTAMP)`).run();db.raw.prepare(`INSERT INTO outreach_automation_sequences(id,workspace_id,gmail_connection_workspace_id,source_package_key,domain,recipient,contact_identity,approved_at,initial_subject,initial_body,followup_body,status,created_by) VALUES('s1','w1','w1','pkg1','example.com','buyer@example.com','person-1','2026-09-08T07:00:00.000Z','Subject','Body','Follow up','active','u1')`).run();db.raw.prepare(`INSERT INTO outreach_automation_queue(id,workspace_id,sequence_id,gmail_connection_workspace_id,step_index,recipient,subject,body,status,earliest_send_at,scheduled_send_at,idempotency_key) VALUES('q0','w1','s1','w1',0,'buyer@example.com','Subject','Body','queued','2026-09-08T08:00:00.000Z','2026-09-08T08:00:00.000Z','auto-q0')`).run();}
const noCrm=async()=>{};
function inboundThread(sentAt){const received=new Date(new Date(sentAt).getTime()+15*60000).getTime();return {id:'th-q0',messages:[{id:'gm-q0',threadId:'th-q0',internalDate:String(new Date(sentAt).getTime()),payload:{headers:[{name:'From',value:'sender@example.com'}],mimeType:'text/plain',body:{data:Buffer.from('Body').toString('base64url')}}},{id:'reply-1',threadId:'th-q0',internalDate:String(received),payload:{headers:[{name:'From',value:'Buyer <buyer@example.com>'}],mimeType:'text/plain',body:{data:Buffer.from('Sounds interesting. Tell me more.').toString('base64url')}}}]};}

sqliteTest('manual default never executes automatic queue',async()=>{const DBx=new DB();seedPolicy(DBx,{mode:'manual',enabled:0});seedSequence(DBx);let calls=0;const result=await runOutreachAutomation({DB:DBx},{now:new Date('2026-09-08T08:30:00Z'),sendMessage:async()=>{calls++;return {id:'x',threadId:'x'};},onSent:noCrm});assert.equal(calls,0);assert.equal(result.sent,0);assert.equal(DBx.raw.prepare(`SELECT status FROM outreach_automation_queue WHERE id='q0'`).get().status,'queued');});

sqliteTest('approved snapshot sends once, queues followups, inbound reply stops sequence and prevents later sends',async()=>{const DBx=new DB();seedPolicy(DBx);seedSequence(DBx);const env={DB:DBx};let sends=0;const first=await runOutreachAutomation(env,{now:new Date('2026-09-08T08:30:00Z'),random:()=>0,sendMessage:async()=>{sends++;return {id:'gm-q0',threadId:'th-q0'};},onSent:noCrm});assert.equal(first.sent,1);assert.equal(sends,1);assert.equal(DBx.raw.prepare(`SELECT COUNT(*) n FROM outreach_automation_queue WHERE sequence_id='s1' AND step_index>0 AND status='queued'`).get().n,2);const sent=DBx.raw.prepare(`SELECT sent_at FROM outreach_automation_queue WHERE id='q0'`).get();
  const poll=await pollOutreachReplies(env,{now:new Date('2026-09-08T10:00:00Z'),fetchThread:async()=>inboundThread(sent.sent_at),onReply:noCrm});assert.equal(poll.replies,1);assert.equal(poll.stopped,1);assert.equal(DBx.raw.prepare(`SELECT status FROM outreach_automation_sequences WHERE id='s1'`).get().status,'stopped_reply');assert.equal(DBx.raw.prepare(`SELECT COUNT(*) n FROM outreach_automation_queue WHERE sequence_id='s1' AND step_index>0 AND status='cancelled_reply'`).get().n,2);
  const secondPoll=await pollOutreachReplies(env,{now:new Date('2026-09-08T11:30:00Z'),fetchThread:async()=>inboundThread(sent.sent_at),onReply:noCrm});assert.equal(secondPoll.replies,0);assert.equal(DBx.raw.prepare(`SELECT COUNT(*) n FROM outreach_automation_processed_replies WHERE sequence_id='s1'`).get().n,1);
  const later=await runOutreachAutomation(env,{now:new Date('2026-09-17T08:30:00Z'),sendMessage:async()=>{sends++;return {id:'unexpected',threadId:'unexpected'};},onSent:noCrm});assert.equal(later.sent,0);assert.equal(sends,1);
});

sqliteTest('emergency stop between enqueue and run blocks Gmail until owner policy is cleared',async()=>{const DBx=new DB();seedPolicy(DBx,{emergency:1});seedSequence(DBx);const env={DB:DBx};let calls=0;const sendMessage=async()=>{calls++;return {id:'gm',threadId:'th'};};await runOutreachAutomation(env,{now:new Date('2026-09-08T08:30:00Z'),sendMessage,onSent:noCrm});assert.equal(calls,0);DBx.raw.prepare(`UPDATE outreach_automation_policies SET emergency_stop=0 WHERE workspace_id='w1'`).run();const resumed=await runOutreachAutomation(env,{now:new Date('2026-09-08T08:31:00Z'),sendMessage,onSent:noCrm});assert.equal(resumed.sent,1);assert.equal(calls,1);});
