import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {base64UrlEncode} from '../src/gmail.js';
import {pollOutreachReplies} from '../src/outreach-automation-replies.js';

let DatabaseSync=null;try{({DatabaseSync}=await import('node:sqlite'));}catch{}
const sqliteTest=(name,fn)=>test(name,{skip:DatabaseSync?false:'requires Node sqlite'},fn);
class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[];}bind(...args){this.args=args;return this;}async first(){return this.db.prepare(this.sql).get(...this.args)??null;}async all(){return {results:this.db.prepare(this.sql).all(...this.args)};}async run(){const r=this.db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes||0)}};}}
class DB{constructor(){this.raw=new DatabaseSync(':memory:');this.raw.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE workspaces(id TEXT PRIMARY KEY);CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE gmail_connections(workspace_id TEXT PRIMARY KEY,user_id TEXT,google_email TEXT,encrypted_refresh_token TEXT,scopes TEXT,status TEXT,history_id TEXT,connected_at TEXT,updated_at TEXT,disconnected_at TEXT);
CREATE TABLE gmail_messages(id TEXT PRIMARY KEY,workspace_id TEXT,idempotency_key TEXT,domain TEXT,recipient TEXT,subject TEXT,gmail_message_id TEXT,gmail_thread_id TEXT,sent_by TEXT,sent_at TEXT,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,idempotency_key));
CREATE TABLE crm_companies(id TEXT PRIMARY KEY,workspace_id TEXT,normalized_domain TEXT,company_name TEXT,lifecycle_status TEXT,deleted_at TEXT,pipeline_stage TEXT,updated_at TEXT);
CREATE TABLE audit_events(id TEXT PRIMARY KEY,workspace_id TEXT,user_id TEXT,event_type TEXT,entity_type TEXT,entity_id TEXT,metadata_json TEXT);
INSERT INTO workspaces VALUES('w1');INSERT INTO users VALUES('u1');INSERT INTO gmail_connections(workspace_id,user_id,google_email,encrypted_refresh_token,status) VALUES('w1','u1','sender@example.com','x','connected');`);this.raw.exec(fs.readFileSync(new URL('../migrations/0015_outreach_automation.sql',import.meta.url),'utf8'));}prepare(sql){return new Statement(this.raw,sql);}async batch(rows){this.raw.exec('BEGIN');try{const out=[];for(const row of rows)out.push(await row.run());this.raw.exec('COMMIT');return out;}catch(e){this.raw.exec('ROLLBACK');throw e;}}}
function policy(db,{interval=60}={}){db.raw.prepare(`INSERT INTO outreach_automation_policies(workspace_id,mode,enabled,workspace_daily_limit,mailbox_daily_limit,working_days_json,timezone,send_window_start,send_window_end,min_delay_minutes,max_delay_minutes,max_followups,followup_delays_days_json,reply_poll_interval_minutes,updated_by) VALUES('w1','automatic',1,20,20,'[1,2,3,4,5]','Europe/Riga','09:00','16:30',8,18,2,'[3,7]',?,'u1')`).run(interval);}
function sequence(db,{id='s1',domain='example.com',recipient='buyer@example.com',lastPolled=null}={}){db.raw.prepare(`INSERT INTO crm_companies(id,workspace_id,normalized_domain,company_name,lifecycle_status,deleted_at,pipeline_stage,updated_at) VALUES(?,?,?,?,?,NULL,'Contacted',CURRENT_TIMESTAMP)`).run(`c-${id}`,'w1',domain,domain,'prospect');db.raw.prepare(`INSERT INTO outreach_automation_sequences(id,workspace_id,gmail_connection_workspace_id,source_package_key,domain,recipient,approved_at,initial_subject,initial_body,followup_body,status,last_polled_at,created_by) VALUES(?,?,?,?,?,?,?,'S','B','F','active',?,'u1')`).run(id,'w1','w1',`pkg-${id}`,domain,recipient,'2026-09-08T07:00:00.000Z',lastPolled);db.raw.prepare(`INSERT INTO outreach_automation_queue(id,workspace_id,sequence_id,gmail_connection_workspace_id,step_index,recipient,subject,body,status,earliest_send_at,scheduled_send_at,idempotency_key,gmail_message_id,gmail_thread_id,sent_at) VALUES(?,?,?,?,0,?,?,?,'sent','2026-09-08T08:00:00Z','2026-09-08T08:00:00Z',?,?,?,'2026-09-08T08:00:00Z')`).run(`q0-${id}`,'w1',id,'w1',recipient,'S','B',`key-${id}` ,`gm-${id}`,`th-${id}`);for(const step of [1,2])db.raw.prepare(`INSERT INTO outreach_automation_queue(id,workspace_id,sequence_id,gmail_connection_workspace_id,step_index,recipient,subject,body,status,earliest_send_at,scheduled_send_at,idempotency_key) VALUES(?,?,?,?,?,?,?,'F','queued','2026-09-11T06:00:00Z','2026-09-11T06:00:00Z',?)`).run(`q${step}-${id}`,'w1',id,'w1',step,recipient,'S',`key-${id}-f${step}`);}
function fixture(options={}){const DBi=new DB();policy(DBi,options);sequence(DBi,options);return {DB:DBi};}
function threadFor({sequenceId='s1',messageId='reply-1',text='Sounds interesting',received='2026-09-08T08:30:00.000Z'}={}){return {id:`th-${sequenceId}`,messages:[{id:`gm-${sequenceId}`,threadId:`th-${sequenceId}`,internalDate:String(Date.parse('2026-09-08T08:00:00.000Z')),payload:{headers:[{name:'From',value:'sender@example.com'}],body:{data:base64UrlEncode('sent')}}},{id:messageId,threadId:`th-${sequenceId}`,internalDate:String(Date.parse(received)),payload:{mimeType:'text/plain',headers:[{name:'From',value:'buyer@example.com'}],body:{data:base64UrlEncode(text)}}}]};}
const now=new Date('2026-09-08T09:00:00.000Z');

sqliteTest('any inbound reply is deduped, stops the sequence, and cancels every pending followup',async()=>{
  const env=fixture();const observed=[];const fetchThread=async()=>threadFor({});const first=await pollOutreachReplies(env,{now,fetchThread,onReply:async ctx=>observed.push(ctx.reply)});assert.equal(first.stopped,1);assert.equal(first.replies,1);assert.equal(observed.length,1);assert.equal(observed[0].category,'positive');
  assert.equal(env.DB.raw.prepare(`SELECT status FROM outreach_automation_sequences WHERE id='s1'`).get().status,'stopped_reply');assert.deepEqual(env.DB.raw.prepare(`SELECT status FROM outreach_automation_queue WHERE sequence_id='s1' AND step_index>0 ORDER BY step_index`).all().map(x=>x.status),['cancelled_reply','cancelled_reply']);assert.equal(env.DB.raw.prepare(`SELECT COUNT(*) count FROM outreach_automation_processed_replies`).get().count,1);
  const second=await pollOutreachReplies(env,{now:new Date('2026-09-08T10:00:00Z'),fetchThread,onReply:async ctx=>observed.push(ctx.reply)});assert.equal(second.replies,0);assert.equal(observed.length,1);assert.equal(env.DB.raw.prepare(`SELECT COUNT(*) count FROM outreach_automation_processed_replies`).get().count,1);
});

sqliteTest('poll interval prevents unnecessary Gmail thread reads',async()=>{
  const env=fixture({lastPolled:'2026-09-08T08:30:00.000Z'});let calls=0;const result=await pollOutreachReplies(env,{now,fetchThread:async()=>{calls++;return threadFor({});},onReply:async()=>{}});assert.equal(calls,0);assert.equal(result.polled,0);assert.equal(result.skipped,1);
});

sqliteTest('one Gmail thread failure does not prevent another sequence reply stop',async()=>{
  const env=fixture();sequence(env.DB,{id:'s2',domain:'second.com',recipient:'two@second.com'});const handled=[];const result=await pollOutreachReplies(env,{now,fetchThread:async({sequence})=>{if(sequence.id==='s1')throw new Error('temporary Gmail failure');return threadFor({sequenceId:'s2',messageId:'reply-2'});},onReply:async ctx=>handled.push(ctx.sequence.id)});assert.equal(result.failed,1);assert.equal(result.stopped,1);assert.deepEqual(handled,['s2']);assert.equal(env.DB.raw.prepare(`SELECT status FROM outreach_automation_sequences WHERE id='s1'`).get().status,'active');assert.equal(env.DB.raw.prepare(`SELECT status FROM outreach_automation_sequences WHERE id='s2'`).get().status,'stopped_reply');
});
