import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {importAesKey,encryptSecret} from '../src/oauth.js';
import {sha256} from '../src/security.js';
import {WORKFLOW_STAGES,approvedContext,normalizeWorkflowConfig,approvalStatus,fingerprint,renderWorkflowMessage,freshEvidence} from '../src/approved-workflow-engine.js';
import {handleApprovedWorkflowRoute} from '../src/approved-workflow-routes.js';
import {executeWorkflowStage,runApprovedWorkflows,researchBuyerContacts} from '../src/approved-workflow-runner.js';
import {workflowAuthorized,workflowDeliveryAuthorized} from '../src/approved-workflow-store.js';
import {handleSavedFlowRoute} from '../src/saved-flow-routes.js';
import {runSavedFlows} from '../src/saved-flow-runner.js';
import {savedFlowAuthorized} from '../src/saved-flow-store.js';
import {getCustomerState,putCustomerState} from '../src/customer-state.js';
class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[];}bind(...a){this.args=a;return this;}async first(){return this.db.prepare(this.sql).get(...this.args)||null;}async all(){return {results:this.db.prepare(this.sql).all(...this.args)};}async run(){const result=this.db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(result.changes)}};}}
class DB{constructor(){this.raw=new DatabaseSync(':memory:');this.raw.exec("CREATE TABLE enrichment_policies(workspace_id TEXT PRIMARY KEY,daily_credit_limit INTEGER NOT NULL DEFAULT 3,monthly_credit_limit INTEGER NOT NULL DEFAULT 30,retry_after_days INTEGER NOT NULL DEFAULT 30,allow_personal_email INTEGER NOT NULL DEFAULT 0,phone_lookup_mode TEXT NOT NULL DEFAULT 'on_request')");for(const file of ['0001_initial.sql','0009_customer_saas.sql','0011_master_crm.sql','0012_crm_contact_enrichment.sql','0013_workspace_service_integrations.sql','0023_hunter_service_integration.sql','0015_outreach_automation.sql','0022_crm_public_contact_sources.sql','0024_automation_brand_html.sql','0025_contact_suppression.sql','0027_approved_workflow.sql','0030_saved_flows.sql'])this.raw.exec(fs.readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));}prepare(sql){return new Statement(this.raw,sql);}async batch(statements){this.raw.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());this.raw.exec('COMMIT');return results;}catch(e){this.raw.exec('ROLLBACK');throw e;}}}
const main={website:'https://seller.example',targetMarkets:['Sweden'],approved:true,answers:{priority_offers:'industrial automation',ideal_customer:'manufacturers',buyer_roles:'COO',exclusions:'retail',value_proposition:'Reliable equipment'},profile:{companyName:'Seller',priorityOffers:'industrial automation',idealCustomer:'manufacturers',decisionMakers:'COO',targetMarkets:'Sweden',exclusions:'retail'},market:{strategyApproved:true,icps:[{id:'core',description:'manufacturers',active:true}],signals:[{id:'expansion',name:'Facility expansion',active:true,weight:10,keywords:'new factory'}]},brandIdentity:{senderName:'Alex'}};
const config=normalizeWorkflowConfig({qualificationVersion:3,buyers:{roles:['COO'],confirmationLevel:'public_confirmed'},messages:{subject:'Hello {{company}}',body:'Hello {{firstName}}, {{sender}} offers {{offer}}. Source: {{evidenceUrl}}'},delivery:{timezone:'UTC',dailyLimit:5}});
async function fixture(){const db=new DB();db.raw.exec("INSERT INTO users(id,email,display_name) VALUES('u1','owner@fixture.test','Owner');INSERT INTO workspaces(id,name,market,owner_user_id) VALUES('w1','First','SE','u1'),('w2','Other','FI','u1');INSERT INTO workspace_members(workspace_id,user_id,role) VALUES('w1','u1','owner');INSERT INTO gmail_connections(workspace_id,user_id,google_email,status) VALUES('w1','u1','owner@fixture.test','connected');");db.raw.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,'u1',datetime('now','+1 day'))").run(await sha256('token'));db.raw.prepare("INSERT INTO customer_workspace_state(workspace_id,payload_json,version) VALUES('w1',?,1)").run(JSON.stringify({main,discovery:{pipeline:[{company:'Swedish Buyer',people:[{name:'Buyer'}]}]},outreach:{messageStudio:{mode:'professional'}},delivery:{}}));return {DB:db,AUTOMATIC_GMAIL_DELIVERY_MODE:'manual_only',APPROVED_WORKFLOW_DELIVERY_MODE:'enabled'};}
async function call(env,id,body,workspace='w1'){return handleSavedFlowRoute(new Request('https://api.test/api/flows'+(id?'/'+id:'')+'?workspace_id='+workspace,{method:body?'POST':'GET',headers:{Cookie:'leadintel_session=token','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);}
async function ok(res){assert.equal(res.status,200,await res.clone().text());return res.json();}
async function create(env,name='Sweden'){const state=await getCustomerState(env,'w1');return ok(await call(env,'',{action:'create',name,workspaceVersion:state.version,config}));}
async function approve(env,id){let value=await ok(await call(env,id));for(const stage of WORKFLOW_STAGES)value=await ok(await call(env,id,{action:'approve-stage',revision:value.revision,stage}));return value;}
test('saved flows isolate workspace membership and retain current setup on the server',async()=>{const env=await fixture(),value=await create(env);assert.equal(value.flows.length,1);assert.equal(value.flows[0].summary.markets[0],'Sweden');assert.equal(value.flows[0].summary.companies,1);assert.equal(value.flows[0].metrics.opens,null);assert.equal((await call(env,value.id,undefined,'w2')).status,401);});
test('duplicate starts paused, clears recipients and research, and requires a full checklist',async()=>{const env=await fixture(),value=await create(env),copy=await ok(await call(env,value.id,{action:'duplicate',revision:1,name:'Finland',markets:['Finland']}));const flow=await ok(await call(env,copy.id));assert.equal(flow.status,'paused');assert.equal(flow.summary.markets[0],'Finland');assert.equal(flow.summary.companies,0);assert.equal(flow.review.length,6);assert.ok(flow.stages.every(s=>!s.approved));assert.equal((await call(env,copy.id,{action:'review',revision:1,confirmed:['markets']})).status,409);assert.equal((await call(env,copy.id,{action:'activate',revision:1,approved:true})).status,409);});
test('save/open/switch preserves progress and business details without crossing markets',async()=>{const env=await fixture(),se=await create(env),copy=await ok(await call(env,se.id,{action:'duplicate',revision:1,name:'Finland',markets:['Finland']}));let state=await getCustomerState(env,'w1');let result=await ok(await call(env,se.id,{action:'open',revision:1,workspaceVersion:state.version}));state=result.state;state.payload.discovery={pipeline:[{company:'Saved Sweden Buyer'}]};let save=await putCustomerState(env,{workspaceId:'w1',userId:'u1',expectedVersion:state.version,schemaVersion:1,payload:state.payload,role:'owner'});assert.equal(save.conflict,false);let flow=await ok(await call(env,se.id));assert.equal(flow.summary.companies,1);let opened=await ok(await call(env,copy.id,{action:'open',revision:1,workspaceVersion:save.state.version}));assert.equal(opened.state.payload.main.targetMarkets[0],'Finland');assert.deepEqual(opened.state.payload.discovery,{});flow=await ok(await call(env,se.id));opened=await ok(await call(env,se.id,{action:'open',revision:flow.revision,workspaceVersion:opened.state.version}));assert.equal(opened.state.payload.discovery.pipeline[0].company,'Saved Sweden Buyer');assert.equal(opened.state.payload.main.website,main.website);});
test('ten-flow capacity is enforced by database, including concurrent creations',async()=>{const env=await fixture();for(let i=0;i<9;i++)await create(env,'Flow '+i);const values=await Promise.all([call(env,'',{action:'create',name:'Tenth',workspaceVersion:1,config}),call(env,'',{action:'create',name:'Eleventh',workspaceVersion:1,config})]);assert.deepEqual(values.map(v=>v.status).sort(),[200,409]);assert.equal((await ok(await call(env,''))).flows.length,10);});
test('two active flows are enforced atomically and pausing frees a slot',async()=>{const env=await fixture(),ids=[];for(let i=0;i<3;i++){const value=await create(env,'Flow '+i);ids.push(value.id);await approve(env,value.id);}const responses=await Promise.all(ids.map(id=>call(env,id,{action:'activate',revision:1,approved:true})));assert.deepEqual(responses.map(r=>r.status).sort(),[200,200,409]);const active=(await ok(await call(env,''))).flows.filter(f=>f.status==='automatic');await ok(await call(env,active[0].id,{action:'pause',revision:1}));const waiting=ids.find(id=>!active.some(f=>f.id===id));await ok(await call(env,waiting,{action:'activate',revision:1,approved:true}));assert.equal((await ok(await call(env,''))).activeCount,2);});
test('runner executes two independent settings and immutable run attribution, with no browser required',async()=>{const env=await fixture();const ids=[];for(let i=0;i<2;i++){const v=await create(env,'Flow '+i);ids.push(v.id);await approve(env,v.id);await ok(await call(env,v.id,{action:'activate',revision:1,approved:true}));}const result=await runSavedFlows(env,{execute:async(stage,{result,guard})=>{await guard();return {...result,lastStage:stage};}});assert.equal(result.completed,2);const runs=env.DB.raw.prepare('SELECT * FROM approved_workflow_runs').all();assert.deepEqual(runs.map(r=>r.flow_id).sort(),ids.sort());assert.ok(runs.every(r=>r.status==='completed'&&JSON.parse(r.result_json).flowId===r.flow_id));});
test('shared business changes block unattended execution while preserving the other flow',async()=>{const env=await fixture(),se=await create(env);await approve(env,se.id);await ok(await call(env,se.id,{action:'activate',revision:1,approved:true}));const state=await getCustomerState(env,'w1');state.payload.main.brandIdentity.senderName='Changed';await putCustomerState(env,{workspaceId:'w1',userId:'u1',expectedVersion:state.version,schemaVersion:1,payload:state.payload,role:'owner'});assert.equal(await savedFlowAuthorized(env,'w1',1,se.id),false);assert.equal((await ok(await call(env,se.id))).summary.companies,1);});
test('workspace state CAS rejects stale flow switching and arbitrary flow-id writes',async()=>{const env=await fixture(),v=await create(env);assert.equal((await call(env,v.id,{action:'open',revision:1,workspaceVersion:0})).status,409);const state=await getCustomerState(env,'w1');state.payload.main.myFlow={id:v.id};await assert.rejects(()=>putCustomerState(env,{workspaceId:'w1',userId:'u1',expectedVersion:state.version,schemaVersion:1,payload:state.payload,role:'owner'}),/My Flows/);});
test('changing shared sender details in the current flow invalidates its own automatic approval',async()=>{const env=await fixture(),value=await create(env);const opened=await ok(await call(env,value.id,{action:'open',revision:1,workspaceVersion:1}));let v=await approve(env,value.id);await ok(await call(env,value.id,{action:'activate',revision:v.revision,approved:true}));const state=await getCustomerState(env,'w1');state.payload.main.brandIdentity.senderName='New sender';const saved=await putCustomerState(env,{workspaceId:'w1',userId:'u1',expectedVersion:state.version,schemaVersion:1,payload:state.payload,role:'owner'});assert.equal(saved.conflict,false);v=await ok(await call(env,value.id));assert.equal(v.status,'needs_review');assert.equal(await savedFlowAuthorized(env,'w1',v.revision,value.id),false);});
test('legacy migration keeps settings, approvals, run IDs and queued-message associations without two schedulers',()=>{const db=new DatabaseSync(':memory:');db.exec("PRAGMA foreign_keys=ON;CREATE TABLE workspaces(id TEXT PRIMARY KEY);CREATE TABLE users(id TEXT PRIMARY KEY);CREATE TABLE customer_workspace_state(workspace_id TEXT PRIMARY KEY,payload_json TEXT);CREATE TABLE outreach_automation_sequences(id TEXT PRIMARY KEY);INSERT INTO workspaces VALUES('legacy-w');INSERT INTO users VALUES('owner');INSERT INTO customer_workspace_state VALUES('legacy-w','{\"main\":{\"website\":\"https://seller.test\"}}');");db.exec(fs.readFileSync(new URL('../migrations/0027_approved_workflow.sql',import.meta.url),'utf8'));db.exec("INSERT INTO approved_workflows(workspace_id,revision,status,config_json,approvals_json,approved_by,approved_at) VALUES('legacy-w',4,'automatic','{\"preserved\":true}','{\"profile\":{\"hash\":\"original\"}}','owner','2026-10-01');INSERT INTO approved_workflow_runs(id,workspace_id,revision,status) VALUES('original-run','legacy-w',4,'completed');INSERT INTO outreach_automation_sequences(id,workflow_run_id,workflow_revision) VALUES('original-sequence','original-run',4);");db.exec(fs.readFileSync(new URL('../migrations/0030_saved_flows.sql',import.meta.url),'utf8'));const row=db.prepare('SELECT * FROM saved_flows').get();assert.equal(row.id,'legacy-legacy-w');assert.equal(row.revision,4);assert.equal(JSON.parse(row.config_json).preserved,true);assert.equal(JSON.parse(row.approvals_json).profile.hash,'original');assert.equal(db.prepare('SELECT flow_id FROM approved_workflow_runs').get().flow_id,row.id);assert.equal(db.prepare('SELECT workflow_run_id FROM outreach_automation_sequences').get().workflow_run_id,'original-run');assert.equal(db.prepare('SELECT status FROM approved_workflows').get().status,'stopped');});
test('flow metrics count actual linked replies and bookings, exclude automatic replies and cancelled meetings',async()=>{const env=await fixture(),v=await create(env);env.DB.raw.prepare("INSERT INTO approved_workflow_runs(id,workspace_id,flow_id,revision,status) VALUES('r','w1',?,1,'completed')").run(v.id);env.DB.raw.exec("INSERT INTO crm_companies(id,workspace_id,company_name,first_seen_at,last_seen_at,created_at,updated_at) VALUES('buyer','w1','Buyer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);INSERT INTO outreach_automation_sequences(id,workspace_id,gmail_connection_workspace_id,source_package_key,domain,recipient,approved_at,initial_subject,initial_body,workflow_run_id,workflow_revision) VALUES('s','w1','w1','p','buyer.test','buyer@buyer.test',CURRENT_TIMESTAMP,'Hello','Body','r',1);INSERT INTO outreach_automation_queue(id,workspace_id,sequence_id,gmail_connection_workspace_id,recipient,subject,body,status,earliest_send_at,scheduled_send_at,idempotency_key,sent_at) VALUES('q','w1','s','w1','buyer@buyer.test','Hello','Body','sent',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p',CURRENT_TIMESTAMP);");const insert=(id,type,metadata)=>env.DB.raw.prepare("INSERT INTO crm_activities(id,workspace_id,company_id,activity_type,metadata_json,occurred_at,created_at) VALUES(?,'w1','buyer',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run(id,type,JSON.stringify(metadata));insert('auto','email.reply_received',{automation_sequence_id:'s',category:'out_of_office'});let metrics=(await ok(await call(env,''))).flows[0].metrics;assert.equal(metrics.replies,0);insert('human','email.reply_received',{automation_sequence_id:'s',category:'positive'});insert('booking','meeting.booked',{automation_sequence_id:'s',scheduled_event_uri:'meeting1'});metrics=(await ok(await call(env,''))).flows[0].metrics;assert.equal(metrics.providerConfirmedSent,1);assert.equal(metrics.replies,1);assert.equal(metrics.meetings,1);assert.equal(metrics.delivered,null);insert('cancel','meeting.cancelled',{automation_sequence_id:'s',scheduled_event_uri:'meeting1'});assert.equal((await ok(await call(env,''))).flows[0].metrics.meetings,0);});
test('a market-only switch does not invalidate the other flow’s shared business settings',async()=>{const env=await fixture(),value=await create(env);const copy=await ok(await call(env,value.id,{action:'duplicate',revision:1,name:'Finland',markets:['Finland']}));await ok(await call(env,copy.id,{action:'open',revision:1,workspaceVersion:1}));const list=await ok(await call(env,''));const original=list.flows.find(f=>f.id===value.id);assert.equal(original.review.some(r=>r.id==='business'),false);assert.equal((await ok(await call(env,value.id))).sharedChanged,false);});
test('two active flows may use different research frequencies while preserving shared mailbox limits',async()=>{const env=await fixture(),first=await create(env);await approve(env,first.id);await ok(await call(env,first.id,{action:'activate',revision:1,approved:true}));const second=await create(env,'Weekly');let v=await ok(await call(env,second.id,{action:'save',revision:1,config:{...config,delivery:{...config.delivery,frequency:'weekly'}}}));v=await approve(env,second.id);await ok(await call(env,second.id,{action:'activate',revision:v.revision,approved:true}));assert.equal((await ok(await call(env,''))).activeCount,2);assert.equal((await ok(await call(env,second.id))).config.delivery.frequency,'weekly');});
