import test from 'node:test';import assert from 'node:assert/strict';import {storageFixture} from './writing-reference-fixture.mjs';import {sha256} from '../src/security.js';
import app from '../src/app.js';
const routes=await import('../src/writing-reference-routes.js').catch(()=>({}));
async function fixture(){const env=storageFixture();env.WRITING_REFERENCES_ALLOWED_WORKSPACES='w1';env.DB.raw.exec("CREATE TABLE users(id TEXT,email TEXT,display_name TEXT,role TEXT); CREATE TABLE sessions(token_hash TEXT,user_id TEXT,expires_at TEXT); CREATE TABLE workspace_members(workspace_id TEXT,user_id TEXT,role TEXT); INSERT INTO users VALUES('u1','owner@example.com','Owner','customer'); INSERT INTO workspace_members VALUES('w1','u1','owner');");await env.DB.prepare("INSERT INTO sessions VALUES(?,'u1',datetime('now','+1 day'))").bind(await sha256('session')).run();return env;}
function req(path='',options={}){return new Request('https://api.example.test/api/writing-references'+path+'?workspace_id=w1',{headers:{Cookie:'leadintel_session=session'},...options});}
test('large raw uploads use a short-lived single-use ticket without cookies and reject replay',async()=>{const env=await fixture();const ticket=await routes.handleWritingReferenceRoute(req('/upload-ticket',{method:'POST',body:JSON.stringify({slot:1,expectedRevision:0,expectedSourceId:null,expectedSlotRevision:0})}),env);assert.equal(ticket.status,201);const data=await ticket.json();assert.equal(new URL(data.uploadUrl).pathname,'/writing-reference-upload');const form=new FormData();form.set('ticket',data.ticket);form.set('file',new File(['a'.repeat(6000000)],'large.txt',{type:'text/plain'}));const request=()=>new Request(data.uploadUrl,{method:'POST',body:form});const response=await routes.handleWritingReferenceRoute(request(),env);assert.equal(response.status,422,'size passes transport; text limit fails on server');assert.equal((await routes.handleWritingReferenceRoute(request(),env)).status,401);});
test('expired upload tickets cannot write any private objects',async()=>{const env=await fixture();const r=await routes.handleWritingReferenceRoute(req('/upload-ticket',{method:'POST',body:JSON.stringify({slot:1,expectedRevision:0,expectedSlotRevision:0})}),env);assert.equal(r.status,201);const data=await r.json();env.DB.raw.prepare('UPDATE writing_reference_upload_tickets SET expires_at=0').run();const form=new FormData();form.set('ticket',data.ticket);form.set('file',new File(['guide'],'g.txt',{type:'text/plain'}));const response=await routes.handleWritingReferenceRoute(new Request(data.uploadUrl,{method:'POST',body:form}),env);assert.equal(response.status,401);assert.equal(env.objects.size,0);});
test('source routes deny anonymous and unentitled accounts before file storage access',async()=>{
 assert.equal(typeof routes.handleWritingReferenceRoute,'function');const env=await fixture();assert.equal((await routes.handleWritingReferenceRoute(req('',{headers:{}}),env)).status,401);
 env.WRITING_REFERENCES_ALLOWED_WORKSPACES='';assert.equal((await routes.handleWritingReferenceRoute(req(),env)).status,403);
});
test('Worker entry point routes unauthenticated source requests to private access denial',async()=>{const r=await app.fetch(new Request('https://api.example.test/api/writing-references?workspace_id=w1'),{APP_ORIGIN:'https://example.test'});assert.equal(r.status,401);});
test('Worker entry point serves the authenticated three-slot API',async()=>{const env=await fixture();const r=await app.fetch(req(),env);assert.equal(r.status,200);assert.deepEqual((await r.json()).cards,[]);});
test('authenticated upload recomputes text, rejects stale replacement and removes private original',async()=>{
 assert.equal(typeof routes.handleWritingReferenceRoute,'function');const env=await fixture();const form=new FormData();form.set('slot','1');form.set('expectedRevision','0');form.set('file',new File(['Ask one useful question.'],'guide.txt',{type:'text/plain'}));form.set('extracted','INJECTED');
 const response=await routes.handleWritingReferenceRoute(req('',{method:'POST',body:form}),env);assert.equal(response.status,201);
 const data=await response.json(),card=data.cards[0];assert.equal(card.status,'Processing');assert.equal(card.active,false);assert.ok(!JSON.stringify(data).includes('original_key'));
 const original=await routes.handleWritingReferenceRoute(req('/'+card.id+'/original'),env);assert.equal(await original.text(),'Ask one useful question.');
 const bad=await routes.handleWritingReferenceRoute(req('/'+card.id,{method:'PATCH',headers:{Cookie:'leadintel_session=session','Content-Type':'application/json'},body:JSON.stringify({expectedRevision:0,active:true})}),env);assert.equal(bad.status,409);
 const del=await routes.handleWritingReferenceRoute(req('/'+card.id,{method:'DELETE',headers:{Cookie:'leadintel_session=session','Content-Type':'application/json'},body:JSON.stringify({expectedRevision:card.revision})}),env);assert.equal(del.status,200);assert.equal(env.objects.size,0);
 assert.equal((await routes.handleWritingReferenceRoute(req('/'+card.id+'/original'),env)).status,404);
});
