import {test} from 'node:test';import assert from 'node:assert/strict';import {resolveWritingContext,assertWritingContextCurrent} from '../src/writing-reference-context.js';
import * as contextModule from '../src/writing-reference-context.js';
function env(){let revision=1;const cards=[{id:'s1',slot:1,workspaceId:'w1',revision:1,status:'Ready',active:true,instruction:'Use for openings',techniques:[{id:'t1',name:'Friendly opening',principle:'Ask a relevant question',uses:['opening'],cautions:['No invented facts'],pattern:'Hi {{firstName}}',locations:['page:1']}]}];return {WRITING_REFERENCE_STORE:{snapshot:async()=>({cards,referenceRevision:revision}),revision:async()=>revision},deactivate(){cards[0].active=false;revision++;}};}
test('protected and numbered styles bypass writing sources',async()=>{for(const mode of ['professional','nlp','friendly','brutal','template-1','linkedin-template-1'])assert.equal(await resolveWritingContext({}, {workspaceId:'w1'}, {mode,channel:'email',query:'opening'}),null);});
test('original mode includes only scoped ready active techniques and no browser guidance',async()=>{const e=env();const r=await resolveWritingContext(e,{workspaceId:'w1'},{mode:'original',channel:'linkedin',query:'opening',techniques:[{name:'invented'}]});assert.deepEqual(r.sourceRefs,[{id:'s1',revision:1}]);assert.equal(r.techniques[0].name,'Friendly opening');assert.equal(r.referenceRevision,1);await assert.rejects(resolveWritingContext(e,{workspaceId:'w2'},{mode:'original',channel:'email',query:'opening'}),/workspace/i);});
test('deactivated sources do not influence future or in-flight generation',async()=>{const e=env(),scope={workspaceId:'w1'};const r=await resolveWritingContext(e,scope,{mode:'original',channel:'email',query:'opening'});e.deactivate();await assert.rejects(assertWritingContextCurrent(e,scope,r),/changed/i);assert.equal(await resolveWritingContext(e,scope,{mode:'original',channel:'email',query:'opening'}),null);});
test('selected techniques retrieve only bounded source passages at their verified locations',async()=>{const e=env(),snapshot=e.WRITING_REFERENCE_STORE.snapshot;e.WRITING_REFERENCE_STORE.snapshot=async()=>{const s=await snapshot();s.cards[0].text_key='private-text';return s;};e.WRITING_REFERENCES_BUCKET={get:async()=>({text:async()=>JSON.stringify({sections:[{location:'page:1',text:'A useful opening asks a specific question.'},{location:'page:2',text:'UNRELATED'}]})})};const c=await resolveWritingContext(e,{workspaceId:'w1'},{mode:'original',channel:'email',query:'opening'});assert.equal(c.passages.length,1);assert.equal(c.passages[0].location,'page:1');assert.ok(!JSON.stringify(c).includes('UNRELATED'));});
test('generation envelope retains the exact original request with no active sources and adds untrusted guidance only to original outreach',async()=>{
 assert.equal(typeof contextModule.prepareWritingReferenceGeneration,'function');const e=env();e.WRITING_REFERENCES_ALLOWED_WORKSPACES='w1';
 const body={task:'outreach-generation',writing_mode:'original',channel:'email',system:'Existing facts',prompt:'Write an opening'};
 const ready=await contextModule.prepareWritingReferenceGeneration(e,{workspaceId:'w1'},body);assert.ok(ready.prompt.includes('Friendly opening'));assert.ok(ready.system.includes('verified'));assert.deepEqual(ready.context.sourceRefs,[{id:'s1',revision:1}]);
 for(const mode of ['professional','curiosity','friendly','brutal','template-1'])assert.deepEqual(await contextModule.prepareWritingReferenceGeneration(e,{workspaceId:'w1'},{...body,writing_mode:mode}),{system:body.system,prompt:body.prompt,context:null});
 e.deactivate();assert.deepEqual(await contextModule.prepareWritingReferenceGeneration(e,{workspaceId:'w1'},body),{system:body.system,prompt:body.prompt,context:null});
});
