import {corsHeaders,allowedOrigin,sha256,randomToken,cookieValue,sessionCookie} from './security.js';
import {safeReturnUrl,buildGoogleAuthorizationUrl,exchangeGoogleCode,fetchGoogleIdentity,buildMicrosoftAuthorizationUrl,exchangeMicrosoftCode,fetchMicrosoftIdentity,importAesKey,encryptSecret,decryptSecret,createOAuthState,consumeOAuthState,createPkcePair} from './oauth.js';
import {getCustomerState,putCustomerState} from './customer-state.js';
import {normalizeEmail,buildMimeMessage,refreshGoogleAccessToken,sendGmailMessage,fetchGmailThread,normalizeInboundReplies} from './gmail.js';
import {refreshMicrosoftAccessToken,sendMicrosoftMessage} from './microsoft-mail.js';
import {findCrmCompanyByDomain,appendCrmActivity,setCrmPipelineStage} from './crm.js';

const uuid=()=>crypto.randomUUID();
const json=(value,status=200,headers={})=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const error=(message,status,headers,extra={})=>json({error:message,...extra},status,headers);
const redirect=(location,headers={})=>new Response(null,{status:302,headers:{Location:location,'Cache-Control':'no-store',...headers}});
const GOOGLE_LOGIN_SCOPES=['openid','email','profile'];
const GMAIL_SCOPES=['openid','email','https://www.googleapis.com/auth/gmail.send','https://www.googleapis.com/auth/gmail.readonly'];
const MICROSOFT_LOGIN_SCOPES=['openid','profile','email','https://graph.microsoft.com/User.Read'];
const MICROSOFT_MAIL_SCOPES=['openid','profile','email','offline_access','https://graph.microsoft.com/User.Read','https://graph.microsoft.com/Mail.Send'];

async function sessionUser(request,env){
  const token=cookieValue(request,'leadintel_session');if(!token)return null;const tokenHash=await sha256(token);
  return env.DB.prepare(`SELECT users.id,users.email,users.display_name,users.role,sessions.expires_at FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND sessions.expires_at>datetime('now')`).bind(tokenHash).first();
}
async function membership(env,workspaceId,userId){return env.DB.prepare('SELECT role FROM workspace_members WHERE workspace_id=? AND user_id=?').bind(workspaceId,userId).first();}
async function audit(env,{workspaceId=null,userId=null,type,entityType=null,entityId=null,metadata={}}){
  await env.DB.prepare(`INSERT INTO audit_events(id,workspace_id,user_id,event_type,entity_type,entity_id,metadata_json) VALUES(?,?,?,?,?,?,?)`).bind(uuid(),workspaceId,userId,type,entityType,entityId,JSON.stringify(metadata)).run();
}
function configReady(env,names){return names.every(name=>String(env[name]||'').trim());}
function configuredCustomerReturn(env,requestUrl){return safeReturnUrl(requestUrl,env.CUSTOMER_APP_URL)||safeReturnUrl(env.CUSTOMER_APP_URL,env.CUSTOMER_APP_URL);}
function withResult(url,params){const out=new URL(url);for(const [key,value] of Object.entries(params))if(value!==undefined&&value!==null)out.searchParams.set(key,String(value));return out.toString();}
function normalizeDomain(value){return String(value||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split(/[/?#]/)[0].slice(0,253);}
function validIdempotency(value){return /^[A-Za-z0-9._:-]{16,128}$/.test(String(value||''));}
function googleConfig(env,kind){return {clientId:env.GOOGLE_OAUTH_CLIENT_ID,clientSecret:env.GOOGLE_OAUTH_CLIENT_SECRET,redirectUri:kind==='gmail'?env.GMAIL_OAUTH_REDIRECT_URI:env.GOOGLE_OAUTH_REDIRECT_URI};}function microsoftConfig(env,kind='login'){return {clientId:env.MICROSOFT_OAUTH_CLIENT_ID,clientSecret:env.MICROSOFT_OAUTH_CLIENT_SECRET,redirectUri:kind==='mail'?env.MICROSOFT_MAIL_OAUTH_REDIRECT_URI:env.MICROSOFT_OAUTH_REDIRECT_URI};}
async function createSession(env,userId){const token=randomToken(32);const hash=await sha256(token);const hours=Math.max(1,Number(env.SESSION_TTL_HOURS)||168);await env.DB.batch([env.DB.prepare("DELETE FROM sessions WHERE expires_at<=datetime('now')"),env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now',?))").bind(hash,userId,`+${hours} hours`)]);return {token,hours};}
async function ensureDefaultWorkspace(env,user){
  const existing=await env.DB.prepare(`SELECT w.id,w.name,w.market,wm.role FROM workspace_members wm JOIN workspaces w ON w.id=wm.workspace_id WHERE wm.user_id=? ORDER BY w.created_at ASC LIMIT 1`).bind(user.id).first();if(existing)return existing;
  const suffix=(await sha256(user.email)).slice(0,16);const workspaceId=`workspace-${suffix}`;const name=`${String(user.display_name||user.email.split('@')[0]).slice(0,80)} Workspace`;
  await env.DB.batch([env.DB.prepare(`INSERT OR IGNORE INTO workspaces(id,name,market,owner_user_id) VALUES(?,?,?,?)`).bind(workspaceId,name,'Global',user.id),env.DB.prepare(`INSERT OR IGNORE INTO workspace_members(workspace_id,user_id,role) VALUES(?,?,?)`).bind(workspaceId,user.id,'owner')]);
  return {id:workspaceId,name,market:'Global',role:'owner'};
}
async function requireMember(request,env,workspaceId,roles=[]){const user=await sessionUser(request,env);if(!user)return {error:'Authentication required',status:401};const member=await membership(env,workspaceId,user.id);if(!member)return {error:'Workspace access denied',status:403};if(roles.length&&!roles.includes(member.role))return {error:'Workspace role is not permitted',status:403};return {user,member};}
async function connectedGmail(env,workspaceId){return env.DB.prepare(`SELECT workspace_id,user_id,google_email,encrypted_refresh_token,scopes,status,history_id,connected_at,updated_at FROM gmail_connections WHERE workspace_id=? AND status='connected'`).bind(workspaceId).first();}
async function gmailAccess(env,connection){if(!configReady(env,['GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET','OAUTH_TOKEN_ENCRYPTION_KEY']))throw new Error('Gmail integration is not configured');const key=await importAesKey(env.OAUTH_TOKEN_ENCRYPTION_KEY);const refreshToken=await decryptSecret(connection.encrypted_refresh_token,key);return refreshGoogleAccessToken(refreshToken,googleConfig(env,'gmail'));}
async function connectedMicrosoftMail(env,workspaceId){return env.DB.prepare(`SELECT workspace_id,user_id,microsoft_email,encrypted_refresh_token,scopes,status,connected_at,updated_at FROM microsoft_mail_connections WHERE workspace_id=? AND status='connected'`).bind(workspaceId).first();}
async function microsoftMailAccess(env,connection){if(!configReady(env,['MICROSOFT_OAUTH_CLIENT_ID','MICROSOFT_OAUTH_CLIENT_SECRET','OAUTH_TOKEN_ENCRYPTION_KEY']))throw new Error('Microsoft mail integration is not configured');const key=await importAesKey(env.OAUTH_TOKEN_ENCRYPTION_KEY);const refreshToken=await decryptSecret(connection.encrypted_refresh_token,key);const token=await refreshMicrosoftAccessToken(refreshToken,{...microsoftConfig(env,'mail'),scopes:MICROSOFT_MAIL_SCOPES});if(token.refreshToken&&token.refreshToken!==refreshToken){const encrypted=await encryptSecret(token.refreshToken,key);await env.DB.prepare(`UPDATE microsoft_mail_connections SET encrypted_refresh_token=?,scopes=?,updated_at=CURRENT_TIMESTAMP WHERE workspace_id=?`).bind(encrypted,token.scope||connection.scopes,connection.workspace_id).run();}return token;}
async function dailyEmailCount(env,workspaceId){const [gmail,microsoft]=await Promise.all([env.DB.prepare(`SELECT COUNT(*) AS count FROM gmail_messages WHERE workspace_id=? AND status IN ('sending','sent') AND COALESCE(sent_at,created_at)>=date('now','start of day')`).bind(workspaceId).first(),env.DB.prepare(`SELECT COUNT(*) AS count FROM microsoft_mail_messages WHERE workspace_id=? AND status IN ('sending','sent') AND COALESCE(sent_at,created_at)>=date('now','start of day')`).bind(workspaceId).first()]);return Number(gmail?.count||0)+Number(microsoft?.count||0);}
async function ensureCustomerProject(env,{workspaceId,userId,name,website=''}){const id=uuid();await env.DB.prepare(`INSERT INTO customer_projects(id,workspace_id,name,website,created_by) VALUES(?,?,?,?,?)`).bind(id,workspaceId,String(name||'New customer').trim().slice(0,160),normalizeDomain(website),userId).run();return env.DB.prepare('SELECT * FROM customer_projects WHERE id=?').bind(id).first();}
async function projectAccess(env,workspaceId,projectId){return env.DB.prepare(`SELECT id,workspace_id,name,website,status,created_by,created_at,updated_at FROM customer_projects WHERE id=? AND workspace_id=? AND status='active'`).bind(projectId,workspaceId).first();}

export async function handleSaasRoute(request,env,corsOverride){
  const url=new URL(request.url);const cors=corsOverride??corsHeaders(allowedOrigin(request,env.APP_ORIGIN));const path=url.pathname;
  const known=path.startsWith('/api/auth/google/')||path.startsWith('/api/auth/microsoft/')||path==='/api/workspaces'||path==='/api/customer/state'||path.startsWith('/api/customer/projects')||path==='/api/customer/activity'||path.startsWith('/api/integrations/gmail/')||path.startsWith('/api/integrations/microsoft-mail/');if(!known)return null;

  if(path==='/api/auth/google/start'&&request.method==='GET'){
    if(!configReady(env,['GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET','GOOGLE_OAUTH_REDIRECT_URI','CUSTOMER_APP_URL']))return error('Google sign-in is not configured',503,cors);
    const returnTo=configuredCustomerReturn(env,url.searchParams.get('return_to'));if(!returnTo)return error('Invalid return URL',400,cors);
    const state=await createOAuthState(env,{purpose:'login',returnTo});const location=buildGoogleAuthorizationUrl({...googleConfig(env,'login'),state,scopes:GOOGLE_LOGIN_SCOPES,prompt:'select_account'});return redirect(location,cors);
  }
  if(path==='/api/auth/google/callback'&&request.method==='GET'){
    const state=await consumeOAuthState(env,{rawState:url.searchParams.get('state'),purpose:'login'});if(!state)return error('Google sign-in state is invalid or expired',400,cors);
    try{
      const token=await exchangeGoogleCode(url.searchParams.get('code'),googleConfig(env,'login'));const identity=await fetchGoogleIdentity(token.accessToken);let user=await env.DB.prepare('SELECT users.* FROM user_identities JOIN users ON users.id=user_identities.user_id WHERE user_identities.provider=? AND user_identities.provider_subject=?').bind('google',identity.sub).first();if(!user)user=await env.DB.prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE').bind(identity.email).first();
      if(!user){const id=`user-${(await sha256(identity.email)).slice(0,24)}`;await env.DB.prepare(`INSERT INTO users(id,email,display_name,role,last_login_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP)`).bind(id,identity.email,identity.name,'owner').run();user={id,email:identity.email,display_name:identity.name,role:'owner'};}
      else{await env.DB.prepare('UPDATE users SET display_name=?,last_login_at=CURRENT_TIMESTAMP WHERE id=?').bind(identity.name||user.display_name,user.id).run();user={...user,display_name:identity.name||user.display_name};}
      await env.DB.prepare(`INSERT INTO user_identities(id,provider,provider_subject,user_id,email,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(provider,provider_subject) DO UPDATE SET user_id=excluded.user_id,email=excluded.email,updated_at=CURRENT_TIMESTAMP`).bind(uuid(),'google',identity.sub,user.id,identity.email).run();const workspace=await ensureDefaultWorkspace(env,user);const session=await createSession(env,user.id);await audit(env,{workspaceId:workspace.id,userId:user.id,type:'auth.google_login_succeeded',entityType:'user',entityId:user.id,metadata:{workspace_id:workspace.id}});
      return redirect(withResult(state.return_to,{auth:'success',workspace_id:workspace.id}),{...cors,'Set-Cookie':sessionCookie(session.token,session.hours*3600)});
    }catch(cause){return redirect(withResult(state.return_to,{auth:'error',reason:String(cause?.message||'Google sign-in failed').slice(0,160)}),cors);}
  }

  if(path==='/api/auth/microsoft/start'&&request.method==='GET'){
    if(!configReady(env,['MICROSOFT_OAUTH_CLIENT_ID','MICROSOFT_OAUTH_CLIENT_SECRET','MICROSOFT_OAUTH_REDIRECT_URI','CUSTOMER_APP_URL']))return error('Microsoft sign-in is not configured',503,cors);const returnTo=configuredCustomerReturn(env,url.searchParams.get('return_to'));if(!returnTo)return error('Invalid return URL',400,cors);const pkce=await createPkcePair();const state=await createOAuthState(env,{purpose:'login',returnTo,codeVerifier:pkce.verifier});const location=buildMicrosoftAuthorizationUrl({...microsoftConfig(env),state,scopes:MICROSOFT_LOGIN_SCOPES,prompt:'select_account',codeChallenge:pkce.challenge});return redirect(location,cors);
  }
  if(path==='/api/auth/microsoft/callback'&&request.method==='GET'){
    const state=await consumeOAuthState(env,{rawState:url.searchParams.get('state'),purpose:'login'});if(!state)return error('Microsoft sign-in state is invalid or expired',400,cors);try{const token=await exchangeMicrosoftCode(url.searchParams.get('code'),{...microsoftConfig(env),scopes:MICROSOFT_LOGIN_SCOPES,codeVerifier:state.pkce_verifier||''});const identity=await fetchMicrosoftIdentity(token.accessToken);let user=await env.DB.prepare('SELECT users.* FROM user_identities JOIN users ON users.id=user_identities.user_id WHERE user_identities.provider=? AND user_identities.provider_subject=?').bind('microsoft',identity.sub).first();if(!user)user=await env.DB.prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE').bind(identity.email).first();if(!user){const id=`user-${(await sha256(identity.email)).slice(0,24)}`;await env.DB.prepare(`INSERT INTO users(id,email,display_name,role,last_login_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP)`).bind(id,identity.email,identity.name,'owner').run();user={id,email:identity.email,display_name:identity.name,role:'owner'};}else{await env.DB.prepare('UPDATE users SET display_name=?,last_login_at=CURRENT_TIMESTAMP WHERE id=?').bind(identity.name||user.display_name,user.id).run();user={...user,display_name:identity.name||user.display_name};}await env.DB.prepare(`INSERT INTO user_identities(id,provider,provider_subject,user_id,email,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(provider,provider_subject) DO UPDATE SET user_id=excluded.user_id,email=excluded.email,updated_at=CURRENT_TIMESTAMP`).bind(uuid(),'microsoft',identity.sub,user.id,identity.email).run();const workspace=await ensureDefaultWorkspace(env,user);const session=await createSession(env,user.id);await audit(env,{workspaceId:workspace.id,userId:user.id,type:'auth.microsoft_login_succeeded',entityType:'user',entityId:user.id,metadata:{workspace_id:workspace.id}});return redirect(withResult(state.return_to,{auth:'success',workspace_id:workspace.id}),{...cors,'Set-Cookie':sessionCookie(session.token,session.hours*3600)});}catch(cause){return redirect(withResult(state.return_to,{auth:'error',reason:String(cause?.message||'Microsoft sign-in failed').slice(0,160)}),cors);}
  }

  if(path==='/api/workspaces'&&request.method==='GET'){
    const user=await sessionUser(request,env);if(!user)return error('Authentication required',401,cors);const {results=[]}=await env.DB.prepare(`SELECT w.id,w.name,w.market,wm.role,w.updated_at FROM workspace_members wm JOIN workspaces w ON w.id=wm.workspace_id WHERE wm.user_id=? ORDER BY w.created_at ASC`).bind(user.id).all();return json({workspaces:results},200,cors);
  }

  if(path==='/api/customer/projects'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,request.method==='POST'||request.method==='DELETE'?['owner','researcher','sales']:[]);if(access.error)return error(access.error,access.status,cors);
    if(request.method==='GET'){const {results=[]}=await env.DB.prepare(`SELECT id,name,website,status,created_by,created_at,updated_at FROM customer_projects WHERE workspace_id=? AND status='active' ORDER BY created_at ASC`).bind(workspaceId).all();return json({projects:results},200,cors);}
    if(request.method==='POST'){const body=await request.json().catch(()=>null);if(!body||!String(body.name||'').trim())return error('Project name is required',400,cors);const project=await ensureCustomerProject(env,{workspaceId,userId:access.user.id,name:body.name,website:body.website});await audit(env,{workspaceId,userId:access.user.id,type:'customer_project.created',entityType:'customer_project',entityId:project.id});return json({project},201,cors);}
    if(request.method==='DELETE'){const projectId=url.searchParams.get('project_id')||'';const project=await projectAccess(env,workspaceId,projectId);if(!project)return error('Customer project not found',404,cors);await env.DB.prepare(`UPDATE customer_projects SET status='archived',archived_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(projectId).run();await audit(env,{workspaceId,userId:access.user.id,type:'customer_project.archived',entityType:'customer_project',entityId:projectId});return json({ok:true,project_id:projectId},200,cors);}
    return error('Method not allowed',405,cors);
  }

  if(path==='/api/customer/activity'&&request.method==='GET'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId);if(access.error)return error(access.error,access.status,cors);const projectId=url.searchParams.get('project_id')||'';const since=url.searchParams.get('since')||new Date(Date.now()-86400000).toISOString();const project=projectId?await projectAccess(env,workspaceId,projectId):null;if(projectId&&!project)return error('Customer project not found',404,cors);
    const gmailSentQuery=projectId?env.DB.prepare(`SELECT COUNT(*) AS count FROM gmail_messages WHERE workspace_id=? AND customer_project_id=? AND status='sent' AND sent_at>=?`).bind(workspaceId,projectId,since):env.DB.prepare(`SELECT COUNT(*) AS count FROM gmail_messages WHERE workspace_id=? AND status='sent' AND sent_at>=?`).bind(workspaceId,since);const microsoftSentQuery=projectId?env.DB.prepare(`SELECT COUNT(*) AS count FROM microsoft_mail_messages WHERE workspace_id=? AND customer_project_id=? AND status='sent' AND sent_at>=?`).bind(workspaceId,projectId,since):env.DB.prepare(`SELECT COUNT(*) AS count FROM microsoft_mail_messages WHERE workspace_id=? AND status='sent' AND sent_at>=?`).bind(workspaceId,since);const [gmailSent,microsoftSent]=await Promise.all([gmailSentQuery.first(),microsoftSentQuery.first()]);const sentCount=Number(gmailSent?.count||0)+Number(microsoftSent?.count||0);const replyQuery=projectId?env.DB.prepare(`SELECT COUNT(*) AS count FROM gmail_replies WHERE workspace_id=? AND customer_project_id=? AND received_at>=?`).bind(workspaceId,projectId,since):env.DB.prepare(`SELECT COUNT(*) AS count FROM gmail_replies WHERE workspace_id=? AND received_at>=?`).bind(workspaceId,since);const replies=await replyQuery.first();const recent=projectId?await env.DB.prepare(`SELECT * FROM (SELECT id,recipient,subject,status,sent_at,'gmail' AS provider,NULL AS provider_status,gmail_thread_id AS provider_thread_id FROM gmail_messages WHERE workspace_id=? AND customer_project_id=? UNION ALL SELECT id,recipient,subject,status,sent_at,'microsoft' AS provider,provider_status,NULL AS provider_thread_id FROM microsoft_mail_messages WHERE workspace_id=? AND customer_project_id=?) ORDER BY COALESCE(sent_at,id) DESC LIMIT 50`).bind(workspaceId,projectId,workspaceId,projectId).all():await env.DB.prepare(`SELECT * FROM (SELECT id,recipient,subject,status,sent_at,'gmail' AS provider,NULL AS provider_status,gmail_thread_id AS provider_thread_id FROM gmail_messages WHERE workspace_id=? UNION ALL SELECT id,recipient,subject,status,sent_at,'microsoft' AS provider,provider_status,NULL AS provider_thread_id FROM microsoft_mail_messages WHERE workspace_id=?) ORDER BY COALESCE(sent_at,id) DESC LIMIT 50`).bind(workspaceId,workspaceId).all();return json({project,limits:{daily_minimum:10,daily_maximum:20,configured_daily_limit:20,sent_today:sentCount,remaining_today:Math.max(0,20-sentCount)},replies_today:Number(replies?.count||0),recent:recent.results||[]},200,cors);
  }

  if(path==='/api/customer/state'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,request.method==='PUT'?['owner','researcher','sales']:[]);if(access.error)return error(access.error,access.status,cors);
    const projectId=url.searchParams.get('project_id')||'';
    if(projectId){
      const project=await projectAccess(env,workspaceId,projectId);if(!project)return error('Customer project not found',404,cors);
      if(request.method==='GET'){const row=await env.DB.prepare('SELECT project_id,schema_version,version,payload_json,updated_by,updated_at FROM customer_project_state WHERE project_id=?').bind(projectId).first();return json(row?{project_id:row.project_id,schema_version:row.schema_version,version:row.version,payload:JSON.parse(row.payload_json),updated_by:row.updated_by,updated_at:row.updated_at}:{project_id:projectId,schema_version:1,version:1,payload:{},updated_by:null,updated_at:null},200,cors);}
      if(request.method==='PUT'){const contentLength=Number(request.headers.get('Content-Length')||0);if(contentLength>1150000)return error('Customer state request is too large',413,cors);const body=await request.json().catch(()=>null);if(!body||typeof body.payload!=='object')return error('Customer state payload is required',400,cors);const existing=await env.DB.prepare('SELECT version FROM customer_project_state WHERE project_id=?').bind(projectId).first();const expected=body.version===undefined?null:Number(body.version);if(existing&&expected!==null&&Number(existing.version)!==expected)return json({error:'Customer state version conflict',current:existing},409,cors);const version=Number(existing?.version||0)+1;await env.DB.prepare(`INSERT INTO customer_project_state(project_id,schema_version,version,payload_json,updated_by,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(project_id) DO UPDATE SET schema_version=excluded.schema_version,version=excluded.version,payload_json=excluded.payload_json,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(projectId,Number(body.schema_version||1),version,JSON.stringify(body.payload),access.user.id).run();const state={project_id:projectId,schema_version:Number(body.schema_version||1),version,payload:body.payload,updated_by:access.user.id};await audit(env,{workspaceId,userId:access.user.id,type:'customer_project_state.saved',entityType:'customer_project_state',entityId:projectId,metadata:{version}});return json(state,200,cors);}
      return error('Method not allowed',405,cors);
    }
    if(request.method==='GET')return json(await getCustomerState(env,workspaceId),200,cors);
    if(request.method==='PUT'){
      const contentLength=Number(request.headers.get('Content-Length')||0);if(contentLength>1150000)return error('Customer state request is too large',413,cors);const body=await request.json().catch(()=>null);if(!body)return error('Customer state payload is required',400,cors);
      try{const result=await putCustomerState(env,{workspaceId,userId:access.user.id,expectedVersion:body.version,schemaVersion:body.schema_version,payload:body.payload});if(result.conflict)return json({error:'Customer state version conflict',current:result.current},409,cors);await audit(env,{workspaceId,userId:access.user.id,type:'customer_state.saved',entityType:'customer_workspace_state',entityId:workspaceId,metadata:{version:result.state.version,schema_version:result.state.schema_version}});return json(result.state,200,cors);}catch(cause){return error(String(cause?.message||'Invalid customer state'),400,cors);}
    }
    return error('Method not allowed',405,cors);
  }

  if(path==='/api/integrations/gmail/status'&&request.method==='GET'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId);if(access.error)return error(access.error,access.status,cors);const connection=await env.DB.prepare(`SELECT google_email,scopes,status,connected_at,updated_at FROM gmail_connections WHERE workspace_id=?`).bind(workspaceId).first();return json({configured:configReady(env,['GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET','GMAIL_OAUTH_REDIRECT_URI','OAUTH_TOKEN_ENCRYPTION_KEY']),connected:connection?.status==='connected',email:connection?.status==='connected'?connection.google_email:'',scopes:connection?.status==='connected'?connection.scopes:'',connected_at:connection?.connected_at||null,role:access.member.role},200,cors);
  }
  if(path==='/api/integrations/gmail/start'&&request.method==='GET'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner']);if(access.error)return error(access.error,access.status,cors);if(!configReady(env,['GOOGLE_OAUTH_CLIENT_ID','GOOGLE_OAUTH_CLIENT_SECRET','GMAIL_OAUTH_REDIRECT_URI','OAUTH_TOKEN_ENCRYPTION_KEY','CUSTOMER_APP_URL']))return error('Gmail integration is not configured',503,cors);
    const returnTo=configuredCustomerReturn(env,url.searchParams.get('return_to'));if(!returnTo)return error('Invalid return URL',400,cors);const state=await createOAuthState(env,{purpose:'gmail',userId:access.user.id,workspaceId,returnTo});const location=buildGoogleAuthorizationUrl({...googleConfig(env,'gmail'),state,scopes:GMAIL_SCOPES,accessType:'offline',prompt:'consent',loginHint:access.user.email});return redirect(location,cors);
  }
  if(path==='/api/integrations/gmail/callback'&&request.method==='GET'){
    const state=await consumeOAuthState(env,{rawState:url.searchParams.get('state'),purpose:'gmail'});if(!state)return error('Gmail connection state is invalid or expired',400,cors);try{
      const member=await membership(env,state.workspace_id,state.user_id);if(member?.role!=='owner')throw new Error('Workspace owner permission is required');const token=await exchangeGoogleCode(url.searchParams.get('code'),googleConfig(env,'gmail'));if(!token.refreshToken)throw new Error('Google did not return an offline refresh token');const identity=await fetchGoogleIdentity(token.accessToken);const key=await importAesKey(env.OAUTH_TOKEN_ENCRYPTION_KEY);const encrypted=await encryptSecret(token.refreshToken,key);
      await env.DB.prepare(`INSERT INTO gmail_connections(workspace_id,user_id,google_email,encrypted_refresh_token,scopes,status,connected_at,updated_at,disconnected_at) VALUES(?,?,?,?,?,'connected',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT(workspace_id) DO UPDATE SET user_id=excluded.user_id,google_email=excluded.google_email,encrypted_refresh_token=excluded.encrypted_refresh_token,scopes=excluded.scopes,status='connected',connected_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,disconnected_at=NULL`).bind(state.workspace_id,state.user_id,identity.email,encrypted,token.scope||GMAIL_SCOPES.join(' ')).run();await audit(env,{workspaceId:state.workspace_id,userId:state.user_id,type:'gmail.connected',entityType:'gmail_connection',entityId:state.workspace_id,metadata:{google_email:identity.email}});return redirect(withResult(state.return_to,{gmail:'connected'}),cors);
    }catch(cause){return redirect(withResult(state.return_to,{gmail:'error',reason:String(cause?.message||'Gmail connection failed').slice(0,160)}),cors);}
  }
  if(path==='/api/integrations/gmail/send'&&request.method==='POST'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner','sales']);if(access.error)return error(access.error,access.status,cors);const body=await request.json().catch(()=>null);if(!body)return error('Send payload is required',400,cors);const key=String(request.headers.get('Idempotency-Key')||body.idempotency_key||'').trim();if(!validIdempotency(key))return error('A valid idempotency key is required',400,cors);
    const existing=await env.DB.prepare(`SELECT id,status,domain,recipient,subject,gmail_message_id,gmail_thread_id,sent_at FROM gmail_messages WHERE workspace_id=? AND idempotency_key=?`).bind(workspaceId,key).first();
    const recipient=normalizeEmail(body.recipient);const domain=normalizeDomain(body.domain);const projectId=String(body.customer_project_id||'').trim();if(projectId&&!(await projectAccess(env,workspaceId,projectId)))return error('Customer project not found',404,cors);if(!recipient||!domain)return error('Valid target domain and recipient are required',400,cors);if(await dailyEmailCount(env,workspaceId)>=20)return error('Daily email limit reached (20). Review activity before sending more.',429,cors,{code:'DAILY_EMAIL_LIMIT'});
    const crmCompany=await findCrmCompanyByDomain(env.DB,workspaceId,domain);if(crmCompany?.lifecycle_status==='suppressed')return error('Suppressed companies cannot receive normal outreach',409,cors,{code:'CRM_COMPANY_SUPPRESSED'});const crmSendActivityId=`gmail-send-${key}`.replace(/[^A-Za-z0-9._:-]/g,'-').slice(0,128);
    if(existing){if(existing.status==='sent'&&crmCompany){await appendCrmActivity(env.DB,{workspaceId,userId:access.user.id,role:access.member.role},{id:crmSendActivityId,companyId:crmCompany.id,type:'email.sent',channel:'gmail',direction:'outbound',subject:existing.subject,summary:`Email sent to ${existing.recipient}`,occurredAt:existing.sent_at,metadata:{gmail_message_id:existing.gmail_message_id,gmail_thread_id:existing.gmail_thread_id,recipient:existing.recipient,idempotency_key:key}});await setCrmPipelineStage(env.DB,{workspaceId,userId:access.user.id,role:access.member.role},crmCompany.id,'Contacted');}return json({message:existing,duplicate:true},200,cors);}const connection=await connectedGmail(env,workspaceId);if(!connection)return error('Gmail is not connected for this workspace',409,cors);let mime;try{mime=buildMimeMessage({from:connection.google_email,to:recipient,subject:body.subject,body:body.body});}catch(cause){return error(cause.message,400,cors);}
    const messageId=uuid();let reserve;try{reserve=await env.DB.prepare(`INSERT OR IGNORE INTO gmail_messages(id,workspace_id,customer_project_id,idempotency_key,domain,recipient,subject,sent_by,status) VALUES(?,?,?,?,?,?,?,?,'sending')`).bind(messageId,workspaceId,projectId||null,key,domain,recipient,String(body.subject||'').slice(0,500),access.user.id).run();}catch(cause){return error('Unable to reserve Gmail send',500,cors);}
    if(Number(reserve?.meta?.changes||0)<1){const duplicate=await env.DB.prepare(`SELECT id,status,domain,recipient,subject,gmail_message_id,gmail_thread_id,sent_at FROM gmail_messages WHERE workspace_id=? AND idempotency_key=?`).bind(workspaceId,key).first();return json({message:duplicate,duplicate:true},200,cors);}
    try{const accessToken=await gmailAccess(env,connection);const sent=await sendGmailMessage(accessToken.accessToken,mime);const sentAt=new Date().toISOString();await env.DB.prepare(`UPDATE gmail_messages SET gmail_message_id=?,gmail_thread_id=?,sent_at=?,status='sent' WHERE id=?`).bind(sent.id,sent.threadId,sentAt,messageId).run();await env.DB.prepare(`INSERT INTO email_activity_events(id,workspace_id,customer_project_id,user_id,kind,provider,provider_message_id,provider_thread_id,occurred_at,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uuid(),workspaceId,projectId||null,access.user.id,'sent','gmail',sent.id,sent.threadId,sentAt,JSON.stringify({recipient,domain,subject:String(body.subject||'').slice(0,500),idempotency_key:key})).run();await audit(env,{workspaceId,userId:access.user.id,type:'gmail.message_sent',entityType:'gmail_message',entityId:messageId,metadata:{domain,recipient,gmail_message_id:sent.id,gmail_thread_id:sent.threadId}});if(crmCompany){const crmContext={workspaceId,userId:access.user.id,role:access.member.role};await appendCrmActivity(env.DB,crmContext,{id:crmSendActivityId,companyId:crmCompany.id,type:'email.sent',channel:'gmail',direction:'outbound',subject:String(body.subject||'').slice(0,500),summary:`Email sent to ${recipient}`,occurredAt:sentAt,metadata:{gmail_message_id:sent.id,gmail_thread_id:sent.threadId,recipient,idempotency_key:key}});await setCrmPipelineStage(env.DB,crmContext,crmCompany.id,'Contacted');}return json({message:{id:messageId,status:'sent',domain,recipient,subject:String(body.subject||'').slice(0,500),gmail_message_id:sent.id,gmail_thread_id:sent.threadId,sent_at:sentAt},duplicate:false},201,cors);}catch(cause){await env.DB.prepare(`UPDATE gmail_messages SET status='failed' WHERE id=?`).bind(messageId).run();await audit(env,{workspaceId,userId:access.user.id,type:'gmail.message_failed',entityType:'gmail_message',entityId:messageId,metadata:{domain,recipient,error:String(cause?.message||'send failed').slice(0,160)}});return error(String(cause?.message||'Gmail send failed'),502,cors,{message_id:messageId});}
  }
  if(path==='/api/integrations/gmail/sync'&&request.method==='POST'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner','sales','researcher']);if(access.error)return error(access.error,access.status,cors);const connection=await connectedGmail(env,workspaceId);if(!connection)return error('Gmail is not connected for this workspace',409,cors);try{
      const token=await gmailAccess(env,connection);const {results=[]}=await env.DB.prepare(`SELECT id,domain,gmail_message_id,gmail_thread_id,sent_at FROM gmail_messages WHERE workspace_id=? AND status='sent' AND gmail_thread_id IS NOT NULL AND sent_at IS NOT NULL ORDER BY sent_at DESC LIMIT 50`).bind(workspaceId).all();const threadCache=new Map();const added=[];
      for(const sent of results){if(!threadCache.has(sent.gmail_thread_id))threadCache.set(sent.gmail_thread_id,await fetchGmailThread(token.accessToken,sent.gmail_thread_id));const replies=normalizeInboundReplies(threadCache.get(sent.gmail_thread_id),{sentMessageId:sent.gmail_message_id,sentAt:sent.sent_at,connectedEmail:connection.google_email});for(const reply of replies){const id=uuid();const inserted=await env.DB.prepare(`INSERT OR IGNORE INTO gmail_replies(id,workspace_id,domain,gmail_message_id,gmail_thread_id,sender_email,received_at,body_text,category) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,workspaceId,sent.domain,reply.gmailMessageId,reply.gmailThreadId,reply.senderEmail,reply.receivedAt,reply.bodyText.slice(0,20000),reply.category).run();if(Number(inserted?.meta?.changes||0)>0){added.push({id,domain:sent.domain,...reply});const crmCompany=await findCrmCompanyByDomain(env.DB,workspaceId,sent.domain);if(crmCompany){const crmContext={workspaceId,userId:access.user.id,role:access.member.role};await appendCrmActivity(env.DB,crmContext,{id:`gmail-reply-${reply.gmailMessageId}`.replace(/[^A-Za-z0-9._:-]/g,'-').slice(0,128),companyId:crmCompany.id,type:'email.reply_received',channel:'gmail',direction:'inbound',summary:`Reply from ${reply.senderEmail}`,occurredAt:reply.receivedAt,metadata:{gmail_message_id:reply.gmailMessageId,gmail_thread_id:reply.gmailThreadId,sender_email:reply.senderEmail,category:reply.category}});await setCrmPipelineStage(env.DB,crmContext,crmCompany.id,'Replied');}}}}
      await env.DB.prepare(`UPDATE gmail_connections SET updated_at=CURRENT_TIMESTAMP WHERE workspace_id=?`).bind(workspaceId).run();if(added.length)await audit(env,{workspaceId,userId:access.user.id,type:'gmail.replies_synced',entityType:'gmail_connection',entityId:workspaceId,metadata:{new_replies:added.length}});return json({replies:added,synced_threads:threadCache.size},200,cors);
    }catch(cause){return error(String(cause?.message||'Gmail sync failed'),502,cors);}
  }
  if(path==='/api/integrations/gmail/disconnect'&&request.method==='POST'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner']);if(access.error)return error(access.error,access.status,cors);const connection=await connectedGmail(env,workspaceId);if(connection?.encrypted_refresh_token&&env.OAUTH_TOKEN_ENCRYPTION_KEY){try{const key=await importAesKey(env.OAUTH_TOKEN_ENCRYPTION_KEY);const refresh=await decryptSecret(connection.encrypted_refresh_token,key);await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:refresh})});}catch{}}
    await env.DB.prepare(`UPDATE gmail_connections SET encrypted_refresh_token=NULL,status='disconnected',updated_at=CURRENT_TIMESTAMP,disconnected_at=CURRENT_TIMESTAMP WHERE workspace_id=?`).bind(workspaceId).run();await audit(env,{workspaceId,userId:access.user.id,type:'gmail.disconnected',entityType:'gmail_connection',entityId:workspaceId});return json({ok:true,connected:false},200,cors);
  }

  if(path==='/api/integrations/microsoft-mail/status'&&request.method==='GET'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId);if(access.error)return error(access.error,access.status,cors);const connection=await env.DB.prepare(`SELECT microsoft_email,scopes,status,connected_at,updated_at FROM microsoft_mail_connections WHERE workspace_id=?`).bind(workspaceId).first();return json({configured:configReady(env,['MICROSOFT_OAUTH_CLIENT_ID','MICROSOFT_OAUTH_CLIENT_SECRET','MICROSOFT_MAIL_OAUTH_REDIRECT_URI','OAUTH_TOKEN_ENCRYPTION_KEY']),connected:connection?.status==='connected',email:connection?.status==='connected'?connection.microsoft_email:'',scopes:connection?.status==='connected'?connection.scopes:'',connected_at:connection?.connected_at||null,role:access.member.role},200,cors);
  }
  if(path==='/api/integrations/microsoft-mail/start'&&request.method==='GET'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner']);if(access.error)return error(access.error,access.status,cors);if(!configReady(env,['MICROSOFT_OAUTH_CLIENT_ID','MICROSOFT_OAUTH_CLIENT_SECRET','MICROSOFT_MAIL_OAUTH_REDIRECT_URI','OAUTH_TOKEN_ENCRYPTION_KEY','CUSTOMER_APP_URL']))return error('Microsoft mail integration is not configured',503,cors);
    const returnTo=configuredCustomerReturn(env,url.searchParams.get('return_to'));if(!returnTo)return error('Invalid return URL',400,cors);const pkce=await createPkcePair();const state=await createOAuthState(env,{purpose:'gmail',userId:access.user.id,workspaceId,returnTo,codeVerifier:pkce.verifier});const location=buildMicrosoftAuthorizationUrl({...microsoftConfig(env,'mail'),state,scopes:MICROSOFT_MAIL_SCOPES,loginHint:access.user.email,prompt:'consent',codeChallenge:pkce.challenge});return redirect(location,cors);
  }
  if(path==='/api/integrations/microsoft-mail/callback'&&request.method==='GET'){
    const state=await consumeOAuthState(env,{rawState:url.searchParams.get('state'),purpose:'gmail'});if(!state)return error('Microsoft mail connection state is invalid or expired',400,cors);try{const member=await membership(env,state.workspace_id,state.user_id);if(member?.role!=='owner')throw new Error('Workspace owner permission is required');const token=await exchangeMicrosoftCode(url.searchParams.get('code'),{...microsoftConfig(env,'mail'),scopes:MICROSOFT_MAIL_SCOPES,codeVerifier:state.pkce_verifier||''});if(!token.refreshToken)throw new Error('Microsoft did not return an offline refresh token');const identity=await fetchMicrosoftIdentity(token.accessToken);const key=await importAesKey(env.OAUTH_TOKEN_ENCRYPTION_KEY);const encrypted=await encryptSecret(token.refreshToken,key);await env.DB.prepare(`INSERT INTO microsoft_mail_connections(workspace_id,user_id,microsoft_email,encrypted_refresh_token,scopes,status,connected_at,updated_at,disconnected_at) VALUES(?,?,?,?,?,'connected',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL) ON CONFLICT(workspace_id) DO UPDATE SET user_id=excluded.user_id,microsoft_email=excluded.microsoft_email,encrypted_refresh_token=excluded.encrypted_refresh_token,scopes=excluded.scopes,status='connected',connected_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,disconnected_at=NULL`).bind(state.workspace_id,state.user_id,identity.email,encrypted,token.scope||MICROSOFT_MAIL_SCOPES.join(' ')).run();await audit(env,{workspaceId:state.workspace_id,userId:state.user_id,type:'microsoft_mail.connected',entityType:'microsoft_mail_connection',entityId:state.workspace_id,metadata:{microsoft_email:identity.email}});return redirect(withResult(state.return_to,{microsoft_mail:'connected'}),cors);}catch(cause){return redirect(withResult(state.return_to,{microsoft_mail:'error',reason:String(cause?.message||'Microsoft mail connection failed').slice(0,160)}),cors);}
  }
  if(path==='/api/integrations/microsoft-mail/send'&&request.method==='POST'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner','sales']);if(access.error)return error(access.error,access.status,cors);const body=await request.json().catch(()=>null);if(!body)return error('Send payload is required',400,cors);const key=String(request.headers.get('Idempotency-Key')||body.idempotency_key||'').trim();if(!validIdempotency(key))return error('A valid idempotency key is required',400,cors);
    const existing=await env.DB.prepare(`SELECT id,status,provider_status,domain,recipient,subject,sent_at FROM microsoft_mail_messages WHERE workspace_id=? AND idempotency_key=?`).bind(workspaceId,key).first();if(existing)return json({message:{...existing,provider:'microsoft'},duplicate:true},200,cors);const recipient=normalizeEmail(body.recipient);const domain=normalizeDomain(body.domain);const projectId=String(body.customer_project_id||'').trim();if(projectId&&!(await projectAccess(env,workspaceId,projectId)))return error('Customer project not found',404,cors);if(!recipient||!domain)return error('Valid target domain and recipient are required',400,cors);if(await dailyEmailCount(env,workspaceId)>=20)return error('Daily email limit reached (20). Review activity before sending more.',429,cors,{code:'DAILY_EMAIL_LIMIT'});
    const crmCompany=await findCrmCompanyByDomain(env.DB,workspaceId,domain);if(crmCompany?.lifecycle_status==='suppressed')return error('Suppressed companies cannot receive normal outreach',409,cors,{code:'CRM_COMPANY_SUPPRESSED'});const crmSendActivityId=`microsoft-send-${key}`.replace(/[^A-Za-z0-9._:-]/g,'-').slice(0,128);const connection=await connectedMicrosoftMail(env,workspaceId);if(!connection)return error('Microsoft mail is not connected for this workspace',409,cors);const messageId=uuid();let reserve;try{reserve=await env.DB.prepare(`INSERT OR IGNORE INTO microsoft_mail_messages(id,workspace_id,customer_project_id,idempotency_key,domain,recipient,subject,sent_by,status) VALUES(?,?,?,?,?,?,?,?,'sending')`).bind(messageId,workspaceId,projectId||null,key,domain,recipient,String(body.subject||'').slice(0,500),access.user.id).run();}catch{return error('Unable to reserve Microsoft send',500,cors);}if(Number(reserve?.meta?.changes||0)<1){const duplicate=await env.DB.prepare(`SELECT id,status,provider_status,domain,recipient,subject,sent_at FROM microsoft_mail_messages WHERE workspace_id=? AND idempotency_key=?`).bind(workspaceId,key).first();return json({message:{...duplicate,provider:'microsoft'},duplicate:true},200,cors);}
    try{const accessToken=await microsoftMailAccess(env,connection);await sendMicrosoftMessage(accessToken.accessToken,{to:recipient,subject:body.subject,body:body.body});const sentAt=new Date().toISOString();await env.DB.prepare(`UPDATE microsoft_mail_messages SET sent_at=?,status='sent',provider_status='accepted' WHERE id=?`).bind(sentAt,messageId).run();await env.DB.prepare(`INSERT INTO email_activity_events(id,workspace_id,customer_project_id,user_id,kind,provider,provider_message_id,provider_thread_id,occurred_at,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(uuid(),workspaceId,projectId||null,access.user.id,'sent','microsoft',messageId,null,sentAt,JSON.stringify({recipient,domain,subject:String(body.subject||'').slice(0,500),idempotency_key:key,provider_status:'accepted'})).run();await audit(env,{workspaceId,userId:access.user.id,type:'microsoft_mail.message_accepted',entityType:'microsoft_mail_message',entityId:messageId,metadata:{domain,recipient,provider_status:'accepted'}});if(crmCompany){const crmContext={workspaceId,userId:access.user.id,role:access.member.role};await appendCrmActivity(env.DB,crmContext,{id:crmSendActivityId,companyId:crmCompany.id,type:'email.sent',channel:'microsoft',direction:'outbound',subject:String(body.subject||'').slice(0,500),summary:`Email accepted by Microsoft for ${recipient}`,occurredAt:sentAt,metadata:{provider_message_id:messageId,provider_status:'accepted',recipient,idempotency_key:key}});await setCrmPipelineStage(env.DB,crmContext,crmCompany.id,'Contacted');}return json({message:{id:messageId,status:'sent',provider:'microsoft',provider_status:'accepted',domain,recipient,subject:String(body.subject||'').slice(0,500),sent_at:sentAt},duplicate:false},201,cors);}catch(cause){await env.DB.prepare(`UPDATE microsoft_mail_messages SET status='failed',provider_status='failed' WHERE id=?`).bind(messageId).run();await audit(env,{workspaceId,userId:access.user.id,type:'microsoft_mail.message_failed',entityType:'microsoft_mail_message',entityId:messageId,metadata:{domain,recipient,error:String(cause?.message||'send failed').slice(0,160)}});return error(String(cause?.message||'Microsoft send failed'),502,cors,{message_id:messageId});}
  }
  if(path==='/api/integrations/microsoft-mail/disconnect'&&request.method==='POST'){
    const workspaceId=url.searchParams.get('workspace_id')||'';const access=await requireMember(request,env,workspaceId,['owner']);if(access.error)return error(access.error,access.status,cors);await env.DB.prepare(`UPDATE microsoft_mail_connections SET encrypted_refresh_token=NULL,status='disconnected',updated_at=CURRENT_TIMESTAMP,disconnected_at=CURRENT_TIMESTAMP WHERE workspace_id=?`).bind(workspaceId).run();await audit(env,{workspaceId,userId:access.user.id,type:'microsoft_mail.disconnected',entityType:'microsoft_mail_connection',entityId:workspaceId});return json({ok:true,connected:false},200,cors);
  }

  return error('Not found',404,cors);
}
