let deps=null;
let drawer=null;
let conversationId='';

function ensureCss(){if(document.querySelector('link[data-leadintel-asset="copilot-css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='./copilot.css?v=20260908-copilot-v1';link.dataset.leadintelAsset='copilot-css';document.head.appendChild(link);}
function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=String(text);return el;}
function safeUrl(value){try{const url=new URL(String(value||''));return /^https?:$/.test(url.protocol)?url.toString():'';}catch{return '';}}
function closeCopilot(){if(!drawer)return;drawer.hidden=true;document.getElementById('leadintel-copilot-entry')?.focus();}
function onKeydown(event){if(event.key==='Escape'&&drawer&&!drawer.hidden)closeCopilot();}
function badge(count){const target=document.querySelector('#leadintel-copilot-entry [data-copilot-badge]');if(!target)return;const n=Math.max(0,Number(count)||0);target.textContent=n?String(n):'';target.hidden=!n;}
function clear(el){while(el.firstChild)el.removeChild(el.firstChild);}
function severityLabel(value){const v=String(value||'').toLowerCase();if(v==='important')return 'Important';if(v==='improve')return 'Improve';return 'Info';}
function formatPreview(value){if(value===null||value===undefined)return 'None';if(typeof value==='string')return value;try{return JSON.stringify(value,null,2);}catch{return String(value);}}

function ensureDrawer(){
  if(drawer)return drawer;ensureCss();drawer=node('aside','leadintel-copilot-drawer');drawer.id='leadintel-copilot-drawer';drawer.setAttribute('role','dialog');drawer.setAttribute('aria-modal','false');drawer.setAttribute('aria-label','Ask LeadIntel');drawer.hidden=true;
  const header=node('header','copilot-header');const titleWrap=node('div');titleWrap.append(node('strong','copilot-title','Ask LeadIntel ✦'),node('span','copilot-subtitle','Workspace Copilot'));
  const close=node('button','copilot-close','×');close.type='button';close.setAttribute('aria-label','Close Copilot');close.addEventListener('click',closeCopilot);header.append(titleWrap,close);
  const diagnostics=node('section','copilot-diagnostics');diagnostics.dataset.copilotDiagnostics='';const messages=node('section','copilot-messages');messages.dataset.copilotMessages='';const proposals=node('section','copilot-proposals');proposals.dataset.copilotProposals='';const prompts=node('section','copilot-prompts');prompts.dataset.copilotPrompts='';
  const form=node('form','copilot-composer');const input=document.createElement('textarea');input.rows=3;input.maxLength=8000;input.placeholder='Ask about this step, your strategy, leads, signals or setup…';input.setAttribute('aria-label','Message Ask LeadIntel');const send=node('button','copilot-send','Send');send.type='submit';form.append(input,send);
  const status=node('div','copilot-status');status.dataset.copilotStatus='';status.setAttribute('aria-live','polite');form.addEventListener('submit',async event=>{event.preventDefault();const message=input.value.trim();if(!message)return;input.value='';await sendMessage(message);});
  drawer.append(header,diagnostics,messages,proposals,prompts,status,form);document.documentElement.appendChild(drawer);document.addEventListener('keydown',onKeydown);return drawer;
}

function renderDiagnostics(items=[],unreadImportant=0){const host=drawer.querySelector('[data-copilot-diagnostics]');clear(host);badge(unreadImportant);if(!items.length)return;const heading=node('h3','','Workspace checks');host.appendChild(heading);for(const item of items.slice(0,8)){const card=node('article',`copilot-diagnostic is-${String(item.severity||'info').toLowerCase()}`);card.append(node('span','copilot-severity',severityLabel(item.severity)),node('strong','',item.title||item.message||'Workspace guidance'));if(item.message&&item.message!==item.title)card.append(node('p','',item.message));host.appendChild(card);}}
function renderPrompts(){const host=drawer.querySelector('[data-copilot-prompts]');clear(host);const screen=deps.context.currentCopilotScreenContext();for(const prompt of deps.context.contextualPromptSuggestions(screen.step)){const button=node('button','copilot-prompt',prompt);button.type='button';button.addEventListener('click',()=>void sendMessage(prompt));host.appendChild(button);}}
function renderSources(host,sources=[]){const safe=(Array.isArray(sources)?sources:[]).filter(item=>safeUrl(item?.url)).slice(0,8);if(!safe.length)return;const wrap=node('div','copilot-sources');wrap.append(node('strong','','Sources'));for(const item of safe){const link=node('a','copilot-source',item.title||item.url);link.href=safeUrl(item.url);link.target='_blank';link.rel='noopener noreferrer';wrap.appendChild(link);}host.appendChild(wrap);}
function appendMessage(role,text,sources=[]){const host=drawer.querySelector('[data-copilot-messages]');const card=node('article',`copilot-message is-${role}`);card.append(node('span','copilot-message-role',role==='user'?'You':'LeadIntel'),node('p','copilot-message-text',text));renderSources(card,sources);host.appendChild(card);host.scrollTop=host.scrollHeight;}
function setStatus(text){drawer.querySelector('[data-copilot-status]').textContent=String(text||'');}

function proposalCard(proposal){const card=node('article','copilot-proposal');card.dataset.proposalId=proposal.id||'';card.append(node('span','copilot-severity','Proposed change'),node('strong','',String(proposal.action_type||'Change').replaceAll('.',' · ')));
  const preview=node('div','copilot-preview');const before=node('div','copilot-preview-side');before.append(node('b','','Before'),node('pre','',formatPreview(proposal.preview?.before)));const after=node('div','copilot-preview-side');after.append(node('b','','After'),node('pre','',formatPreview(proposal.preview?.after)));preview.append(before,after);card.appendChild(preview);
  const actions=node('div','copilot-proposal-actions');const reject=node('button','copilot-reject','Reject');reject.type='button';const confirm=node('button','copilot-confirm','Confirm change');confirm.type='button';
  reject.addEventListener('click',async()=>{reject.disabled=true;confirm.disabled=true;try{await deps.api.rejectCopilotAction(proposal.id);card.remove();}catch(cause){setStatus(cause?.message||'Unable to reject change');reject.disabled=false;confirm.disabled=false;}});
  confirm.addEventListener('click',async()=>{const key=proposal.idempotency_key||`copilot-${crypto.randomUUID()}`;reject.disabled=true;confirm.disabled=true;setStatus('Applying confirmed change…');try{await deps.api.confirmCopilotAction(proposal.id,key);window.dispatchEvent(new CustomEvent('leadintel:copilot-action-confirmed',{detail:{proposal_id:proposal.id,action_type:proposal.action_type}}));setStatus('Change applied. Refreshing authoritative workspace…');location.reload();}catch(cause){if(Number(cause?.status)===409||/conflict/i.test(String(cause?.message||'')))setStatus('Workspace changed since this suggestion. Refresh and ask LeadIntel to propose the change again.');else setStatus(cause?.message||'Unable to apply change');reject.disabled=false;confirm.disabled=false;}});actions.append(reject,confirm);card.appendChild(actions);return card;}
function renderProposals(items=[]){const host=drawer.querySelector('[data-copilot-proposals]');clear(host);for(const proposal of (Array.isArray(items)?items:[]).slice(0,5))host.appendChild(proposalCard(proposal));}

async function sendMessage(message){appendMessage('user',message);setStatus('Thinking…');const screen=deps.context.currentCopilotScreenContext();try{const result=await deps.api.sendCopilotMessage({...(conversationId?{conversation_id:conversationId}:{}),message,screen});if(!result){setStatus('Sign in to use Ask LeadIntel.');return;}conversationId=String(result.conversation_id||conversationId);appendMessage('assistant',result.answer||'No answer was returned.',result.sources||[]);renderProposals(result.action_proposals||[]);renderDiagnostics(result.diagnostics||[],(result.diagnostics||[]).filter(item=>String(item.severity).toLowerCase()==='important').length);setStatus(result.research_used?'Answer includes fresh external research.':'');}catch(cause){setStatus(cause?.name==='AbortError'?'Ask LeadIntel timed out. Please try again.':cause?.message||'Ask LeadIntel is temporarily unavailable.');}}

export async function openCopilot(options={}){deps=options;const panel=ensureDrawer();panel.hidden=false;renderPrompts();setStatus('Loading workspace guidance…');try{const boot=await deps.api.bootstrapCopilot();if(!boot){setStatus('Sign in to use Ask LeadIntel.');return panel;}conversationId=String(boot.latestConversation?.id||'');renderDiagnostics(boot.diagnostics||[],boot.unreadImportant||0);setStatus(boot.ai?.configured?'':'Connect an AI provider in settings to use Copilot reasoning.');}catch(cause){setStatus(cause?.message||'Copilot guidance is temporarily unavailable.');}panel.querySelector('textarea')?.focus();return panel;}

export {safeUrl,closeCopilot};
if(typeof window!=='undefined')window.LeadIntelCopilotUi={openCopilot,closeCopilot};
