(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.LeadIntelCrm=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const STAGES=['Discovered','Qualified','Ready for Outreach','Contacted','Replied','Meeting','Proposal','Won','Lost'];
  const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
  function canonicalDomain(value){const raw=clean(value);if(!raw||/\s/.test(raw))return '';try{const url=new URL(/^[a-z][a-z0-9+.-]*:\/\//i.test(raw)?raw:`https://${raw}`);return String(url.hostname||'').toLowerCase().replace(/^www\./,'').replace(/\.$/,'');}catch{return '';}}
  function normalizeEmail(value){const email=clean(value).toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:'';}
  function normalizeCrmStage(value){const stage=clean(value)==='Contact Found'?'Qualified':clean(value);return STAGES.includes(stage)?stage:null;}
  function mapContacts(people=[]){return (Array.isArray(people)?people:[]).slice(0,20).map(person=>({external_person_id:clean(person?.external_person_id||person?.id)||undefined,name:clean(person?.name)||undefined,title:clean(person?.title)||undefined,work_email:normalizeEmail(person?.work_email||person?.email)||undefined,email_status:clean(person?.email_status)||undefined,linkedin_url:clean(person?.linkedin_url||person?.linkedin)||undefined,source:clean(person?.source)||'apollo'})).filter(person=>person.external_person_id||person.work_email||person.name||person.title);}
  function mapDiscoveryCandidateToCrm(candidate={},options={}){const domain=canonicalDomain(candidate.domain||candidate.website);const score=candidate.score&&typeof candidate.score==='object'?candidate.score:{};const stage=normalizeCrmStage(options.pipelineStage??candidate.pipeline_stage??candidate.stage);return {company:{company_name:clean(candidate.company||candidate.company_name||candidate.name)||domain,domain,website:clean(candidate.website)||(domain?`https://${domain}/`:''),country:clean(candidate.country)||undefined,industry:clean(candidate.industry)||undefined,opportunity_score:Number.isFinite(Number(score.total??candidate.opportunity_score))?Math.max(0,Math.min(100,Math.round(Number(score.total??candidate.opportunity_score)))):undefined,confidence:clean(candidate.confidence)||undefined,source:clean(candidate.source)||'discovery',...(stage?{pipeline_stage:stage}:{})},intelligence:{matched_signals:(Array.isArray(candidate.matchedSignals)?candidate.matchedSignals:Array.isArray(candidate.matched_signals)?candidate.matched_signals:[]).slice(0,20),evidence:(Array.isArray(candidate.evidence)?candidate.evidence:[]).slice(0,12),opportunity_hypothesis:clean(candidate.opportunity_hypothesis||candidate.hypothesis)||undefined,score_breakdown:score,research_snapshot:{market:clean(candidate.market)||undefined}},contacts:mapContacts(candidate.people||candidate.contacts)};}
  function mapLocalPipelineItemToCrm(item={}){return mapDiscoveryCandidateToCrm(item,{pipelineStage:normalizeCrmStage(item.stage)||'Discovered'});}
  function filterCrmCompanies(companies=[],filters={}){const q=clean(filters.q).toLowerCase(),lifecycle=clean(filters.lifecycle),pipeline=clean(filters.pipeline);return (Array.isArray(companies)?companies:[]).filter(company=>{if(lifecycle&&lifecycle!=='all'&&company.lifecycle_status!==lifecycle)return false;if(pipeline==='active'&&!company.pipeline_stage)return false;if(pipeline&&pipeline!=='active'&&company.pipeline_stage!==pipeline)return false;if(q){const hay=[company.company_name,company.normalized_domain,company.contact_search].map(clean).join(' ').toLowerCase();if(!hay.includes(q))return false;}return true;});}
  function isSuppressed(company){return clean(company?.lifecycle_status)==='suppressed';}
  function lifecycleLabel(company){const value=clean(company?.lifecycle_status)||'prospect';return value.charAt(0).toUpperCase()+value.slice(1);}
  return {STAGES,canonicalDomain,normalizeEmail,normalizeCrmStage,mapContacts,mapDiscoveryCandidateToCrm,mapLocalPipelineItemToCrm,filterCrmCompanies,isSuppressed,lifecycleLabel};
});
