(function(root){
  'use strict';
  const VERSION='20260924-crm-activity-pages-v1';
  const state={open:false,view:'all',q:'',companies:[],selectedId:'',detail:null,loading:false,error:'',activityCursor:null,activityLoading:false,activityError:''};
  const q=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const bridge=()=>root.LeadIntelServerBridge;
  function toast(message){const el=q('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3000);}
  function injectCss(){if(document.querySelector('link[data-leadintel-asset="crm-css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=`crm.css?v=${VERSION}`;link.dataset.leadintelAsset='crm-css';document.head.appendChild(link);}
  function inject(){injectCss();const actions=document.querySelector('.top-actions');if(actions&&!q('open-crm'))actions.insertAdjacentHTML('afterbegin','<button class="ghost-btn crm-open-btn" id="open-crm" type="button">CRM</button>');if(q('crm-workspace'))return;document.body.insertAdjacentHTML('beforeend',`<div class="crm-workspace" id="crm-workspace" hidden aria-hidden="true"><div class="crm-backdrop" data-crm-close></div><section class="crm-shell" role="dialog" aria-modal="true" aria-labelledby="crm-title"><header class="crm-header"><div><span class="eyebrow">Master CRM</span><h2 id="crm-title">Commercial memory</h2><p>Companies, contacts, intelligence and activity history that survive the active pipeline.</p></div><button class="crm-close" type="button" data-crm-close aria-label="Close CRM">×</button></header><div class="crm-toolbar"><div class="crm-tabs" role="tablist"><button class="active" type="button" data-crm-view="all">All Companies</button><button type="button" data-crm-view="pipeline">Active Pipeline</button><button type="button" data-crm-view="customer">Customers</button><button type="button" data-crm-view="archived">Archived</button><button type="button" data-crm-view="suppressed">Suppressed</button></div><label class="crm-search"><span>Search</span><input id="crm-search" type="search" placeholder="Company, domain, contact or email"></label></div><div class="crm-status" id="crm-status">Sign in to load Master CRM.</div><div class="crm-body"><div class="crm-list" id="crm-company-list"></div><aside class="crm-detail" id="crm-company-detail"><div class="crm-empty-detail">Select a company to inspect intelligence, contacts and activity.</div></aside></div></section></div>`);bind();}
  function role(){return bridge()?.workspace?.role||'';}
  function filters(){if(state.view==='pipeline')return {q:state.q,pipeline_stage:'active',limit:100};if(['customer','archived','suppressed'].includes(state.view))return {q:state.q,lifecycle:state.view,limit:100};return {q:state.q,limit:100};}
  function topSignal(company){try{const rows=JSON.parse(company.matched_signals_json||'[]');return rows?.[0]?.name||'—';}catch{return '—';}}
  function formatDate(value){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleDateString();}
  function renderList(){const target=q('crm-company-list');if(!target)return;if(state.loading){target.innerHTML='<div class="crm-empty">Loading CRM…</div>';return;}if(state.error){target.innerHTML=`<div class="crm-empty crm-error">${esc(state.error)}</div>`;return;}if(!state.companies.length){target.innerHTML='<div class="crm-empty">No companies match this view yet.</div>';return;}target.innerHTML=`<div class="crm-table"><div class="crm-row crm-row-head"><span>Company</span><span>Lifecycle</span><span>Pipeline</span><span>Score</span><span>Signal</span><span>Contacts</span><span>Last activity</span></div>${state.companies.map(company=>`<button class="crm-row ${company.id===state.selectedId?'selected':''}" type="button" data-crm-company-id="${esc(company.id)}"><span class="crm-company-cell"><strong>${esc(company.company_name)}</strong><small>${esc(company.normalized_domain||company.website||'No domain')}</small></span><span><i class="crm-pill lifecycle-${esc(company.lifecycle_status)}">${esc(root.LeadIntelCrm?.lifecycleLabel(company)||company.lifecycle_status)}</i></span><span>${esc(company.pipeline_stage||'—')}</span><span>${Number(company.opportunity_score)||0}</span><span>${esc(topSignal(company))}</span><span>${Number(company.contact_count)||0}</span><span>${esc(formatDate(company.last_activity_at||company.updated_at))}</span></button>`) .join('')}</div>${nextCursor?'<button type="button" class="secondary-btn" data-crm-load-more>Load more companies</button>':''}`;}
  function intelligenceHtml(intelligence){if(!intelligence)return '<div class="crm-detail-empty">No durable intelligence snapshot yet.</div>';const signals=Array.isArray(intelligence.matched_signals)?intelligence.matched_signals:[];const evidence=Array.isArray(intelligence.evidence)?intelligence.evidence:[];return `<div class="crm-intel-block"><p>${esc(intelligence.opportunity_hypothesis||'No opportunity hypothesis saved.')}</p><div class="crm-chip-list">${signals.length?signals.slice(0,8).map(item=>`<span>${esc(item.name||item.id||'Signal')}</span>`).join(''):'<span>No matched signals</span>'}</div><small>${evidence.length} evidence source${evidence.length===1?'':'s'} · ${esc(intelligence.confidence||'Unrated')} confidence</small></div>`;}
  function contactsHtml(contacts=[]){return contacts.length?contacts.map(contact=>`<div class="crm-contact"><strong>${esc(contact.name||'Unnamed contact')}</strong><span>${esc(contact.title||'Role not set')}</span><small>${esc(contact.work_email||'No verified work email')}</small><small>${contact.phone_number?`Verified phone · ${esc(contact.phone_number)}`:'No verified phone'}</small>${contact.linkedin_url?`<a class="crm-contact-linkedin" href="${esc(contact.linkedin_url)}" target="_blank" rel="noopener noreferrer">View LinkedIn profile ↗</a>`:''}</div>`).join(''):'<div class="crm-detail-empty">No contacts saved.</div>';}
  function activitiesHtml(activities=[],options={}){const rows=(Array.isArray(activities)?activities:[]).map(item=>`<div class="crm-activity"><span>${esc(item.activity_type)}</span><strong>${esc(item.summary||item.subject||item.activity_type)}</strong><small>${esc(formatDate(item.occurred_at))}</small></div>`).join('');const error=options.error?`<p class="crm-detail-empty crm-activity-error">${esc(options.error)}</p>`:'';const button=options.hasMore||options.error?`<button class="secondary-btn crm-load-activity" type="button" data-crm-load-activity ${options.loading?'disabled':''}>${options.loading?'Loading activity…':options.error?'Retry activity history':'Load older activity'}</button>`:'';return `${rows||(!error?'<div class="crm-detail-empty">No CRM activity yet.</div>':'')}${error}${button}`;}
  function renderDetail(){const target=q('crm-company-detail');if(!target)return;const detail=state.detail;if(!detail?.company){target.innerHTML='<div class="crm-empty-detail">Select a company to inspect intelligence, contacts and activity.</div>';return;}const c=detail.company;const suppressed=c.lifecycle_status==='suppressed',archived=c.lifecycle_status==='archived',owner=role()==='owner';const primaryActions=c.pipeline_stage?`<button type="button" data-crm-action="remove-pipeline">Remove from Pipeline</button>`:`<button type="button" data-crm-action="add-pipeline" ${suppressed||archived?'disabled':''}>Add to Pipeline</button>`;target.innerHTML=`<div class="crm-detail-head"><div><span class="eyebrow">Company record</span><h3>${esc(c.company_name)}</h3><a href="${esc(c.website||'#')}" target="_blank" rel="noopener">${esc(c.normalized_domain||c.website||'Website unavailable')}</a></div><button type="button" class="crm-detail-close" data-crm-detail-close>×</button></div><div class="crm-detail-meta"><span>${esc(root.LeadIntelCrm?.lifecycleLabel(c)||c.lifecycle_status)}</span><span>${esc(c.pipeline_stage||'Not in pipeline')}</span><span>${Number(c.opportunity_score)||0}/100</span><span>${esc(c.confidence||'Unrated')}</span></div><div class="crm-detail-actions">${primaryActions}<button type="button" data-crm-action="mark-customer">Mark Customer</button><button type="button" data-crm-action="archive" ${archived?'disabled':''}>Archive</button><button type="button" data-crm-action="suppress" ${suppressed?'disabled':''}>Suppress</button><button type="button" data-crm-action="restore" ${!suppressed&&!archived?'disabled':''}>Restore</button>${owner?'<button class="danger" type="button" data-crm-action="delete-permanently">Delete permanently</button>':''}</div><section><h4>Intelligence</h4>${intelligenceHtml(detail.intelligence)}</section><section><h4>Contacts</h4>${contactsHtml(detail.contacts)}</section><section><h4>Activity</h4>${activitiesHtml(detail.activities,{hasMore:Boolean(state.activityCursor),loading:state.activityLoading,error:state.activityError})}</section>`;}
  function renderStatus(){const el=q('crm-status');if(!el)return;const b=bridge();el.textContent=!b?.session?.authenticated?'Sign in with Google to use durable Master CRM.':state.error?state.error:`${state.companies.length} compan${state.companies.length===1?'y':'ies'} · ${state.view==='all'?'All Companies':state.view==='pipeline'?'Active Pipeline':root.LeadIntelCrm?.lifecycleLabel({lifecycle_status:state.view})||state.view}`;}
  function render(){q('crm-workspace')?.querySelectorAll('[data-crm-view]').forEach(button=>button.classList.toggle('active',button.dataset.crmView===state.view));renderStatus();renderList();renderDetail();}
  let listRequest=0,detailRequest=0,activityRequest=0,nextCursor=null;
  async function loadCompanies(append=false){
    append=append===true;
    if(append&&(state.loading||!nextCursor))return;
    const request=++listRequest,b=bridge(),workspaceId=b?.workspace?.id,query=filters();
    state.error='';
    if(!b?.session?.authenticated||!b.workspace){state.companies=[];state.detail=null;state.selectedId='';state.loading=false;nextCursor=null;render();return;}
    if(append)query.cursor=nextCursor;else nextCursor=null;
    state.loading=true;renderList();
    try{
      const result=await b.listCrmCompanies(query);
      if(request!==listRequest||workspaceId!==bridge()?.workspace?.id)return;
      if(!result?.ok)throw Error(result?.error||'CRM unavailable');
      const rows=Array.isArray(result.companies)?result.companies:[];
      state.companies=append?Array.from(new Map([...state.companies,...rows].map(row=>[row.id,row])).values()):rows;
      nextCursor=result.next_cursor&&result.next_cursor!==query.cursor?result.next_cursor:null;
      if(!append&&state.selectedId&&!state.companies.some(item=>item.id===state.selectedId)&&state.view!=='all'){state.selectedId='';state.detail=null;}
    }catch(error){if(request===listRequest&&workspaceId===bridge()?.workspace?.id)state.error='Unable to load CRM. Please retry.';}
    finally{if(request===listRequest){state.loading=false;render();}}
  }
  async function openCompany(id){
    const request=++detailRequest,workspaceId=bridge()?.workspace?.id,b=bridge();
    ++activityRequest;state.selectedId=id;state.detail=null;state.activityCursor=null;state.activityLoading=false;state.activityError='';renderList();renderDetail();
    try{
      const result=await b?.getCrmCompany(id);
      if(request!==detailRequest||state.selectedId!==id||workspaceId!==bridge()?.workspace?.id)return;
      if(!result?.ok){toast(result?.error||'Unable to load company');return;}
      let activityPage=Object.prototype.hasOwnProperty.call(result,'activity_next_cursor')?{ok:true,activities:result.activities,next_cursor:result.activity_next_cursor}:null;
      if(!activityPage&&typeof b?.getCrmActivities==='function'){try{activityPage=await b.getCrmActivities(id,{limit:40});}catch{activityPage={ok:false};}}
      if(request!==detailRequest||state.selectedId!==id||workspaceId!==bridge()?.workspace?.id)return;
      const fallbackLimit=activityPage?40:100;
      const activities=activityPage?.ok&&Array.isArray(activityPage.activities)?activityPage.activities:Array.isArray(result.activities)?result.activities.slice(0,fallbackLimit):[];
      state.detail={...result,activities};state.activityCursor=activityPage?.ok?activityPage.next_cursor||null:null;state.activityError=activityPage?.ok||!activityPage?'':'Activity history could not load. Please retry.';renderDetail();
    }catch(error){if(request===detailRequest)toast('Unable to load company. Please retry.');}
  }
  async function loadMoreActivities(){const id=state.detail?.company?.id,b=bridge();if(!id||state.activityLoading||(!state.activityCursor&&!state.activityError)||typeof b?.getCrmActivities!=='function')return;const request=++activityRequest,workspaceId=b?.workspace?.id,cursor=state.activityCursor||'';state.activityLoading=true;state.activityError='';renderDetail();try{const result=await b.getCrmActivities(id,{limit:40,cursor});if(request!==activityRequest||state.selectedId!==id||workspaceId!==bridge()?.workspace?.id)return;if(!result?.ok)throw Error(result?.error||'Activity history unavailable');const existing=state.detail?.activities||[],known=new Set(existing.map(item=>item.id));state.detail.activities=[...existing,...(Array.isArray(result.activities)?result.activities:[]).filter(item=>!known.has(item.id))];state.activityCursor=result.next_cursor||null;}catch(error){if(request===activityRequest&&state.selectedId===id)state.activityError='Activity history could not load. Please retry.';}finally{if(request===activityRequest){state.activityLoading=false;renderDetail();}}}
  function changed(company){root.dispatchEvent(new CustomEvent('leadintel:crm-changed',{detail:{company}}));}
  async function action(name){const b=bridge(),id=state.detail?.company?.id;if(!b||!id)return;let result=null;if(name==='add-pipeline')result=await b.addCrmToPipeline(id,'Discovered');if(name==='remove-pipeline')result=await b.removeCrmFromPipeline(id);if(name==='mark-customer')result=await b.markCrmCustomer(id);if(name==='archive')result=await b.archiveCrmCompany(id);if(name==='suppress'){if(!confirm('Suppress this company? It will be blocked from normal rediscovery and outreach until restored.'))return;result=await b.suppressCrmCompany(id);}if(name==='restore')result=await b.restoreCrmCompany(id);if(name==='delete-permanently'){if(!confirm('Permanently delete this CRM company and its CRM history? This cannot be undone.'))return;result=await b.deleteCrmCompany(id);if(result?.ok){state.selectedId='';state.detail=null;toast('CRM company permanently deleted');await loadCompanies();changed(null);return;}}if(!result?.ok){toast(result?.error||'CRM action failed');return;}toast('CRM updated');changed(result.company||state.detail?.company);await loadCompanies();await openCompany(id);}
  function open(){state.open=true;const el=q('crm-workspace');if(el){el.hidden=false;el.setAttribute('aria-hidden','false');}document.body.classList.add('crm-open');loadCompanies();}
  function close(){state.open=false;const el=q('crm-workspace');if(el){el.hidden=true;el.setAttribute('aria-hidden','true');}document.body.classList.remove('crm-open');}
  let searchTimer=null;
  function bind(){q('open-crm')?.addEventListener('click',open);q('crm-workspace')?.addEventListener('click',event=>{if(event.target.closest('[data-crm-load-more]')){loadCompanies(true);return;}if(event.target.closest('[data-crm-load-activity]')){loadMoreActivities();return;}const closeTarget=event.target.closest('[data-crm-close]');if(closeTarget){close();return;}const view=event.target.closest('[data-crm-view]');if(view){state.view=view.dataset.crmView;loadCompanies();return;}const row=event.target.closest('[data-crm-company-id]');if(row){openCompany(row.dataset.crmCompanyId);return;}if(event.target.closest('[data-crm-detail-close]')){++activityRequest;state.selectedId='';state.detail=null;state.activityCursor=null;state.activityError='';renderDetail();return;}const actionButton=event.target.closest('[data-crm-action]');if(actionButton&&!actionButton.disabled)action(actionButton.dataset.crmAction);});q('crm-search')?.addEventListener('input',event=>{state.q=event.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(loadCompanies,250);});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&state.open)close();});root.addEventListener('leadintel:server-ready',()=>{if(state.open)loadCompanies();});root.addEventListener('leadintel:crm-migrated',()=>{if(state.open)loadCompanies();});}
  function init(){inject();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
