(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.LeadIntelEvidencePolicy=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
  const SUPPORT_SUBDOMAINS=new Set(['www','media','investors','investor','newsroom','news','press','ir','en','sv','se','fi','de','fr','lv','lt','ee','pl','es','it']);
  const SHARED_HOSTS=new Set(['github.io','wordpress.com','webflow.io','wixsite.com','notion.site','blogspot.com','azurewebsites.net','pages.dev','vercel.app']);
  function host(value){try{const raw=clean(value);if(!raw||/\s/.test(raw))return '';const url=new URL(/^[a-z][a-z0-9+.-]*:\/\//i.test(raw)?raw:`https://${raw}`);return ['http:','https:'].includes(url.protocol)?url.hostname.toLowerCase().replace(/\.$/,'').replace(/^www\./,''):'';}catch{return '';}}
  function companyDomain(value){let domain=host(value),parts=domain.split('.');while(parts.length>2&&SUPPORT_SUBDOMAINS.has(parts[0])&&![...SHARED_HOSTS].some(shared=>domain===shared||domain.endsWith('.'+shared))){parts.shift();domain=parts.join('.');}return domain;}
  function firstParty(url,domain){const actual=host(url),official=companyDomain(domain);return Boolean(actual&&official&&(actual===official||actual.endsWith(`.${official}`)));}
  const MONTHS=['january january jan januari janvāris janvāra januar janvier enero gennaio','february feb februari februāris februāra februar février febrero febbraio','march mar mars marts marta märz marzo','april apr avril aprīlis aprīļa abril aprile','may maj maijs maija mai mayo maggio','june jun juni jūnijs jūnija juin junio giugno','july jul juli jūlijs jūlija juillet julio luglio','august aug augusts augusta août agosto','september sep sept septembris septembra septembre septiembre settembre','october oct oktober oktobris oktobra octobre octubre ottobre','november nov novembris novembra novembre noviembre','december dec december decembris decembra dezember décembre diciembre dicembre'];
  const monthMap=new Map(MONTHS.flatMap((names,index)=>names.split(' ').map(name=>[name,index+1])));
  const monthPattern=[...monthMap.keys()].sort((a,b)=>b.length-a.length).join('|');
  function calendarDate(year,month,day){const y=Number(year),m=Number(month),d=Number(day);if(y<1900||y>2100||m<1||m>12||d<1||d>31)return '';const date=new Date(Date.UTC(y,m-1,d));return date.getUTCFullYear()===y&&date.getUTCMonth()===m-1&&date.getUTCDate()===d?date.toISOString().slice(0,10):'';}
  function parseDate(value){
    if(Array.isArray(value)){for(const item of value){const date=parseDate(item);if(date)return date;}return '';}
    const text=clean(value);if(!text)return '';
    let match=text.match(/\b(20\d{2}|19\d{2})[-/.](\d{1,2})[-/.](\d{1,2})(?=T|\b)/);if(match)return calendarDate(match[1],match[2],match[3]);
    match=text.match(new RegExp(`\\b(${monthPattern})[ .]+(\\d{1,2})[,]?[ .]+((?:19|20)\\d{2})\\b`,'i'));if(match)return calendarDate(match[3],monthMap.get(match[1].toLowerCase()),match[2]);
    match=text.match(new RegExp(`\\b(\\d{1,2})[ .]+(${monthPattern})[,]?[ .]+((?:19|20)\\d{2})\\b`,'i'));if(match)return calendarDate(match[3],monthMap.get(match[2].toLowerCase()),match[1]);
    match=text.match(/\b(\d{1,2})[/.](\d{1,2})[/.]((?:19|20)\d{2})\b/);return match?calendarDate(match[3],match[2],match[1]):'';
  }
  function publication(source={}){
    const metadata=source.metadata||{};
    const fields=[['date',source.date],['publishedDate',source.publishedDate],['published_at',source.published_at],['datePublished',source.datePublished],['metadata.publishedTime',metadata.publishedTime],['metadata.publishedDate',metadata.publishedDate],['metadata.datePublished',metadata.datePublished],['article:published_time',metadata['article:published_time']],['metadata.dcDate',metadata.dcDate]];
    for(const [dateSource,value] of fields){const date=parseDate(value);if(date)return {date,dateSource:source.dateSource||dateSource};}
    const url=String(source.url||metadata.sourceURL||'');let match=url.match(/\/(19\d{2}|20\d{2})\/(\d{1,2})\/(\d{1,2})(?:\/|$)/);if(match){const date=calendarDate(match[1],match[2],match[3]);if(date)return {date,dateSource:'dated-url'};}
    const title=clean(source.title||metadata.title);let date=parseDate(title);if(date)return {date,dateSource:'page-title'};
    // Publication datelines only: never turn footer copyright, scrape time or a bare planning year into publication time.
    const text=String(source.markdown||source.content||source.text||source.description||'').slice(0,2500).replace(/\[[^\]]*\]\([^)]*\)/g,'').replace(/\b(?:©|copyright)\b[^\n]*/gi,'');
    date=parseDate(text);if(date)return {date,dateSource:'page-dateline'};
    match=(title+' '+url).match(/(?:\/|\b)(19\d{2}|20\d{2})(?:\/|\b)/);return {date:'',dateSource:'unknown',historicalYear:match?Number(match[1]):null};
  }
  function recency(source={},now=Date.now(),days=365){const info=publication(source);if(!info.date)return {...info,status:info.historicalYear&&info.historicalYear<new Date(now).getUTCFullYear()-1?'historical':'unknown'};const ageDays=(now-Date.parse(info.date))/86400000;return {...info,ageDays,status:ageDays<-7?'future':ageDays>days?'historical':'recent'};}
  const FAILURE=/(?:ERR_BLOCKED_BY_CLIENT|ERR_ACCESS_DENIED|ERR_CONNECTION|content is blocked|is blocked ERR|cloudflare ray id|verify you are human|checking your browser|access denied|page not found|403 forbidden|404 not found)/i;
  function usable(source={}){const metadata=source.metadata||{},status=Number(source.statusCode||metadata.statusCode)||200;const body=clean(source.markdown||source.content||source.text||source.description);return status>=200&&status<400&&!source.error&&!metadata.error&&!((body.length<1600||/^(?:access denied|just a moment|verify you are human)/i.test(body))&&FAILURE.test(body));}
  const DISCLAIMER=/(?:forward[- ]looking statements?|projections? of (?:revenues?|volumes?|margins?)|expectations? regarding|actual results? (?:may|could|will) (?:differ|vary)|risks? and uncertainties|no obligation to update|not guarantees? of future|statements? (?:are|is) based on|for illustrative purposes|does not constitute (?:an offer|investment advice))/i;
  function claimText(value){let text=String(value||'');const heading=text.search(/(?:^|\n)\s*#{0,4}\s*(?:forward[- ]looking statements?|safe harbor|legal disclaimer)\s*(?:\n|:)/i);if(heading>=0)text=text.slice(0,heading);return text.split(/(?<=[.!?])\s+|\n+/).filter(sentence=>!DISCLAIMER.test(sentence)&&!FAILURE.test(sentence)).join('\n');}
  const GENERIC=new Set(('currently relevant development structure structures company companies business businesses market markets customer customers service services product products industrial industry industries manufacturing manufacturer manufacturers production producer producers factory factories facility facilities engineering engineer engineers equipment project projects technology technologies solution solutions organization organizations employee employees custom serial sweden swedish sverige priority priorities strategic strategy growth growing advanced innovative innovation quality high low strong leading needs need required requires requiring available provide provides providing help helps support supports supporting deliver delivers delivery improve improves improving create creates based focus focused focuses potential opportunity opportunities operations operating commercial including includes include related mainly primarily specific different various broad today tomorrow future general additional international global domestic local online should would could must have has had with from that this your their into more less very also only both other another about such each many some most every well best real data information customers outcomes effective efficient efficiency relevant successful success important new latest current established website websites analysis research description confirmed known planned verified targeting target targets demand problems challenges capability capabilities process processes investment funding expansion necessary use used using offer offers seller sellers supplier suppliers offering means intended suitable seeking searching reference references similar similarity limited existing evidence recently recent often normally typically generally and are for not our the will financial statements expectations regarding projections revenues volumes margins cash flow profitability value revenue services').split(' '));
  function terms(value){return [...new Set(clean(value).toLowerCase().normalize('NFKC').match(/[\p{L}\p{N}]+/gu)||[])].filter(word=>word.length>=4&&!GENERIC.has(word)&&!/^\d+$/.test(word));}
  return {host,companyDomain,firstParty,publication,recency,usable,claimText,terms,isDisclaimer:value=>DISCLAIMER.test(String(value||''))};
});
