const MAIN_STORAGE_KEY="leadintel_customer_v2_state";
const DISCOVERY_STORAGE_KEY="leadintel_customer_v2_discovery";
const OUTREACH_STORAGE_KEY="leadintel_customer_v2_outreach";
const DELIVERY_STORAGE_KEY="leadintel_customer_v2_delivery";
const DISCOVERY_META_KEY="leadintel_customer_v2_discovery_meta";
const INTELLIGENCE_PROXY="https://apollo-proxy.edgars-7e7.workers.dev";
const MAX_DOSSIER_SEARCH_QUERIES=2;
const MAX_DOSSIER_RESULTS_PER_QUERY=5;
const ASSET_VERSION="20261004-linkedin-message-v1";
const LANGUAGE_ASSET_VERSION="20260924-workspace-content-english-v1";
const asset=path=>`${path}?v=${ASSET_VERSION}`;
const q=id=>document.getElementById(id);
let handoffContact=null;
let outreach=loadOutreach({recoverInterrupted:true});
let scriptRestoreRequest=0;
let scriptGenerationRequest=0;
function contentLanguage(){return LeadIntelContentLanguage.workspaceContentLanguage();}

function esc(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function readJson(key){try{return JSON.parse(localStorage.getItem(key)||"{}");}catch{return {};}}
function mainState(){return readJson(MAIN_STORAGE_KEY);}
function campaignStudio(){const main=mainState();return LeadIntelOutreach.normalizeCampaignStudio(main.campaignStudio||{},main.profile||{},contentLanguage());}
function persistCampaignStudio(studio,{sync=true}={}){const main=mainState();main.campaignStudio=studio;localStorage.setItem(MAIN_STORAGE_KEY,JSON.stringify(main));window.LeadIntelJourney?.refresh?.();if(sync)window.LeadIntelServerBridge?.saveNow?.().catch(()=>null);return studio;}
function ensureCampaignStudio(){const main=mainState(),studio=campaignStudio();if(JSON.stringify(main.campaignStudio||null)!==JSON.stringify(studio))persistCampaignStudio(studio,{sync:false});return studio;}
function activeCampaignScenario(){const studio=ensureCampaignStudio();return studio.presets.find(item=>item.id===studio.selectedPresetId)||studio.coreScenario;}
function persistMainStep(step){
  const marker=document.querySelector(`[data-step-marker="${step}"]`);
  if(marker&&!marker.classList.contains("active")){marker.dispatchEvent(new MouseEvent("click",{bubbles:true}));return;}
  const main=mainState();main.step=step;localStorage.setItem(MAIN_STORAGE_KEY,JSON.stringify(main));
}
function discoveryState(){return LeadIntelDiscovery.normalizeDiscoveryState(readJson(DISCOVERY_STORAGE_KEY));}
function saveDiscovery(value){localStorage.setItem(DISCOVERY_STORAGE_KEY,JSON.stringify(LeadIntelDiscovery.normalizeDiscoveryState(value)));}
function loadOutreach({recoverInterrupted=false}={}){const state=LeadIntelOutreach.normalizeOutreachState(readJson(OUTREACH_STORAGE_KEY));if(recoverInterrupted)for(const item of state.items){if(['running','checking'].includes(item.localizationStatus)){item.localizationStatus='error';item.localizationApprovalBlocked=true;item.localizationMessage='Generation was interrupted by a reload. Regenerate this package before approval.';}if(item.researchStatus==='running')item.researchStatus='error';}return state;}
function saveOutreach(){outreach=LeadIntelOutreach.normalizeOutreachState(outreach);localStorage.setItem(OUTREACH_STORAGE_KEY,JSON.stringify(outreach));window.LeadIntelJourney?.refresh?.();}
function toast(message){const el=q("toast");if(!el)return;el.textContent=message;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2600);}
function pipeline(){const shared=window.LeadIntelDiscoveryUI?.getSelectedCompanies?.()||window.LeadIntelDiscoveryUI?.getPipeline?.();if(Array.isArray(shared))return shared;const state=discoveryState();return [...new Map([...(state.pipeline||[]),...(state.selectedProspects||[])].map(item=>[item.domain,item])).values()];}
function selectedCandidate(){const domain=outreach.selectedDomain;return pipeline().find(item=>item.domain===domain)||null;}
function currentItem(){return outreach.items.find(item=>item.domain===outreach.selectedDomain)||null;}
function upsertItem(next){const idx=outreach.items.findIndex(item=>item.domain===next.domain);if(idx>=0)outreach.items[idx]=next;else outreach.items.unshift(next);outreach.items=outreach.items.slice(0,50);saveOutreach();return next;}
function stageAtLeast(current,target){const stages=LeadIntelDiscovery.CRM_STAGES;return stages.indexOf(current)>=stages.indexOf(target);}
function updatePipelineStage(domain,targetStage){
  const discovery=discoveryState();const item=discovery.pipeline.find(x=>x.domain===domain);if(!item)return false;
  if(!stageAtLeast(item.stage,targetStage))item.stage=targetStage;
  item.updatedAt=new Date().toISOString();saveDiscovery(discovery);return true;
}
function crmBridge(){return window.LeadIntelServerBridge||null;}
function crmAuthenticated(){const b=crmBridge();return Boolean(b?.session?.authenticated&&b?.workspace);}
function crmDomain(value){return window.LeadIntelCrm?.canonicalDomain(value)||String(value||"").replace(/^https?:\/\//,"").replace(/^www\./,"").split(/[/?#]/)[0].toLowerCase();}
function crmActivityId(kind,domain,stamp){return `${kind}-${crmDomain(domain)}-${String(stamp||"")}`.replace(/[^A-Za-z0-9._:-]/g,"-").slice(0,128);}
async function durableCompany(candidate,{create=true}={}){
  if(!candidate||!crmAuthenticated())return {ok:true,localOnly:true,company:null};
  const b=crmBridge(),workspaceId=b.workspace.id,domain=crmDomain(candidate.domain||candidate.website);const listed=await b.listCrmCompanies({q:domain,limit:20});if(workspaceId!==b.workspace?.id)return {ok:false,error:"Workspace changed; retry in the selected workspace"};if(!listed.ok)return listed;
  let company=(listed.companies||[]).find(row=>crmDomain(row.normalized_domain||row.website)===domain)||null;
  if(!company&&!create)return {ok:true,company:null};
  if(!company){const payload=window.LeadIntelCrm?.mapLocalPipelineItemToCrm(candidate);if(!payload)return {ok:false,error:"CRM mapper unavailable"};const saved=await b.saveCrmCompany(payload);if(!saved.ok)return saved;company=saved.company;}
  return {ok:true,company};
}
async function syncCrmActivity(candidate,{activity=null,stage=""}={}){
  const workspaceId=crmBridge()?.workspace?.id;const resolved=await durableCompany(candidate);if(workspaceId!==crmBridge()?.workspace?.id)return {ok:false,error:"Workspace changed"};if(!resolved.ok||resolved.localOnly)return resolved;const b=crmBridge(),company=resolved.company;
  if(activity){const recorded=await b.recordCrmActivity(company.id,activity);if(!recorded.ok)return recorded;if(workspaceId!==b.workspace?.id)return {ok:false,error:"Workspace changed"};}
  let latest=company;if(stage){const moved=await b.addCrmToPipeline(company.id,stage);if(!moved.ok)return moved;latest=moved.company||company;}
  window.dispatchEvent(new CustomEvent("leadintel:crm-changed",{detail:{company:latest}}));return {ok:true,company:latest};
}

async function saveScriptPackage(){
  const edited=readDraftEdits(),candidate=selectedCandidate();if(!edited?.dossier||!candidate)return;
  if(['running','checking'].includes(edited.localizationStatus)||edited.researchStatus==='running'){toast('Wait for script generation before saving the package to CRM');return;}
  const workspaceId=crmBridge()?.workspace?.id,domain=edited.domain;upsertItem(edited);
  const stamp=new Date().toISOString();
  const result=await syncCrmActivity(candidate,{activity:{id:crmActivityId('scripts-saved',domain,stamp),type:'dossier.built',summary:edited.dossier.selectedTrigger?'Trigger-linked scripts saved':'Company scripts saved',occurred_at:stamp,metadata:{script_package:LeadIntelOutreach.buildCrmScriptSnapshot(edited),selected_trigger:edited.dossier.selectedTrigger||null,selected_person_id:edited.selectedPersonId||''}}});
  if(workspaceId!==crmBridge()?.workspace?.id||domain!==outreach.selectedDomain)return;
  q('trigger-script-status').textContent=result.ok&&!result.localOnly?'Scripts and trigger connection saved to CRM.':'Scripts remain in this browser. Sign in or retry CRM save.';
}
async function restoreScriptPackage(){
  const candidate=selectedCandidate();if(!candidate||!crmAuthenticated())return;
  const request=++scriptRestoreRequest,workspaceId=crmBridge().workspace.id,domain=candidate.domain;
  const resolved=await durableCompany(candidate,{create:false});if(!resolved.ok||!resolved.company){q('trigger-script-status').textContent='No saved CRM company package yet.';return;}
  if(request!==scriptRestoreRequest||workspaceId!==crmBridge()?.workspace?.id||domain!==outreach.selectedDomain)return;
  const detail=await crmBridge().getCrmCompany(resolved.company.id);
  if(request!==scriptRestoreRequest||workspaceId!==crmBridge()?.workspace?.id||domain!==outreach.selectedDomain)return;
  if(!detail.ok){q('trigger-script-status').textContent='CRM package could not load. Your current scripts are unchanged.';return;}
  const activities=detail.activities||[];let cursor=detail.activity_next_cursor;const cursors=new Set();
  while(!activities.some(activity=>activity.metadata?.script_package)&&cursor&&!cursors.has(cursor)){
    cursors.add(cursor);const page=await crmBridge().getCrmActivities(resolved.company.id,{limit:100,cursor});
    if(request!==scriptRestoreRequest||workspaceId!==crmBridge()?.workspace?.id||domain!==outreach.selectedDomain)return;
    if(!page.ok){q('trigger-script-status').textContent='CRM history could not load. Your current scripts are unchanged.';return;}
    activities.push(...(page.activities||[]));cursor=page.next_cursor;
  }
  const saved=activities.find(activity=>activity.metadata?.script_package);
  const item=LeadIntelOutreach.restoreCrmScriptSnapshot(saved?.metadata?.script_package,domain);
  if(!item){q('trigger-script-status').textContent='No saved script package for this company yet.';return;}
  scriptGenerationRequest++;upsertItem(item);renderDossier();q('trigger-script-status').textContent='Saved scripts and trigger connection reopened from CRM.';
}
async function loadTriggerAlerts(){
  const candidate=selectedCandidate(),item=currentItem(),bridge=crmBridge();if(!candidate||!item?.dossier||!crmAuthenticated()){toast('Sign in and build the company dossier first');return;}
  const domain=candidate.domain,workspaceId=bridge.workspace.id;
  try{
    const response=await fetch(`https://leadintel-api.edgars-7e7.workers.dev/api/market-monitoring/alerts?workspace_id=${encodeURIComponent(workspaceId)}`,{credentials:'include',headers:{Accept:'application/json'}});
    const result=await response.json();if(!response.ok)throw Error(result.error||'Monitoring alerts unavailable');
    if(workspaceId!==crmBridge()?.workspace?.id||domain!==outreach.selectedDomain)return;
    q('trigger-monitoring-alerts').innerHTML=(result.alerts||[]).map(alert=>`<article><a href="${esc(alert.source_url)}" target="_blank" rel="noopener">${esc(alert.title)}</a><p>${esc(alert.summary)}</p><small>Detected: ${esc(alert.created_at)} · source date unknown · company association needs review</small><button class="secondary-btn small" type="button" data-add-trigger-alert="${esc(alert.id)}">Review for ${esc(candidate.company)}</button></article>`).join('')||'<p>No monitoring alerts yet.</p>';
    q('trigger-monitoring-alerts').onclick=event=>{const button=event.target.closest('[data-add-trigger-alert]');if(!button||domain!==outreach.selectedDomain||workspaceId!==crmBridge()?.workspace?.id)return;const alert=(result.alerts||[]).find(row=>row.id===button.dataset.addTriggerAlert);if(!alert)return;const current=currentItem();if(!current?.dossier)return;const evidence={url:alert.source_url,title:alert.title,description:alert.summary,text:alert.summary,date:'',detectedAt:alert.created_at,sourceType:'Public'};current.dossier.evidence=[...(current.dossier.evidence||[]).filter(row=>row.url!==alert.source_url),evidence].slice(-15);upsertItem(current);renderDossier();q('outreach-trigger-select').value=alert.source_url;previewSelectedTrigger();};
  }catch(error){q('trigger-script-status').textContent=error.message;}
}
function previewSelectedTrigger(){const item=currentItem(),url=q('outreach-trigger-select')?.value;const source=item?.dossier?.evidence?.find(row=>row.url===url);q('trigger-source-preview').innerHTML=source?`<a href="${esc(source.url)}" target="_blank" rel="noopener">${esc(source.title||source.url)} ↗</a><br>Source date: ${esc(source.date||'unknown')}<br>${esc(String(source.text||source.description||'').slice(0,900))}`:'Select and review a source before connecting it to scripts.';q('trigger-source-confirm').checked=false;}
async function useReviewedTrigger(){
  const current=currentItem();if(!current?.dossier)return;
  if(!q('trigger-source-confirm').checked){toast('Confirm that you checked the source, company and event first');return;}
  try{const item=LeadIntelOutreach.reviewTrigger(current,q('outreach-trigger-select').value);upsertItem(item);const generated=await regenerateDrafts();if(!generated)return;q('trigger-script-status').textContent=generated.localizationApprovalBlocked?'Trigger selected; resolve the script language before approval.': 'Reviewed trigger connected to the selected buyer. Save scripts to CRM to preserve the connection.';}catch(error){toast(error.message);}
}

function injectOutreachUI(){
  if(!document.querySelector('link[data-leadintel-asset="outreach-css"]')){const link=document.createElement("link");link.rel="stylesheet";link.href=asset("outreach.css");link.dataset.leadintelAsset="outreach-css";document.head.appendChild(link);}
  const pipelinePanel=document.querySelector("#step-5 .pipeline-panel");
  if(pipelinePanel&&!q("continue-to-outreach"))pipelinePanel.insertAdjacentHTML("afterend",'<div class="outreach-entry workflow-next-action" hidden><div><span class="eyebrow">Next step</span><strong>Identify the buyers at a saved company, then prepare a relevant message.</strong></div><button class="primary-btn stage-next-action" id="continue-to-outreach" type="button" disabled aria-disabled="true">Continue to Buyers →</button></div>');
  const content=document.querySelector("main.content");
  if(content&&!q("step-6"))content.insertAdjacentHTML("beforeend",`<section class="step-view" id="step-6" data-step="6">
    <div class="profile-header outreach-header"><div><span class="eyebrow">Step 6 · Messages</span><h1>Turn evidence into messages buyers will want to answer.</h1><p>Set the message strategy, tailor scripts to a specific company and buyer, then review and approve the complete package before delivery.</p></div><div class="profile-header-actions"><span class="profile-status" id="outreach-status">Ready</span><button class="secondary-btn small" id="back-to-discovery" type="button">← Buyers</button></div></div>
    <section class="panel campaign-core-panel"><div class="campaign-section-head"><div class="section-title"><span class="eyebrow">Message approach</span><h3>Core Message Approach</h3><p>LeadIntel creates this from your approved Profile. Accept it or adjust the working defaults below. It remains the fallback for every campaign.</p></div><span class="campaign-status" id="core-scenario-status">Draft</span></div><label class="draft-label">Scenario summary<textarea id="core-scenario-summary" rows="4"></textarea></label><div class="core-scenario-fields"><label>Target segment<input id="core-scenario-segment" type="text"></label><label>Default offer<input id="core-scenario-offer" type="text"></label><label>Buyer role<input id="core-scenario-buyer-role" type="text"></label><label>Buying trigger<input id="core-scenario-trigger" type="text"></label><label>Value proposition<input id="core-scenario-value" type="text"></label><label>Commercial objective<input id="core-scenario-objective" type="text"></label><label>Default next step<input id="core-scenario-cta" type="text"></label><label>Tone<select id="core-scenario-tone"><option value="consultative">Consultative</option><option value="direct">Direct</option><option value="brief">Brief</option></select></label><label>Default content language<select id="core-scenario-language"><option value="en">English</option><option value="lv">Latviešu</option><option value="de">Deutsch</option><option value="sv">Svenska</option><option value="et">Eesti</option><option value="lt">Lietuvių</option><option value="fi">Suomi</option><option value="no">Norsk</option><option value="da">Dansk</option><option value="pl">Polski</option><option value="fr">Français</option><option value="nl">Nederlands</option><option value="es">Español</option><option value="it">Italiano</option><option value="pt">Português</option><option value="cs">Čeština</option><option value="sk">Slovenčina</option><option value="ro">Română</option><option value="bg">Български</option><option value="hr">Hrvatski</option><option value="sl">Slovenščina</option><option value="hu">Magyar</option><option value="el">Ελληνικά</option><option value="uk">Українська</option></select></label></div><div class="campaign-actions"><button class="secondary-btn" id="regenerate-core-scenario" type="button">Regenerate from profile</button><button class="primary-btn" id="save-core-scenario" type="button">Accept & save default</button></div></section>
    <section class="panel campaign-builder-panel"><div class="section-title"><span class="eyebrow">Specific segment</span><h3>Create or reuse a campaign preset</h3><p>Only the segment is required. Offer, buyer, trigger, value proposition and next step inherit from your Core Outreach Scenario.</p></div><div class="campaign-builder-grid"><label>Saved preset<select id="campaign-preset-select"><option value="">Core Outreach Scenario</option></select></label><label>Who do you want to contact? <b>Required</b><input id="campaign-segment" type="text" placeholder="Example: German furniture retailers"></label><label>Tone<select id="campaign-tone"><option value="consultative">Consultative</option><option value="direct">Direct</option><option value="brief">Brief</option></select></label><button class="primary-btn" id="save-campaign-preset" type="button">Save & use preset</button></div><div class="campaign-active" id="campaign-active-summary"></div></section>
    <section class="panel dossier-selector"><div class="section-title"><span class="eyebrow">Opportunity research</span><h3>Choose a saved pipeline company</h3><p>Each dossier uses one official-site scrape and at most two targeted public searches. If the pipeline is empty, return to Discovery when you are ready to create an opportunity.</p></div><div class="dossier-select-row"><select id="outreach-company-select"></select><button class="primary-btn" id="build-opportunity-dossier" type="button">Build dossier ✦</button></div><div class="research-status" id="dossier-research-status">No saved company yet · module available.</div></section>
    <div id="dossier-workspace" hidden>
      <div class="dossier-summary-grid"><article class="dossier-card emphasis"><span>Why now</span><p id="dossier-why-now"></p></article><article class="dossier-card"><span>Recommended offer</span><strong id="dossier-offer"></strong><small id="dossier-confidence"></small></article><article class="dossier-card"><span>Buyer strategy</span><div id="dossier-buyers" class="buyer-chips"></div></article></div>
      <section class="panel dossier-panel"><div class="section-title"><span class="eyebrow">Evidence ledger</span><h3>What the recommendation is actually based on</h3><p>Official, public and inherited Discovery evidence remain distinguishable.</p></div><div id="dossier-evidence" class="dossier-evidence"></div></section>
      <section class="panel dossier-panel hypothesis-panel"><div class="section-title"><span class="eyebrow">Commercial hypotheses</span><h3>Questions to validate—not facts</h3></div><div id="dossier-hypotheses" class="hypothesis-list"></div></section>
      <section class="panel dossier-panel outreach-drafts"><div class="draft-head"><div class="section-title"><span class="eyebrow">Campaign scripts</span><h3>Create the complete conversation package</h3><p>Accept the generated scripts, edit or replace any text, or regenerate the full package. Nothing is sent until the package is approved.</p></div><div class="draft-controls"><select id="outreach-contact-select" aria-label="Decision maker"></select><select id="outreach-tone" aria-label="Outreach tone"><option value="consultative">Consultative</option><option value="direct">Direct</option><option value="brief">Brief</option></select><label class="translation-control"><span>Translate / localize</span><select id="outreach-email-language" aria-label="Translation target language"><option value="">Choose target language</option><option value="en">English</option><option value="lv">Latviešu</option><option value="de">Deutsch</option><option value="sv">Svenska</option><option value="et">Eesti</option><option value="lt">Lietuvių</option><option value="fi">Suomi</option><option value="no">Norsk</option><option value="da">Dansk</option><option value="pl">Polski</option><option value="fr">Français</option><option value="nl">Nederlands</option><option value="es">Español</option><option value="it">Italiano</option><option value="pt">Português</option><option value="cs">Čeština</option><option value="sk">Slovenčina</option><option value="ro">Română</option><option value="bg">Български</option><option value="hr">Hrvatski</option><option value="sl">Slovenščina</option><option value="hu">Magyar</option><option value="el">Ελληνικά</option><option value="uk">Українська</option></select></label><button class="secondary-btn small" id="translate-outreach" type="button">Translate / localize</button><button class="secondary-btn small" id="regenerate-outreach" type="button">Regenerate all</button></div></div>
        <section class="panel trigger-script-panel"><h3>Company trigger → buyer scripts</h3><p>Choose a company event, check its source and date, then connect it to the buyer selected above. A detected event does not establish buying intent.</p><label>Trigger source<select id="outreach-trigger-select"></select></label><p id="trigger-source-preview"></p><label><input type="checkbox" id="trigger-source-confirm"> I checked the source and confirm this event concerns the selected company.</label><div class="draft-controls"><button class="secondary-btn" id="use-reviewed-trigger" type="button">Use reviewed trigger</button><button class="secondary-btn" id="load-trigger-alerts" type="button">Load monitoring alerts</button><button class="primary-btn" id="save-trigger-scripts" type="button">Save scripts to CRM</button><button class="secondary-btn" id="restore-trigger-scripts" type="button">Reopen saved scripts</button></div><p id="trigger-script-status" role="status"></p><div id="trigger-monitoring-alerts"></div><small>Refresh the company dossier to recheck its sources. Automatic monitoring is managed in Strategy.</small></section><div class="script-grid">
          <article class="script-card script-card-wide"><div class="script-card-head"><div><span class="script-number">01</span><strong>Cold email</strong><small>Evidence-led first contact</small></div><button class="text-btn copy-btn" type="button" data-copy-field="email">Copy email</button></div><label class="draft-label">Subject<input id="outreach-email-subject" type="text"></label><label class="draft-label">Email body<textarea id="outreach-email-body" rows="10"></textarea></label><div id="outreach-email-preview" hidden><div class="draft-controls"><button class="secondary-btn small" id="outreach-preview-html" type="button">HTML preview</button><button class="secondary-btn small" id="outreach-preview-text" type="button">Plain-text preview</button></div><iframe id="outreach-preview-frame" title="Approved email HTML preview" sandbox="" hidden></iframe><pre id="outreach-preview-plain" hidden></pre></div></article>
          <article class="script-card"><div class="script-card-head"><div><span class="script-number">02</span><strong>LinkedIn message</strong><small>Short social first touch</small></div><button class="text-btn copy-btn" type="button" data-copy-field="linkedin">Copy</button></div><label class="draft-label">Message<textarea id="outreach-linkedin" rows="7"></textarea></label></article>
          <article class="script-card"><div class="script-card-head"><div><span class="script-number">03</span><strong>Call opener</strong><small>Permission-based opening</small></div><button class="text-btn copy-btn" type="button" data-copy-field="call">Copy</button></div><label class="draft-label">Opening script<textarea id="outreach-call-opener" rows="7"></textarea></label></article>
          <article class="script-card"><div class="script-card-head"><div><span class="script-number">04</span><strong>Follow-up email</strong><small>Close the loop without pressure</small></div><button class="text-btn copy-btn" type="button" data-copy-field="followup">Copy</button></div><label class="draft-label">Follow-up<textarea id="outreach-follow-up" rows="7"></textarea></label></article>
          <article class="script-card"><div class="script-card-head"><div><span class="script-number">05</span><strong>Objection / reply script</strong><small>Handle “not now” or “not relevant”</small></div><button class="text-btn copy-btn" type="button" data-copy-field="objection">Copy</button></div><label class="draft-label">Response<textarea id="outreach-objection-reply" rows="7"></textarea></label></article>
        </div>
        <div class="outreach-approval"><div><span class="eyebrow">Approval gate</span><strong id="outreach-approval-label">Draft not approved</strong><small id="outreach-approval-help">Approval freezes the message scenario, scripts and current email identity, then moves the opportunity to Ready for Outreach. Sending remains a separate explicit action in Delivery.</small></div><div class="outreach-approval-actions"><button class="secondary-btn" id="preview-approved-email" type="button" hidden>Preview approved email</button><button class="secondary-btn" id="mark-contacted" type="button" disabled>Mark contacted</button><button class="primary-btn" id="approve-outreach" type="button">Approve message package</button></div></div>
      </section>
    </div>
  </section>`);
}
function showStep(step){persistMainStep(step);document.querySelectorAll(".step-view").forEach(el=>el.classList.toggle("active",Number(el.dataset.step)===step));document.querySelectorAll("[data-step-marker]").forEach(el=>{const n=Number(el.dataset.stepMarker);el.classList.toggle("active",n===step);el.classList.toggle("complete",n<step);});window.scrollTo({top:0,behavior:"smooth"});}
function showOutreachStep(){ensureSelection();renderAll();showStep(6);}
function continueFromCompanies(){
  const stage=Number(q("continue-to-outreach")?.dataset.journeyStage)||5;
  if(stage===6&&window.LeadIntelDiscoveryUI?.continueToMessages){window.LeadIntelDiscoveryUI.continueToMessages();return;}
  if(window.LeadIntelJourney?.openWorkflowStage){window.LeadIntelJourney.openWorkflowStage(stage);return;}
  if(stage===5){window.LeadIntelDiscoveryUI?.open?.({focus:"buyers"});return;}
  showOutreachStep();
}
function backToDiscovery(){try{const meta=readJson(DISCOVERY_META_KEY);localStorage.setItem(DISCOVERY_META_KEY,JSON.stringify({...meta,activeJourneyStage:5,visibleStep:5}));}catch{}if(window.LeadIntelJourney?.openWorkflowStage){window.LeadIntelJourney.openWorkflowStage(5);return;}if(window.LeadIntelDiscoveryUI?.open){window.LeadIntelDiscoveryUI.open({focus:"buyers"});return;}showStep(5);}
function ensureSelection(){const list=pipeline();if(!list.length){outreach.selectedDomain="";saveOutreach();return;}if(!list.some(x=>x.domain===outreach.selectedDomain))outreach.selectedDomain=list[0].domain;saveOutreach();}

async function officialScrape(candidate){
  const response=await fetch(`${INTELLIGENCE_PROXY}/firecrawl-scrape`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:candidate.website,formats:["markdown"],onlyMainContent:true,timeout:30000})});
  const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Official site returned ${response.status}`);
  return LeadIntelOutreach.normalizeDossierResearchResults(payload,{domain:candidate.domain,sourceType:"official",url:candidate.website});
}
async function dossierSearch(meta){
  const response=await fetch(`${INTELLIGENCE_PROXY}/firecrawl-search`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:meta.query,limit:MAX_DOSSIER_RESULTS_PER_QUERY,scrapeOptions:{formats:["markdown"]}})});
  const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Dossier search returned ${response.status}`);
  return LeadIntelOutreach.normalizeDossierResearchResults(payload,{domain:meta.domain,sourceType:"search"});
}
function cancelPendingScriptGeneration(){
  scriptGenerationRequest++;const current=currentItem();if(current?.localizationStatus==='running'){upsertItem({...current,localizationStatus:'error',localizationApprovalBlocked:true,localizationMessage:'Generation was interrupted by a selection change. Regenerate this package before approval.'});}
}
async function prepareLocalizedItem(item,campaign,candidate){
  if(item.channel==='linkedin')return {...item,localizationStatus:'not_required',localizationApprovalBlocked:false,localizationMessage:'LinkedIn direct-message draft · review and edit before copying'};
  const request=++scriptGenerationRequest,domain=item.domain,bridge=crmBridge(),workspace=bridge?.session?.authenticated?bridge?.workspace?.id:'';if(domain!==outreach.selectedDomain)return null;if(item.researchStatus==='running')item={...item,researchStatus:item.dossier?.evidence?.length?'partial':'error'};const pending={...item,localizationStatus:item.drafts?.requiresAiLocalization?'running':'checking',localizationApprovalBlocked:true,localizationMessage:'Resolving recipient language…'};upsertItem(pending);renderDossier();
  const result=await LeadIntelOutreachLocalization.prepareCampaignDrafts({root:window,workspace,drafts:item.drafts,scenario:campaign,candidate:candidate||{},dossier:item.dossier||{},languageService:LeadIntelContentLanguage});
  if(request!==scriptGenerationRequest||domain!==outreach.selectedDomain||workspace!==(crmBridge()?.session?.authenticated?crmBridge()?.workspace?.id:''))return null;
  return {...item,drafts:result.drafts,campaignScenario:{...campaign,resolvedLanguage:result.provenance.language,languageSource:result.provenance.selectionSource},localizationStatus:result.status,localizationApprovalBlocked:result.approvalBlocked,localizationMessage:result.message,localizationProvenance:result.provenance};
}
async function buildDossier(){
  const candidate=selectedCandidate();if(!candidate){toast("Choose a saved pipeline company");return;}
  if(crmAuthenticated()&&(!handoffContact||handoffContact.domain!==candidate.domain||!candidate.people?.some(p=>p.id===handoffContact.personId&&p.kept))){toast('Save a buyer and confirm the selected contact channel in Buyers before creating content.');backToDiscovery();return;}
  const researchRequest=++scriptGenerationRequest,workspaceId=crmBridge()?.workspace?.id,main=mainState();let item=currentItem()||{domain:candidate.domain,company:candidate.company,drafts:{tone:"consultative",emailSubject:"",emailBody:"",linkedinMessage:"",callOpener:"",followUp:"",objectionReply:""},approved:false};
  item=LeadIntelOutreach.invalidateOutreachApproval({...item,channel:handoffContact?.channel||'email',company:candidate.company,researchStatus:"running"});upsertItem(item);renderAll();
  const research=[];let failures=0;try{research.push(...await officialScrape(candidate));}catch{failures++;}
  const queries=LeadIntelOutreach.buildDossierSearchQueries(candidate,main.profile||{},main.market||{},MAX_DOSSIER_SEARCH_QUERIES);for(const meta of queries){try{research.push(...await dossierSearch(meta));}catch{failures++;}}
  if(researchRequest!==scriptGenerationRequest||candidate.domain!==outreach.selectedDomain||workspaceId!==crmBridge()?.workspace?.id)return;
  if(handoffContact?.channel==='linkedin'&&!window.LeadIntelDiscovery.confirmedLinkedInBuyer(candidate.people.find(p=>p.id===handoffContact.personId),candidate,readJson(DISCOVERY_META_KEY).scriptBuyer,workspaceId)){toast('LinkedIn selection changed. Confirm it again in Buyers.');return;}
  const language=contentLanguage(),campaign=activeCampaignScenario();const dossierCandidate=handoffContact&&handoffContact.domain===candidate.domain?{...candidate,people:(candidate.people||[]).filter(p=>handoffContact.channel!=='linkedin'||p.id===handoffContact.personId).map(p=>p.id===handoffContact.personId?{...p,...handoffContact.contact,id:p.id,name:handoffContact.contact.name||p.name,email:handoffContact.contact.work_email||handoffContact.contact.normalized_email}:p)}:candidate;let dossier=LeadIntelOutreach.buildOpportunityDossier(dossierCandidate,main.profile||{},main.market||{},research,language);const choice=readJson(DISCOVERY_META_KEY).scriptBuyer;const contact=dossierCandidate.people?.find(p=>p.id===choice?.personId)||dossierCandidate.people?.[0]||null;
  item=LeadIntelOutreach.invalidateOutreachApproval({...item,dossier,campaignScenario:campaign,researchStatus:research.length?(failures?"partial":"complete"):"error",researchAt:new Date().toISOString(),selectedPersonId:contact?.id||"",drafts:LeadIntelOutreach.buildOutreachDrafts(dossier,contact,main.profile||{},campaign.tone||"consultative",language,campaign),contentLanguage:language});item=await prepareLocalizedItem(item,campaign,candidate);if(!item)return;upsertItem(item);
  const crm=await syncCrmActivity(candidate,{activity:{id:crmActivityId("dossier-built",candidate.domain,item.researchAt),type:"dossier.built",summary:"Opportunity dossier built",occurred_at:item.researchAt,metadata:{evidence_count:dossier.evidence?.length||0,research_status:item.researchStatus,script_package:LeadIntelOutreach.buildCrmScriptSnapshot(item)}}});renderAll();
  const baseMessage=research.length?`Dossier built from ${dossier.evidence.length} evidence source${dossier.evidence.length===1?"":"s"}${failures?" · some research unavailable":""}`:"Dossier kept conservative because public research was unavailable";toast(!crm.ok?`${baseMessage} · CRM sync unavailable`:baseMessage);
}
function selectedContact(item){if(!item?.dossier?.people?.length)return null;return item.dossier.people.find(p=>p.id===item.selectedPersonId)||item.dossier.people[0];}
async function regenerateDrafts(){const current=currentItem();if(!current?.dossier)return;if(current.contextNeedsRefresh)return buildDossier();const campaign={...activeCampaignScenario(),tone:q("outreach-tone").value};let item=LeadIntelOutreach.invalidateOutreachApproval(current);item.campaignScenario=campaign;item.selectedPersonId=q("outreach-contact-select").value;item.drafts=LeadIntelOutreach.buildOutreachDrafts(item.dossier,selectedContact(item),mainState().profile||{},campaign.tone,contentLanguage(),campaign);item.contentLanguage=contentLanguage();item=await prepareLocalizedItem(item,campaign,selectedCandidate()||item.dossier);if(!item)return;upsertItem(item);renderDossier();toast(item.localizationApprovalBlocked?item.localizationMessage:"Campaign scripts regenerated · approval required");return item;}
async function confirmOutreachLanguage(){const current=currentItem(),language=q("outreach-email-language")?.value;if(!current?.dossier||!language)return;const campaign={...(current.campaignScenario||activeCampaignScenario()),tone:q("outreach-tone").value,language,resolvedLanguage:language,languageSource:'manual'};let item=LeadIntelOutreach.invalidateOutreachApproval(current);item.campaignScenario=campaign;item.selectedPersonId=q("outreach-contact-select").value;item.drafts=LeadIntelOutreach.buildOutreachDrafts(item.dossier,selectedContact(item),mainState().profile||{},campaign.tone,contentLanguage(),campaign);item=await prepareLocalizedItem(item,campaign,selectedCandidate()||item.dossier);if(!item)return;upsertItem(item);renderDossier();toast(item.localizationApprovalBlocked?item.localizationMessage:`Recipient email language confirmed · ${LeadIntelContentLanguage.EMAIL_LANGUAGES?.[language]||language}`);}
function readDraftEdits(){const item=currentItem();if(!item)return null;return {...item,drafts:{...item.drafts,tone:q("outreach-tone").value,emailSubject:q("outreach-email-subject").value.trim(),emailBody:q("outreach-email-body").value,linkedinMessage:q("outreach-linkedin").value,callOpener:q("outreach-call-opener").value,followUp:q("outreach-follow-up").value,objectionReply:q("outreach-objection-reply").value}};}
async function approveOutreach(){const source=currentItem(),edited=readDraftEdits();if(source?.channel==='linkedin'){toast('Review, edit and copy the LinkedIn draft. Sending is separate.');return;}if(!source?.dossier||!edited){toast("Build the dossier first");return;}if(source.localizationApprovalBlocked){toast(source.localizationMessage||"Confirm the email language before approval");return;}const campaign=source.campaignScenario||activeCampaignScenario();const item=LeadIntelOutreach.approveOutreachItem(source,edited.drafts,new Date().toISOString(),{brandIdentity:mainState().brandIdentity,campaignScenario:campaign});upsertItem(item);if(!item.approved){toast(item.error);renderDossier();return;}updatePipelineStage(item.domain,"Ready for Outreach");const candidate=selectedCandidate()||{domain:item.domain,company:item.company,stage:"Ready for Outreach"};const crm=await syncCrmActivity(candidate,{activity:{id:crmActivityId("content-approved",item.domain,item.approvedAt),type:"content.approved",summary:"Campaign scripts approved",occurred_at:item.approvedAt,metadata:{script_package:LeadIntelOutreach.buildCrmScriptSnapshot(item),selected_trigger:item.dossier?.selectedTrigger||null,tone:item.drafts?.tone||"",selected_person_id:item.selectedPersonId||"",brand_revision:item.brandSnapshot?.revision||null,campaign_id:campaign.id||"core",campaign_segment:campaign.segment||"",email_language:item.localizationProvenance?.language||"",localization_provider:item.localizationProvenance?.provider||""}},stage:"Ready for Outreach"});renderDossier();window.dispatchEvent(new CustomEvent("leadintel:outreach-approved",{detail:{domain:item.domain,email:LeadIntelOutreach.buildApprovedSendPayload(item)}}));toast(crm.ok?"Campaign approved · Pipeline is Ready for Outreach":"Campaign approved locally · CRM sync unavailable");}

function renderApprovedPreview(mode="html"){
  const item=currentItem(),email=LeadIntelOutreach.renderApprovedEmail(item);if(!email){toast("Approve the campaign package before previewing it");return;}
  const wrap=q("outreach-email-preview"),frame=q("outreach-preview-frame"),plain=q("outreach-preview-plain");wrap.hidden=false;
  const showHtml=mode==="html"&&Boolean(email.htmlBody);frame.hidden=!showHtml;plain.hidden=showHtml;
  if(showHtml)frame.srcdoc=email.htmlBody;else plain.textContent=`${email.subject}\n\n${email.textBody}`;
}
async function markContacted(){const item=currentItem();if(!item?.approved){toast("Approve the campaign package first");return;}updatePipelineStage(item.domain,"Contacted");item.contactedAt=new Date().toISOString();upsertItem(item);const candidate=selectedCandidate()||{domain:item.domain,company:item.company,stage:"Contacted"};const crm=await syncCrmActivity(candidate,{stage:"Contacted"});renderDossier();toast(crm.ok?"Opportunity marked Contacted":"Contacted locally · CRM sync unavailable");}
async function copyField(type){
  const item=readDraftEdits();if(!item)return;
  const values={email:`${item.drafts.emailSubject}\n\n${item.drafts.emailBody}`,linkedin:item.drafts.linkedinMessage,call:item.drafts.callOpener,followup:item.drafts.followUp,objection:item.drafts.objectionReply};
  const labels={email:"Email",linkedin:"LinkedIn message",call:"Call opener",followup:"Follow-up",objection:"Objection reply"};
  try{await navigator.clipboard.writeText(values[type]||"");toast(`${labels[type]||"Script"} copied`);}catch{toast("Copy was blocked by the browser");}
}

async function applyCampaignToCurrent(){const current=currentItem(),campaign=activeCampaignScenario();if(!current?.dossier)return;let item=LeadIntelOutreach.invalidateOutreachApproval({...current,campaignScenario:campaign});item.drafts=LeadIntelOutreach.buildOutreachDrafts(item.dossier,selectedContact(item),mainState().profile||{},campaign.tone,contentLanguage(),campaign);item.contentLanguage=contentLanguage();item=await prepareLocalizedItem(item,campaign,selectedCandidate()||item.dossier);if(!item)return;upsertItem(item);renderDossier();}
async function regenerateCoreScenario(){const main=mainState(),studio=ensureCampaignStudio();main.campaignStudio=LeadIntelOutreach.regenerateCoreScenario(studio,main.profile||{},contentLanguage());persistCampaignStudio(main.campaignStudio);await applyCampaignToCurrent();renderAll();toast("Core scenario regenerated from your approved Profile");}
async function saveCoreScenario(){try{const main=mainState(),studio=ensureCampaignStudio(),summary=q("core-scenario-summary").value;const saved=LeadIntelOutreach.saveCoreScenario(studio,{...studio.coreScenario,summary,segment:q("core-scenario-segment").value,offer:q("core-scenario-offer").value,buyerRole:q("core-scenario-buyer-role").value,trigger:q("core-scenario-trigger").value,valueProposition:q("core-scenario-value").value,objective:q("core-scenario-objective").value,cta:q("core-scenario-cta").value,tone:q("core-scenario-tone").value,language:q("core-scenario-language").value,status:'approved'},new Date().toISOString(),main.profile||{});persistCampaignStudio(saved);if(!saved.selectedPresetId)await applyCampaignToCurrent();renderAll();toast("Core Outreach Scenario saved as the workspace default");}catch(error){toast(error.message);}}
async function saveCampaignPreset(){try{const studio=ensureCampaignStudio(),segment=q("campaign-segment").value,tone=q("campaign-tone").value;const saved=LeadIntelOutreach.saveCampaignPreset(studio,{segment,tone},new Date().toISOString());persistCampaignStudio(saved);await applyCampaignToCurrent();renderAll();toast("Campaign preset saved and activated");}catch(error){toast(error.message);}}
async function selectCampaignPreset(event){const studio=ensureCampaignStudio(),selectedPresetId=event.target.value;persistCampaignStudio({...studio,selectedPresetId});await applyCampaignToCurrent();renderAll();toast(selectedPresetId?"Campaign preset activated":"Core Outreach Scenario activated");}
function renderCampaignStudio(){const studio=ensureCampaignStudio(),core=studio.coreScenario,active=activeCampaignScenario();const status=q("core-scenario-status");if(!status)return;q("core-scenario-summary").value=core.summary;q("core-scenario-segment").value=core.segment;q("core-scenario-offer").value=core.offer;q("core-scenario-buyer-role").value=core.buyerRole;q("core-scenario-trigger").value=core.trigger;q("core-scenario-value").value=core.valueProposition;q("core-scenario-objective").value=core.objective;q("core-scenario-cta").value=core.cta;q("core-scenario-tone").value=core.tone||'consultative';q("core-scenario-language").value=core.language||'auto';status.textContent=core.status==='approved'?'Approved default':core.status==='needs_review'?'Review after profile change':'Review required';status.dataset.status=core.status;const select=q("campaign-preset-select");select.innerHTML='<option value="">Core Outreach Scenario</option>'+studio.presets.map(item=>`<option value="${esc(item.id)}" ${item.id===studio.selectedPresetId?'selected':''}>${esc(item.segment)}</option>`).join('');q("campaign-segment").value=studio.selectedPresetId?active.segment:'';q("campaign-tone").value=active.tone||'consultative';const emailLanguage=LeadIntelContentLanguage.EMAIL_LANGUAGES?.[active.language]||active.language||'Auto';q("campaign-active-summary").innerHTML=`<span>Active campaign</span><strong>${esc(active.segment||'Core Outreach Scenario')}</strong><small>${esc(active.offer||'Offer not yet defined')} · ${esc(active.buyerRole||'Buyer role not yet defined')} · Email: ${esc(emailLanguage)}</small>`;}

function renderSelector(){const list=pipeline();const select=q("outreach-company-select");if(!select)return;select.innerHTML=list.length?list.map(item=>`<option value="${esc(item.domain)}" ${item.domain===outreach.selectedDomain?"selected":""}>${esc(item.company)} · ${esc(item.stage||"Selected for Buyers")} · ${item.score?.total||0}/100</option>`).join(""):'<option value="">No saved companies yet</option>';const buyerCount=window.LeadIntelDiscoveryUI?.readyBuyerCount?.(list)||0;const activeJourneyStage=Number(readJson(DISCOVERY_META_KEY).activeJourneyStage)||4;const nextState={pipelineCount:list.length,buyerCount,focus:activeJourneyStage===5?"buyers":"companies"};const gate=q("continue-to-outreach");if(gate){const action=window.LeadIntelNextAction?.forStage(5,nextState)||{label:list.length?"Continue to Buyers →":"Save a Company First",enabled:Boolean(list.length),journeyStage:5};gate.disabled=!action.enabled;gate.setAttribute("aria-disabled",String(!action.enabled));gate.textContent=action.label;window.LeadIntelNextAction?.applyStageVisibility?.(document,5,nextState);}q("build-opportunity-dossier").disabled=!list.length;}
function renderDossier(){const item=currentItem();const workspace=q("dossier-workspace");if(!workspace)return;if(!item?.dossier){workspace.hidden=true;q("dossier-research-status").textContent=item?.researchStatus==="running"?"Researching official and public sources…":pipeline().length?"Choose a saved company and build its dossier.":"No saved company yet. Use Discovery to create a pipeline opportunity when ready.";q("outreach-status").textContent=pipeline().length?"Ready":"Waiting for opportunity";return;}workspace.hidden=false;const d=item.dossier;q("dossier-research-status").textContent=item.researchStatus==="partial"?`Dossier built · ${d.evidence.length} sources · some research unavailable`:item.researchStatus==="error"?"Dossier built conservatively from existing evidence; deep research was unavailable.":`Dossier ready · ${d.evidence.length} evidence sources`;
  q("dossier-why-now").textContent=d.whyNow;q("dossier-offer").textContent=d.recommendedOffer||"Not yet defined";q("dossier-confidence").textContent=`Discovery confidence: ${d.confidence||"Low"}`;
  q("dossier-buyers").innerHTML=d.buyerRoles?.length?d.buyerRoles.map(role=>`<span>${esc(role)}</span>`).join(""):'<span>Not yet defined</span>';
  q("dossier-evidence").innerHTML=d.evidence?.length?d.evidence.map(e=>`<a href="${esc(e.url)}" target="_blank" rel="noopener"><span class="evidence-type ${esc(e.sourceType).toLowerCase()}">${esc(e.sourceType)}</span><strong>${esc(e.title||e.url)}</strong><small>${esc(e.description||e.text).slice(0,230)}</small>${e.date?`<em>${esc(e.date)}</em>`:""}</a>`).join(""):'<div class="market-empty">No additional evidence was available. LeadIntel did not invent replacement facts.</div>';
  q("dossier-hypotheses").innerHTML=d.hypotheses?.length?d.hypotheses.map(h=>`<div>${esc(h)}</div>`).join(""):'<div>No commercial hypothesis added without evidence.</div>';
  const triggerSelect=q('outreach-trigger-select');if(triggerSelect){triggerSelect.innerHTML='<option value="">Choose a source to review</option>'+(d.evidence||[]).map(source=>`<option value="${esc(source.url)}" ${d.selectedTrigger?.url===source.url?'selected':''}>${esc(source.title||source.url)} · ${esc(source.date||'date unknown')}</option>`).join('');previewSelectedTrigger();q('trigger-script-status').textContent=d.selectedTrigger?`Tracked trigger · reviewed ${d.selectedTrigger.reviewedAt} · source date ${d.selectedTrigger.sourceDate||'unknown'}`:'No reviewed trigger selected.';}
  const contact=q("outreach-contact-select");contact.innerHTML=d.people?.length?d.people.map(p=>`<option value="${esc(p.id)}" ${p.id===item.selectedPersonId?"selected":""}>${esc(p.name)} · ${esc(p.title)}</option>`).join(""):`<option value="">Role-based outreach · no named contact</option>`;
  q("outreach-tone").value=item.drafts?.tone||"consultative";q("outreach-email-subject").value=item.drafts?.emailSubject||"";q("outreach-email-body").value=item.drafts?.emailBody||"";q("outreach-linkedin").value=item.drafts?.linkedinMessage||"";q("outreach-call-opener").value=item.drafts?.callOpener||"";q("outreach-follow-up").value=item.drafts?.followUp||"";q("outreach-objection-reply").value=item.drafts?.objectionReply||"";q("outreach-email-language").value=item.localizationStatus==='confirmation_required'?'':(item.localizationProvenance?.language||item.campaignScenario?.resolvedLanguage||(['en','lv'].includes(item.campaignScenario?.language)?item.campaignScenario.language:''));
  [q("outreach-contact-select"),q("outreach-tone"),q("outreach-email-language"),q("outreach-email-subject"),q("outreach-email-body"),q("outreach-linkedin"),q("outreach-call-opener"),q("outreach-follow-up"),q("outreach-objection-reply")].forEach(el=>{if(el)el.disabled=Boolean(item.approved)||item.localizationStatus==='running';});
  q("regenerate-outreach").disabled=item.localizationStatus==='running';q("regenerate-outreach").textContent=item.localizationStatus==='running'?"Localizing…":item.reapprovalRequired?"Regenerate & reapprove":item.approved?"Regenerate & reapprove":"Regenerate all";q("approve-outreach").disabled=Boolean(item.approved)||Boolean(item.localizationApprovalBlocked);q("approve-outreach").textContent=item.localizationStatus==='running'?"Localizing…":item.localizationStatus==='confirmation_required'?"Confirm email language":item.localizationStatus==='error'?"Localization required":item.reapprovalRequired?"Review & reapprove":item.approved?"Approved ✓":"Approve campaign package";q("preview-approved-email").hidden=!item.approved;q("mark-contacted").disabled=!item.approved||Boolean(item.contactedAt);q("mark-contacted").textContent=item.contactedAt?"Contacted ✓":"Mark contacted";
  if(!item.approved)q("outreach-email-preview").hidden=true;
  q("outreach-approval-label").textContent=item.localizationApprovalBlocked?"Email language must be resolved before approval":item.reapprovalRequired?"Reapproval required — branded email changed or could not be verified":item.contactedAt?`Contacted · ${new Date(item.contactedAt).toLocaleString()}`:item.approved?`Approved · ${new Date(item.approvedAt).toLocaleString()}`:"Draft not approved";q("outreach-approval-help").textContent=item.localizationApprovalBlocked?(item.localizationMessage||"Confirm the local email language and regenerate the message."):item.localizationProvenance?.language?`${item.localizationMessage||'Language ready'} Approval freezes this ${LeadIntelContentLanguage.EMAIL_LANGUAGES?.[item.localizationProvenance.language]||item.localizationProvenance.language} version and moves the opportunity to Ready for Outreach.`:item.reapprovalRequired?"Sending is blocked. Regenerate this package, review the new email, then approve it again.":"Approval freezes the current email identity and moves the opportunity to Ready for Outreach. Sending remains a separate explicit action in Delivery.";q("outreach-status").textContent=item.localizationStatus==='running'?"Localizing":item.localizationStatus==='error'?"Localization required":item.localizationStatus==='confirmation_required'?"Confirm language":item.reapprovalRequired?"Reapproval required":item.contactedAt?"Contacted":item.approved?"Approved":"Draft";q("outreach-status").classList.toggle("approved",Boolean(item.approved));
  document.querySelectorAll('#dossier-workspace .script-card').forEach(card=>{card.hidden=item.channel==='linkedin'&&!card.querySelector('#outreach-linkedin');});
  if(item.channel==='linkedin'){
    q('outreach-status').textContent='LinkedIn draft';q('regenerate-outreach').textContent='Regenerate LinkedIn draft';
    q('approve-outreach').disabled=true;q('approve-outreach').textContent='LinkedIn draft · review & copy';
    q('outreach-approval-label').textContent='LinkedIn direct message · draft only';q('outreach-approval-help').textContent='Review and edit the LinkedIn message, then copy it. Email verification is not required. No message is sent from this step.';
  }

}
function localizeVisibleItem(){const item=currentItem();if(!item||item.approved||item.channel==='linkedin')return;const main=mainState();const localized=LeadIntelOutreach.localizeGeneratedItem(item,selectedCandidate()||item.dossier,main.profile||{},main.market||{},contentLanguage());if(localized!==item)upsertItem(localized);}
function renderAll(){ensureSelection();renderCampaignStudio();localizeVisibleItem();renderSelector();renderDossier();}
function bindOutreach(){
  q('outreach-trigger-select')?.addEventListener('change',previewSelectedTrigger);q('use-reviewed-trigger')?.addEventListener('click',useReviewedTrigger);q('load-trigger-alerts')?.addEventListener('click',loadTriggerAlerts);q('save-trigger-scripts')?.addEventListener('click',()=>void saveScriptPackage().catch(error=>toast(error.message)));q('restore-trigger-scripts')?.addEventListener('click',()=>void restoreScriptPackage().catch(error=>toast(error.message)));

  q("outreach-contact-select")?.addEventListener("change",()=>void regenerateDrafts().catch(error=>toast(error.message)));
  q("continue-to-outreach")?.addEventListener("click",continueFromCompanies);q("back-to-discovery")?.addEventListener("click",backToDiscovery);q("save-core-scenario")?.addEventListener("click",saveCoreScenario);q("regenerate-core-scenario")?.addEventListener("click",regenerateCoreScenario);q("save-campaign-preset")?.addEventListener("click",saveCampaignPreset);q("campaign-preset-select")?.addEventListener("change",selectCampaignPreset);q("outreach-company-select")?.addEventListener("change",e=>{cancelPendingScriptGeneration();outreach.selectedDomain=e.target.value;saveOutreach();renderDossier();});q("build-opportunity-dossier")?.addEventListener("click",buildDossier);q("regenerate-outreach")?.addEventListener("click",regenerateDrafts);q("translate-outreach")?.addEventListener("click",confirmOutreachLanguage);q("approve-outreach")?.addEventListener("click",approveOutreach);q("preview-approved-email")?.addEventListener("click",()=>renderApprovedPreview("html"));q("outreach-preview-html")?.addEventListener("click",()=>renderApprovedPreview("html"));q("outreach-preview-text")?.addEventListener("click",()=>renderApprovedPreview("text"));q("mark-contacted")?.addEventListener("click",markContacted);q("dossier-workspace")?.addEventListener("click",e=>{const btn=e.target.closest("[data-copy-field]");if(btn)copyField(btn.dataset.copyField);});q("reset-workspace")?.addEventListener("click",()=>setTimeout(()=>{if(!localStorage.getItem(MAIN_STORAGE_KEY))localStorage.removeItem(OUTREACH_STORAGE_KEY);},0));
  window.addEventListener("leadintel:module-opened",event=>{if(Number(event.detail?.step)!==6)return;ensureSelection();renderAll();});
  window.addEventListener("leadintel:website-activated",()=>{
    scriptGenerationRequest++;outreach=LeadIntelOutreach.normalizeOutreachState({});
    localStorage.removeItem(OUTREACH_STORAGE_KEY);
    localStorage.removeItem(DELIVERY_STORAGE_KEY);
    renderAll();
  });
}
function loadDeliveryModules(){
  if(document.querySelector('script[data-delivery-engine]'))return;
  const engine=document.createElement("script");engine.src=`delivery-engine.js?v=${LANGUAGE_ASSET_VERSION}`;engine.dataset.deliveryEngine="true";
  engine.addEventListener("load",()=>{if(document.querySelector('script[data-delivery-ui]'))return;const ui=document.createElement("script");ui.type="module";ui.src=`delivery-ui.js?v=${LANGUAGE_ASSET_VERSION}&delivery-modes=2`;ui.dataset.deliveryUi="true";document.body.appendChild(ui);});
  document.body.appendChild(engine);
}
function initOutreach(){injectOutreachUI();bindOutreach();renderAll();if(mainState().step===6)showOutreachStep();loadDeliveryModules();}
initOutreach();
import './content-variants.js?v=20260929-public-first-email-v1';

window.addEventListener('leadintel:commercial-context-changed',()=>{cancelPendingScriptGeneration();outreach=LeadIntelOutreach.normalizeOutreachState(readJson(OUTREACH_STORAGE_KEY));renderAll();});

async function openBuyerScripts(choice){
 if(!choice||choice.workspaceId!==crmBridge()?.workspace?.id)return false;
 const candidate=pipeline().find(p=>p.domain===choice.domain);if(!candidate)return false;
 const person=candidate.people?.find(p=>p.id===choice.personId);if(!person?.kept)return false;
 let contacts=[],companyRecord=null;
 if(candidate.crmId){const detail=await crmBridge().getCrmCompany(candidate.crmId);companyRecord=detail;contacts=detail?.ok?detail.contacts:[];}
 if(!candidate.crmId){const result=await crmBridge().listCrmCompanies({q:choice.domain,limit:20});const company=(result.companies||[]).find(c=>c.normalized_domain===choice.domain);if(company){const record=await crmBridge().getCrmCompany(company.id);companyRecord=record;contacts=record.ok?record.contacts:[];}}
 if(choice.channel==='linkedin'){
   if(!window.LeadIntelDiscovery?.confirmedLinkedInBuyer(person,candidate,choice,crmBridge()?.workspace?.id))return false;
   if(!companyRecord?.ok||['suppressed','archived'].includes(companyRecord.company?.lifecycle_status))return false;
   if(!window.LeadIntelDiscovery.confirmedLinkedInBuyer(person,candidate,choice,crmBridge()?.workspace?.id))return false;
   cancelPendingScriptGeneration();outreach.selectedDomain=choice.domain;
   const old=currentItem();
   if(old&&(old.selectedPersonId!==choice.personId||old.channel!=='linkedin'))upsertItem(LeadIntelOutreach.invalidateOutreachApproval({...old,channel:'linkedin',selectedPersonId:choice.personId,dossier:null,drafts:{},researchStatus:'idle'}));
   handoffContact={domain:choice.domain,personId:choice.personId,channel:'linkedin',contact:{name:person.publicName||person.name,linkedin_url:person.linkedinConfirmedUrl}};
   saveOutreach();showOutreachStep();
   if(!currentItem()?.dossier||!currentItem()?.drafts?.linkedinMessage||currentItem()?.contextNeedsRefresh)await buildDossier();
   q('outreach-linkedin')?.scrollIntoView?.({block:'center',behavior:'smooth'});q('outreach-linkedin')?.focus?.();return true;
 }
 const contact=(contacts||[]).find(c=>c.id===choice.contactId&&(!window.LeadIntelContactPolicy&&String(c.email_status||'').toLowerCase()==='verified'||window.LeadIntelContactPolicy?.accepted(c,choice.domain,window.LeadIntelBuyerConfirmationPolicy?.level?.()||window.LeadIntelServiceSettings?.confirmationLevel?.()))&&String(c.work_email||c.normalized_email||'').toLowerCase().endsWith('@'+choice.domain));if(!contact)return false;
 cancelPendingScriptGeneration();outreach.selectedDomain=choice.domain;
 const old=currentItem();if(old&&(old.selectedPersonId!==choice.personId||old.channel==='linkedin'))upsertItem(LeadIntelOutreach.invalidateOutreachApproval({...old,channel:'email',selectedPersonId:choice.personId,dossier:null,drafts:{},researchStatus:'idle'}));
 handoffContact={domain:choice.domain,personId:choice.personId,channel:'email',contact};saveOutreach();showOutreachStep();return true;
}
window.addEventListener('leadintel:buyer-for-scripts',event=>{void openBuyerScripts(event.detail).catch(()=>toast('Unable to load the selected CRM contact.'));});
if(readJson(DISCOVERY_META_KEY).scriptBuyer&&(mainState().step===6||readJson(DISCOVERY_META_KEY).visibleStep===6))void openBuyerScripts(readJson(DISCOVERY_META_KEY).scriptBuyer).catch(()=>{});

window.addEventListener('leadintel:server-ready',()=>{const choice=readJson(DISCOVERY_META_KEY).scriptBuyer;if(choice?.channel==='linkedin'&&(mainState().step===6||readJson(DISCOVERY_META_KEY).visibleStep===6))void openBuyerScripts(choice).catch(()=>toast('Saved LinkedIn selection needs review.'));});
