(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;if(root)root.LeadIntelResearchReport=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  'use strict';
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const url=value=>{try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}};
  const clone=value=>JSON.parse(JSON.stringify(value,(key,item)=>typeof item==='string'&&['text','description'].includes(key)?item.slice(0,900):item));
  const modes={quick:'Quick Overview',deep:'Market Research',intelligence:'Deep Analysis'};
  function snapshot(main={},id=`report-${Date.now()}`){const m=main.market||{};return clone({id,createdAt:new Date().toISOString(),researchedAt:m.lastResearchAt||'',company:main.profile?.companyName||'Your company',website:main.profile?.website||main.website||'',markets:main.profile?.targetMarkets||'',offers:main.profile?.priorityOffers||'',customer:main.profile?.idealCustomer||'',mode:m.researchMode||'quick',status:m.researchStatus||'idle',stale:m.researchContextStale===true,quality:m.researchQuality||null,providers:m.researchSourceStatus||{},errors:m.researchErrors||[],verification:m.researchVerification||{},sources:m.researchResults||[],opportunities:m.opportunities||[],conditions:m.marketConditions||null,signals:(m.signals||[]).filter(x=>x.active!==false).map(x=>({name:x.name,keywords:x.keywords}))});}
  function normalize(history){return (Array.isArray(history)?history:[]).filter(x=>x&&typeof x.id==='string'&&Array.isArray(x.sources)).slice(0,10).map(clone);}
  function append(history,report){return normalize([report,...normalize(history).filter(x=>x.id!==report.id)]);}
  const css=`*{box-sizing:border-box}body{margin:0;background:#f1f4f2;color:#172d27;font:15px/1.65 Arial,sans-serif}.report{max-width:1000px;margin:24px auto;background:white;padding:48px;border-radius:16px}header{border-bottom:3px solid #12614f;padding-bottom:24px}.eyebrow{color:#12614f;letter-spacing:2px;font-size:12px;text-transform:uppercase}h1{font-size:34px;line-height:1.2}h2{margin-top:32px;font-size:22px}h3{font-size:17px}small,.muted{color:#596b65}.metrics{display:flex;gap:24px;flex-wrap:wrap;margin:24px 0}.metrics strong{display:block;font-size:23px}.notice{padding:14px;background:#fff6df;border-left:4px solid #ac812d}article{border:1px solid #dbe4df;border-radius:10px;padding:18px;margin:12px 0}a{color:#12614f;overflow-wrap:anywhere}li{margin-bottom:8px}.source{break-inside:avoid}.source p{white-space:pre-wrap}.toolbar{position:sticky;top:0;background:white;border-bottom:1px solid #dbe4df;padding:12px;display:flex;gap:8px;flex-wrap:wrap}button{padding:10px 16px;border:1px solid #12614f;border-radius:8px;background:white;color:#12614f;cursor:pointer}.primary{background:#12614f;color:white}footer{border-top:1px solid #dbe4df;margin-top:32px;padding-top:20px}@page{size:A4;margin:16mm}@media print{body{background:white;font-size:10pt}.report{margin:0;padding:0;max-width:none;border-radius:0}.toolbar{display:none}h1{font-size:25pt}h2,h3{break-after:avoid}article{break-inside:avoid}a{color:#172d27}a.source-link:after{content:' (' attr(href) ')';font-size:9pt}.source p{max-height:none}}@media(max-width:650px){.report{margin:0;padding:24px}h1{font-size:27px}}`;
  function body(r){const sources=r.sources||[];const citation=s=>{const index=sources.findIndex(x=>x.url===s.url);return index>=0?`<a href="#source-${index+1}">[${index+1}]</a>`:'';};
    const gaps=[...(r.quality?.gaps||[]),...(r.errors||[]).map(x=>`${x.provider||'Source'}: ${x.message||'Unavailable'}`),...(r.verification?.status==='unavailable'?[`Verification: ${r.verification.reason||'Unavailable'}`]:[]),...(r.stale?['This report retains earlier evidence. Context needs review before reuse.']:[])];
    const findings=sources.slice(0,r.mode==='quick'?5:10).map(s=>`<article><h3>${esc(s.title||'Source finding')} ${citation(s)}</h3><p>${esc(String(s.description||s.text||'No readable excerpt saved.').slice(0,600))}</p><small>Source excerpt · ${s.extractedAt?'Page extracted':'Search result only'} · ${esc(s.date||'Publication date unknown')}</small></article>`).join('');
    const opportunities=(r.opportunities||[]).filter(x=>!x.profileOnly&&x.evidence?.length).map(o=>`<article><h3>${esc(o.title||o.market)}</h3><small>AI hypothesis · ${esc(o.confidence||'Unknown')} confidence · ${esc(o.score?.total??'Not scored')}/100</small><p>${esc(o.hypothesis)}</p><p>${o.evidence.map(citation).join(' ')}</p></article>`).join('');
    const conditions=r.conditions?['direction','competition','funding','pricing','demand'].map(key=>r.conditions[key]?.summary?`<article><h3>${esc(key)}</h3><p>${esc(r.conditions[key].summary)}</p><p>${(r.conditions[key].evidence||[]).map(citation).join(' ')}</p></article>`:'').join(''):'';
    return `<main class="report"><header><span class="eyebrow">LeadIntel · Market intelligence</span><h1>${esc(modes[r.mode]||'Research report')}</h1><h2>${esc(r.company)}</h2><p>${esc(r.markets)} · Evidence date: ${esc(r.researchedAt||'Unknown')}</p><p class="muted">Snapshot: ${esc(r.createdAt)} · ${esc(r.status)} coverage</p></header><div class="metrics"><div><strong>${sources.length}</strong>Saved sources</div><div><strong>${sources.filter(x=>x.extractedAt).length}</strong>Pages extracted</div><div><strong>${esc(r.quality?.confidence||'Not assessed')}</strong>Evidence confidence</div></div>${r.status!=='complete'||r.stale?'<p class="notice">Partial or unverified coverage. Source count is not proof of market demand.</p>':''}<h2>Research brief</h2><p><b>Priority offers:</b> ${esc(r.offers||'Not specified')}</p><p><b>Target customers:</b> ${esc(r.customer||'Not specified')}</p><h2>Key findings</h2><p class="muted">Excerpts from collected sources, not independently confirmed facts. See each source’s extraction status.</p>${findings||'<p>No usable evidence was saved.</p>'}<h2>Commercial implications</h2><p class="muted">AI hypotheses and guidance—not verified buying intent. Review before activating Strategy.</p>${opportunities||'<p>No evidence-backed commercial hypothesis available.</p>'}${conditions}<h3>Selected buying signals</h3><ul>${(r.signals||[]).map(x=>`<li>${esc(x.name)}</li>`).join('')||'<li>None selected</li>'}</ul><h2>Coverage and limitations</h2><ul>${gaps.map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No recorded coverage gaps. This does not guarantee factual accuracy or exhaustive coverage.</li>'}</ul><p>${Object.entries(r.providers||{}).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · ')}</p><h2>Sources</h2>${sources.map((s,i)=>`<article class="source" id="source-${i+1}"><h3>[${i+1}] ${esc(s.title||'Source')}</h3>${url(s.url)?`<a class="source-link" href="${esc(url(s.url))}" target="_blank" rel="noopener">${esc(s.url)}</a>`:'<p>Invalid source URL</p>'}<p>${esc(String(s.description||s.text||'').slice(0,900))}</p><small>${esc(s.date||'Publication date unknown')} · ${s.extractedAt?`Extracted by ${esc(s.extractedBy||'provider')} at ${esc(s.extractedAt)}`:'Search snippet—not page verified'} · ${esc(s.verification?.relevance?`AI cross-check: ${s.verification.relevance} relevance`:'No AI cross-check recorded')}</small></article>`).join('')}<footer><b>Next step: Review in Strategy.</b> Select customer segments, markets and signals. Company discovery separately verifies company fit and buying evidence; this report does not approve outreach.<p class="muted">Private workspace snapshot. Review before sharing. No API keys, contacts or account settings are included.</p></footer></main>`;
  }
  function documentHtml(r){return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(r.company)} · Research report</title><style>${css}</style>${body(r)}</html>`;}
  function install({getState,save,onStrategy}){let current=null,previousFocus=null;const d=document;const dialog=d.createElement('dialog');dialog.id='research-report-dialog';dialog.setAttribute('aria-label','Market research report');dialog.style.cssText='width:min(1100px,96vw);height:92vh;padding:0;border:0;border-radius:16px;background:#f1f4f2';dialog.innerHTML='<div class="report-actions" style="padding:12px;display:flex;gap:8px;flex-wrap:wrap;background:white"><button data-report-print>Print / Save PDF</button><button data-report-download>Download to share</button><button data-report-strategy>Review in Strategy</button><button data-report-close style="margin-left:auto">Close</button></div><iframe title="Research report" style="border:0;width:100%;height:calc(100% - 64px)"></iframe>';d.body.appendChild(dialog);const frame=dialog.querySelector('iframe');
    function open(r){if(!r)return;current=clone(r);previousFocus=d.activeElement;frame.srcdoc=documentHtml(current);if(!dialog.open)dialog.showModal();dialog.querySelector('[data-report-close]').focus();}
    dialog.querySelector('[data-report-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>previousFocus?.focus?.());
    dialog.querySelector('[data-report-print]').onclick=()=>{frame.contentWindow.focus();frame.contentWindow.print();};
    dialog.querySelector('[data-report-download]').onclick=()=>{const blob=new Blob([documentHtml(current)],{type:'text/html'});const link=d.createElement('a');const objectUrl=URL.createObjectURL(blob);link.href=objectUrl;link.download=`LeadIntel-${String(current.company).replace(/[^a-z0-9-]/gi,'-')}-${current.id}.html`;link.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);};
    dialog.querySelector('[data-report-strategy]').onclick=()=>{dialog.close();onStrategy();};
    function render(){const m=getState().market||{};const history=normalize(m.researchReports);const latest=history[0]||(m.researchResults?.length?snapshot(getState(),'legacy-current'):null);for(const host of d.querySelectorAll('[data-research-reports]')){host.innerHTML=latest?'<button type="button" data-report-latest>View report</button><details><summary>Saved reports ('+history.length+')</summary>'+history.map((r,i)=>`<p><button type="button" data-report-index="${i}">${esc(modes[r.mode]||r.mode)} · ${esc(r.researchedAt||r.createdAt)} · ${esc(r.status)} · ${r.sources.length} sources</button></p>`).join('')+'</details><small>Saved with your workspace · Print / Save PDF or download to share</small>':'';host.querySelector('[data-report-latest]')?.addEventListener('click',()=>open(latest));host.querySelectorAll('[data-report-index]').forEach(button=>button.onclick=()=>open(history[Number(button.dataset.reportIndex)]));}}
    return {render,capture(){const main=getState();const report=snapshot(main);main.market.researchReports=append(main.market.researchReports,report);save();render();},openLatest(){const m=getState().market||{};open(normalize(m.researchReports)[0]||snapshot(getState()));}};
  }
  return {snapshot,normalize,append,body,documentHtml,install};
});
