(function(root){
  'use strict';
  const API_BASE='https://leadintel-api.edgars-7e7.workers.dev';
  const ASSET_VERSION='20260824-premium';
  const asset=path=>`${path}?v=${ASSET_VERSION}`;
  const KEYS={main:'leadintel_customer_v2_state',discovery:'leadintel_customer_v2_discovery',outreach:'leadintel_customer_v2_outreach',delivery:'leadintel_customer_v2_delivery',meta:'leadintel_customer_v2_discovery_meta'};
  const WORKSPACE_KEY='leadintel_customer_v2_workspace';
  const HYDRATION_KEY='leadintel_customer_v2_server_hydration';
  const CONFLICT_KEY='leadintel_customer_v2_server_conflict';
  const DIRTY_KEY='leadintel_customer_v2_server_dirty';
  let saveTimer=null;let suppress=false;let initialized=false;
  const bridge={session:null,workspaces:[],workspace:null,stateVersion:0,gmail:{configured:false,connected:false,email:'',role:''},status:'local',conflict:false,conflictState:null,saveNow,refreshGmailStatus,syncReplies,sendGmail,connectGmail,disconnectGmail,signIn,signOut,selectWorkspace,resolveConflictKeepLocal,resolveConflictUseServer};
  root.LeadIntelServerBridge=bridge;

  function parse(key){try{return JSON.parse(localStorage.getItem(key)||'{}');}catch{return {};}}
  function bundle(){return {main:parse(KEYS.main),discovery:parse(KEYS.discovery),outreach:parse(KEYS.outreach),delivery:parse(KEYS.delivery),meta:{discovery:parse(KEYS.meta)}};}
  function isEmptyObject(value){return !value||typeof value!=='object'||Object.keys(value).length===0;}
  function hasLocalData(value=bundle()){return ['main','discovery','outreach','delivery'].some(key=>!isEmptyObject(value[key]));}
  function readDirtyLocalState(){try{const value=JSON.parse(localStorage.getItem(DIRTY_KEY)||'null');return value&&typeof value==='object'?value:null;}catch{return null;}}
  function hasDirtyLocalState(){const value=readDirtyLocalState();return Boolean(value&&bridge.workspace&&value.workspace_id===bridge.workspace.id);}
  function markDirtyLocalState(){if(!bridge.workspace)return;const current=readDirtyLocalState();if(current&&current.workspace_id===bridge.workspace.id)return;localStorage.setItem(DIRTY_KEY,JSON.stringify({workspace_id:bridge.workspace.id,base_version:bridge.stateVersion,updated_at:Date.now()}));}
  function rebaseDirtyLocalState(){if(!bridge.workspace)return;localStorage.setItem(DIRTY_KEY,JSON.stringify({workspace_id:bridge.workspace.id,base_version:bridge.stateVersion,updated_at:Date.now()}));}
  function clearDirtyLocalState(){const current=readDirtyLocalState();if(!current||!bridge.workspace||current.workspace_id===bridge.workspace.id)localStorage.removeItem(DIRTY_KEY);}
  function endpoint(path){return `${API_BASE}${path}`;}
  async function api(path,options={}){const response=await fetch(endpoint(path),{credentials:'include',headers:{'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})},...options});const payload=await response.json().catch(()=>({}));return {response,payload};}
  function returnTo(){const url=new URL(location.href);url.searchParams.delete('auth');url.searchParams.delete('gmail');url.searchParams.delete('reason');url.searchParams.delete('workspace_id');return url.toString();}
  function setStatus(text,kind=''){bridge.status=kind||text;const existing=document.querySelector('.autosave');if(existing){existing.innerHTML=`<i></i>${text}`;existing.dataset.serverStatus=kind||'';}const status=document.getElementById('server-sync-status');if(status){status.textContent=text;status.dataset.state=kind||'';}}
  function showToast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),3000);}
  function injectCss(){if(document.querySelector('link[data-leadintel-asset="server-css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=asset('server.css');link.dataset.leadintelAsset='server-css';document.head.appendChild(link);}
  function injectAccountUi(){
    const actions=document.querySelector('.top-actions');if(!actions||document.getElementById('server-account'))return;
    actions.insertAdjacentHTML('afterbegin','<div class="server-account" id="server-account"><button class="ghost-btn server-signin" id="server-google-signin" type="button">Sign in with Google</button><select id="server-workspace-select" aria-label="LeadIntel workspace" hidden></select><span id="server-account-label" hidden></span><span class="server-sync" id="server-sync-status">Local workspace</span><div class="server-conflict-actions" id="server-conflict-actions" hidden><button class="ghost-btn" id="server-use-server" type="button">Use server version</button><button class="ghost-btn" id="server-keep-local" type="button">Keep my local changes</button></div><button class="server-signout" id="server-signout" type="button" hidden>Sign out</button></div>');
    document.getElementById('server-google-signin')?.addEventListener('click',signIn);document.getElementById('server-signout')?.addEventListener('click',signOut);document.getElementById('server-workspace-select')?.addEventListener('change',e=>selectWorkspace(e.target.value));document.getElementById('server-use-server')?.addEventListener('click',resolveConflictUseServer);document.getElementById('server-keep-local')?.addEventListener('click',resolveConflictKeepLocal);
  }
  function renderConflictActions(){const actions=document.getElementById('server-conflict-actions');if(actions)actions.hidden=!bridge.conflict;}
  function renderAccount(){injectAccountUi();const signin=document.getElementById('server-google-signin');const select=document.getElementById('server-workspace-select');const label=document.getElementById('server-account-label');const signout=document.getElementById('server-signout');if(!signin)return;
    const authenticated=Boolean(bridge.session?.authenticated);signin.hidden=authenticated;select.hidden=!authenticated||bridge.workspaces.length<2;label.hidden=!authenticated;signout.hidden=!authenticated;
    if(authenticated){label.textContent=bridge.session.user?.name||bridge.session.user?.email||'Signed in';select.innerHTML=bridge.workspaces.map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===bridge.workspace?.id?'selected':''}>${escapeHtml(item.name)} · ${escapeHtml(item.role)}</option>`).join('');}renderConflictActions();
  }
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function patchStorage(){if(Storage.prototype.__leadintelServerPatched)return;const set=Storage.prototype.setItem;const remove=Storage.prototype.removeItem;Storage.prototype.setItem=function(key,value){set.call(this,key,value);if(this===localStorage&&Object.values(KEYS).includes(key)&&!suppress){markDirtyLocalState();scheduleSave();}};Storage.prototype.removeItem=function(key){remove.call(this,key);if(this===localStorage&&Object.values(KEYS).includes(key)&&!suppress){markDirtyLocalState();scheduleSave();}};Storage.prototype.__leadintelServerPatched=true;}
  function scheduleSave(){if(!bridge.session?.authenticated||!bridge.workspace||bridge.conflict)return;markDirtyLocalState();clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveNow(),1200);}
  function applyPayload(payload){suppress=true;try{const p=payload&&typeof payload==='object'?payload:{};for(const key of ['main','discovery','outreach','delivery']){if(p[key]&&typeof p[key]==='object')localStorage.setItem(KEYS[key],JSON.stringify(p[key]));else localStorage.removeItem(KEYS[key]);}if(p.meta?.discovery)localStorage.setItem(KEYS.meta,JSON.stringify(p.meta.discovery));else localStorage.removeItem(KEYS.meta);}finally{suppress=false;}}
  async function fetchSession(){const {response,payload}=await api('/api/session');bridge.session=response.ok?payload:{authenticated:false};return bridge.session;}
  async function fetchWorkspaces(){const {response,payload}=await api('/api/workspaces');bridge.workspaces=response.ok&&Array.isArray(payload.workspaces)?payload.workspaces:[];return bridge.workspaces;}
  async function fetchWorkspaceState(){if(!bridge.workspace)return null;const {response,payload}=await api(`/api/customer/state?workspace_id=${encodeURIComponent(bridge.workspace.id)}`);if(!response.ok)throw new Error(payload.error||'Unable to load workspace state');bridge.stateVersion=Number(payload.version)||0;return payload;}
  function pickWorkspace(){const preferred=localStorage.getItem(WORKSPACE_KEY);bridge.workspace=bridge.workspaces.find(item=>item.id===preferred)||bridge.workspaces[0]||null;if(bridge.workspace)localStorage.setItem(WORKSPACE_KEY,bridge.workspace.id);}
  function enterConflict(state,message){bridge.conflict=true;bridge.conflictState=state&&typeof state==='object'?state:null;renderConflictActions();setStatus('Sync conflict · local changes preserved','error');showToast(message||'Server state changed in another session. Your local changes are still safe in this browser.');}
  async function hydrateAuthenticated(){const state=await fetchWorkspaceState();const marker=`${bridge.workspace.id}:${state.version}`;const dirty=readDirtyLocalState();if(hasDirtyLocalState()){if(Number(dirty.base_version)!==Number(state.version)){enterConflict(state,'LeadIntel preserved your local changes because the server workspace changed in another session.');return true;}setStatus('Unsynced changes · retrying','saving');scheduleSave();return true;}if(state.version>0&&sessionStorage.getItem(HYDRATION_KEY)!==marker){applyPayload(state.payload);clearDirtyLocalState();sessionStorage.setItem(HYDRATION_KEY,marker);setStatus('Synced to LeadIntel','synced');location.reload();return false;}if(state.version===0&&hasLocalData()){markDirtyLocalState();setStatus('Unsynced changes · saving','saving');scheduleSave();return true;}setStatus('Synced to LeadIntel','synced');return true;}
  async function init(){if(initialized)return;initialized=true;injectCss();injectAccountUi();patchStorage();const conflictNote=sessionStorage.getItem(CONFLICT_KEY);if(conflictNote){sessionStorage.removeItem(CONFLICT_KEY);showToast(conflictNote);}
    try{await fetchSession();if(!bridge.session?.authenticated){setStatus('Local workspace · Sign in to sync','local');renderAccount();root.dispatchEvent(new CustomEvent('leadintel:server-ready',{detail:bridge}));return;}await fetchWorkspaces();pickWorkspace();renderAccount();if(!bridge.workspace){setStatus('Signed in · No workspace','error');return;}const stay=await hydrateAuthenticated();if(!stay)return;await refreshGmailStatus();root.dispatchEvent(new CustomEvent('leadintel:server-ready',{detail:bridge}));}catch(cause){console.warn('LeadIntel server bridge:',cause);setStatus('Local cache · Server unavailable','error');renderAccount();root.dispatchEvent(new CustomEvent('leadintel:server-ready',{detail:bridge}));}
  }
  async function saveNow(){if(!bridge.session?.authenticated||!bridge.workspace||bridge.conflict)return {saved:false};clearTimeout(saveTimer);markDirtyLocalState();setStatus('Saving to LeadIntel…','saving');const payload={schema_version:1,version:bridge.stateVersion,payload:bundle()};const {response,payload:result}=await api(`/api/customer/state?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'PUT',body:JSON.stringify(payload)});
    if(response.status===409){bridge.stateVersion=Number(result.current?.version)||bridge.stateVersion;sessionStorage.setItem(CONFLICT_KEY,'Server state changed in another session. Your local changes were preserved and were not overwritten.');enterConflict(result.current);return {saved:false,conflict:true};}
    if(!response.ok){setStatus('Sync failed · Local cache safe','error');throw new Error(result.error||'Workspace save failed');}bridge.stateVersion=Number(result.version)||bridge.stateVersion+1;sessionStorage.setItem(HYDRATION_KEY,`${bridge.workspace.id}:${bridge.stateVersion}`);clearDirtyLocalState();bridge.conflict=false;bridge.conflictState=null;renderConflictActions();setStatus('Synced to LeadIntel','synced');return {saved:true,version:bridge.stateVersion};
  }
  async function resolveConflictUseServer(){if(!bridge.workspace||!bridge.conflictState)return {resolved:false};const state=bridge.conflictState;applyPayload(state.payload);bridge.stateVersion=Number(state.version)||0;bridge.conflict=false;bridge.conflictState=null;clearDirtyLocalState();sessionStorage.removeItem(CONFLICT_KEY);sessionStorage.setItem(HYDRATION_KEY,`${bridge.workspace.id}:${bridge.stateVersion}`);renderConflictActions();setStatus('Synced to LeadIntel','synced');showToast('Server version restored.');location.reload();return {resolved:true,source:'server'};}
  async function resolveConflictKeepLocal(){if(!bridge.workspace||!bridge.conflictState)return {resolved:false};bridge.stateVersion=Number(bridge.conflictState.version)||bridge.stateVersion;bridge.conflict=false;bridge.conflictState=null;sessionStorage.removeItem(CONFLICT_KEY);rebaseDirtyLocalState();renderConflictActions();setStatus('Saving local changes…','saving');const result=await saveNow();if(result.saved)showToast('Your local changes are now saved to LeadIntel.');return {resolved:Boolean(result.saved),source:'local',...result};}
  function signIn(){location.href=endpoint(`/api/auth/google/start?return_to=${encodeURIComponent(returnTo())}`);}
  async function signOut(){await api('/api/logout',{method:'POST'});sessionStorage.removeItem(HYDRATION_KEY);location.reload();}
  async function selectWorkspace(id){if(!bridge.workspaces.some(item=>item.id===id)||id===bridge.workspace?.id)return;if(hasDirtyLocalState()||bridge.conflict){const message=bridge.conflict?'Resolve the current sync conflict before switching workspaces.':'Finish syncing before switching workspaces.';setStatus(message,bridge.conflict?'error':'saving');showToast(message);const select=document.getElementById('server-workspace-select');if(select&&bridge.workspace)select.value=bridge.workspace.id;return;}localStorage.setItem(WORKSPACE_KEY,id);sessionStorage.removeItem(HYDRATION_KEY);location.reload();}
  async function refreshGmailStatus(){if(!bridge.session?.authenticated||!bridge.workspace){bridge.gmail={configured:false,connected:false,email:'',role:''};return bridge.gmail;}const {response,payload}=await api(`/api/integrations/gmail/status?workspace_id=${encodeURIComponent(bridge.workspace.id)}`);bridge.gmail=response.ok?payload:{configured:false,connected:false,email:'',role:''};root.dispatchEvent(new CustomEvent('leadintel:gmail-status',{detail:bridge.gmail}));return bridge.gmail;}
  function connectGmail(){if(!bridge.workspace)return;location.href=endpoint(`/api/integrations/gmail/start?workspace_id=${encodeURIComponent(bridge.workspace.id)}&return_to=${encodeURIComponent(returnTo())}`);}
  async function disconnectGmail(){if(!bridge.workspace)return {ok:false};const {response,payload}=await api(`/api/integrations/gmail/disconnect?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST'});await refreshGmailStatus();return {ok:response.ok,...payload};}
  async function sendGmail({domain,recipient,subject,body,idempotencyKey}){if(!bridge.workspace)return {ok:false,error:'No workspace selected'};const {response,payload}=await api(`/api/integrations/gmail/send?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey},body:JSON.stringify({idempotency_key:idempotencyKey,domain,recipient,subject,body})});return {ok:response.ok,status:response.status,...payload};}
  async function syncReplies(){if(!bridge.workspace)return {ok:false,replies:[]};const {response,payload}=await api(`/api/integrations/gmail/sync?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST'});return {ok:response.ok,status:response.status,replies:Array.isArray(payload.replies)?payload.replies:[],...payload};}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
