(function(root){
  'use strict';
  if(root.LeadIntelServerBridge)return;
  const API_BASE='https://leadintel-api.edgars-7e7.workers.dev';
  const ASSET_VERSION='20260915-mail-choice-v2';
  const asset=path=>`${path}?v=${ASSET_VERSION}`;
  const KEYS={main:'leadintel_customer_v2_state',discovery:'leadintel_customer_v2_discovery',outreach:'leadintel_customer_v2_outreach',delivery:'leadintel_customer_v2_delivery',meta:'leadintel_customer_v2_discovery_meta'};
  const WORKSPACE_KEY='leadintel_customer_v2_workspace';
  const AUTH_PROVIDER_KEY='leadintel_auth_provider';
  const HYDRATION_KEY='leadintel_customer_v2_server_hydration';
  const CONFLICT_KEY='leadintel_customer_v2_server_conflict';
  const DIRTY_KEY='leadintel_customer_v2_server_dirty';
  const VERSION_KEY='leadintel_customer_v2_server_versions';
  const CRM_MIGRATION_KEY='leadintel_customer_v2_crm_migrations';
  let saveTimer=null;let suppress=false;let initialized=false;
  const bridge={session:null,authProvider:localStorage.getItem(AUTH_PROVIDER_KEY)||'',workspaces:[],workspace:null,stateVersion:0,gmail:{configured:false,connected:false,email:'',role:''},microsoftMail:{configured:false,connected:false,email:'',role:''},status:'local',conflict:false,conflictState:null,saveNow,refreshGmailStatus,refreshMicrosoftMailStatus,syncReplies,sendGmail,sendMicrosoftMail,connectGmail,connectMicrosoftMail,disconnectGmail,disconnectMicrosoftMail,signIn,signOut,selectWorkspace,resolveConflictKeepLocal,resolveConflictUseServer,listCrmCompanies,getCrmCompany,saveCrmCompany,addCrmToPipeline,removeCrmFromPipeline,archiveCrmCompany,restoreCrmCompany,suppressCrmCompany,markCrmCustomer,saveCrmContacts,enrichCrmContact,recordCrmActivity,deleteCrmCompany,migrateLocalPipeline,switchProvider};
  root.LeadIntelServerBridge=bridge;

  function parse(key){try{return JSON.parse(localStorage.getItem(key)||'{}');}catch{return {};}}
  function bundle(){return {main:parse(KEYS.main),discovery:parse(KEYS.discovery),outreach:parse(KEYS.outreach),delivery:parse(KEYS.delivery),meta:{discovery:parse(KEYS.meta)}};}
  function isEmptyObject(value){return !value||typeof value!=='object'||Object.keys(value).length===0;}
  function hasLocalData(value=bundle()){return ['main','discovery','outreach','delivery'].some(key=>!isEmptyObject(value[key]));}
  function readVersionMap(){try{const value=JSON.parse(localStorage.getItem(VERSION_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch{return {};}}
  function readRememberedVersion(workspaceId){const value=Number(readVersionMap()[String(workspaceId||'')]);return Number.isFinite(value)&&value>=0?value:0;}
  function rememberServerVersion(workspaceId,version){if(!workspaceId)return;const map=readVersionMap();map[String(workspaceId)]=Math.max(0,Number(version)||0);localStorage.setItem(VERSION_KEY,JSON.stringify(map));}
  function readDirtyLocalState(){try{const value=JSON.parse(localStorage.getItem(DIRTY_KEY)||'null');return value&&typeof value==='object'?value:null;}catch{return null;}}
  function localWorkspaceId(){return bridge.workspace?.id||localStorage.getItem(WORKSPACE_KEY)||'';}
  function hasDirtyLocalState(){const value=readDirtyLocalState();return Boolean(value&&bridge.workspace&&(value.workspace_id===bridge.workspace.id||!value.workspace_id));}
  function markDirtyLocalState(){const workspaceId=localWorkspaceId();const current=readDirtyLocalState();if(current&&current.workspace_id===workspaceId)return;const baseVersion=bridge.workspace?bridge.stateVersion:readRememberedVersion(workspaceId);localStorage.setItem(DIRTY_KEY,JSON.stringify({workspace_id:workspaceId,base_version:baseVersion,updated_at:Date.now()}));}
  function rebaseDirtyLocalState(){if(!bridge.workspace)return;localStorage.setItem(DIRTY_KEY,JSON.stringify({workspace_id:bridge.workspace.id,base_version:bridge.stateVersion,updated_at:Date.now()}));}
  function clearDirtyLocalState(){const current=readDirtyLocalState();if(!current||!bridge.workspace||current.workspace_id===bridge.workspace.id||!current.workspace_id)localStorage.removeItem(DIRTY_KEY);}
  function clearCustomerCache(){suppress=true;try{for(const key of Object.values(KEYS))localStorage.removeItem(key);}finally{suppress=false;}}
  function endpoint(path){return `${API_BASE}${path}`;}
  async function api(path,options={}){const response=await fetch(endpoint(path),{credentials:'include',headers:{'Accept':'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})},...options});const payload=await response.json().catch(()=>({}));return {response,payload};}
  function returnTo(){const url=new URL(location.href);url.searchParams.delete('auth');url.searchParams.delete('gmail');url.searchParams.delete('microsoft_mail');url.searchParams.delete('reason');url.searchParams.delete('workspace_id');return url.toString();}
  function setStatus(text,kind=''){bridge.status=kind||text;const existing=document.querySelector('.autosave');if(existing){existing.innerHTML=`<i></i>${text}`;existing.dataset.serverStatus=kind||'';}const status=document.getElementById('server-sync-status');if(status){status.textContent=text;status.dataset.state=kind||'';}}
  function showToast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),3000);}
  function injectCss(){if(document.querySelector('link[data-leadintel-asset="server-css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=asset('server.css');link.dataset.leadintelAsset='server-css';document.head.appendChild(link);}
  function injectAccountUi(){
    const actions=document.querySelector('.top-actions');if(!actions||document.getElementById('server-account'))return;
    actions.insertAdjacentHTML('afterbegin','<div class="server-account" id="server-account"><div class="server-signin-options" id="server-signin-options"><button class="ghost-btn server-signin" id="server-google-signin" type="button">Sign in with Google</button><button class="ghost-btn server-signin server-microsoft-signin" id="server-microsoft-signin" type="button">Sign in with Microsoft</button></div><select id="server-workspace-select" aria-label="LeadIntel workspace" hidden></select><span id="server-account-label" hidden></span><span class="server-sync" id="server-sync-status">Local workspace</span><div class="server-conflict-actions" id="server-conflict-actions" hidden><button class="ghost-btn" id="server-use-server" type="button">Use server version</button><button class="ghost-btn" id="server-keep-local" type="button">Keep my local changes</button></div><button class="server-signout" id="server-signout" type="button" hidden>Sign out</button></div>');
    document.getElementById('server-google-signin')?.addEventListener('click',()=>signIn('google'));document.getElementById('server-microsoft-signin')?.addEventListener('click',()=>signIn('microsoft'));document.getElementById('server-signout')?.addEventListener('click',signOut);document.getElementById('server-workspace-select')?.addEventListener('change',e=>selectWorkspace(e.target.value));document.getElementById('server-use-server')?.addEventListener('click',resolveConflictUseServer);document.getElementById('server-keep-local')?.addEventListener('click',resolveConflictKeepLocal);
  }
  function renderConflictActions(){const actions=document.getElementById('server-conflict-actions');if(actions)actions.hidden=!bridge.conflict;}
  function renderAccount(){injectAccountUi();const signin=document.getElementById('server-signin-options');const select=document.getElementById('server-workspace-select');const label=document.getElementById('server-account-label');const signout=document.getElementById('server-signout');if(!signin)return;
    const authenticated=Boolean(bridge.session?.authenticated);signin.hidden=authenticated;select.hidden=!authenticated||bridge.workspaces.length<2;label.hidden=!authenticated;signout.hidden=!authenticated;
    if(authenticated){label.textContent=bridge.session.user?.name||bridge.session.user?.email||'Signed in';select.innerHTML=bridge.workspaces.map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===bridge.workspace?.id?'selected':''}>${escapeHtml(item.name)} · ${escapeHtml(item.role)}</option>`).join('');}renderConflictActions();
  }
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function patchStorage(){if(Storage.prototype.__leadintelServerPatched)return;const set=Storage.prototype.setItem;const remove=Storage.prototype.removeItem;Storage.prototype.setItem=function(key,value){set.call(this,key,value);if(this===localStorage&&Object.values(KEYS).includes(key)&&!suppress){markDirtyLocalState();scheduleSave();}};Storage.prototype.removeItem=function(key){remove.call(this,key);if(this===localStorage&&Object.values(KEYS).includes(key)&&!suppress){markDirtyLocalState();scheduleSave();}};Storage.prototype.__leadintelServerPatched=true;}
  function scheduleSave(){if(!bridge.session?.authenticated||!bridge.workspace||bridge.conflict)return;markDirtyLocalState();clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveNow(),1200);}
  function applyPayload(payload){suppress=true;try{const p=payload&&typeof payload==='object'?payload:{};for(const key of ['main','discovery','outreach','delivery']){if(p[key]&&typeof p[key]==='object')localStorage.setItem(KEYS[key],JSON.stringify(p[key]));else localStorage.removeItem(KEYS[key]);}if(p.meta?.discovery)localStorage.setItem(KEYS.meta,JSON.stringify(p.meta.discovery));else localStorage.removeItem(KEYS.meta);}finally{suppress=false;}}
  async function fetchSession(){const {response,payload}=await api('/api/session');bridge.session=response.ok?payload:{authenticated:false};return bridge.session;}
  async function fetchWorkspaces(){const {response,payload}=await api('/api/workspaces');bridge.workspaces=response.ok&&Array.isArray(payload.workspaces)?payload.workspaces:[];return bridge.workspaces;}
  async function fetchWorkspaceState(){if(!bridge.workspace)return null;const {response,payload}=await api(`/api/customer/state?workspace_id=${encodeURIComponent(bridge.workspace.id)}`);if(!response.ok)throw new Error(payload.error||'Unable to load workspace state');bridge.stateVersion=Number(payload.version)||0;return payload;}
  function pickWorkspace(){const preferred=localStorage.getItem(WORKSPACE_KEY);const dirty=readDirtyLocalState();const dirtyWorkspace=dirty?.workspace_id?bridge.workspaces.find(item=>item.id===dirty.workspace_id):null;bridge.workspace=dirtyWorkspace||bridge.workspaces.find(item=>item.id===preferred)||bridge.workspaces[0]||null;if(bridge.workspace)localStorage.setItem(WORKSPACE_KEY,bridge.workspace.id);}
  function enterConflict(state,message){bridge.conflict=true;bridge.conflictState=state&&typeof state==='object'?state:null;renderConflictActions();setStatus('Sync conflict · local changes preserved','error');showToast(message||'Server state changed in another session. Your local changes are still safe in this browser.');}
  async function hydrateAuthenticated(){const state=await fetchWorkspaceState();const marker=`${bridge.workspace.id}:${state.version}`;const dirty=readDirtyLocalState();if(hasDirtyLocalState()){if(!dirty.workspace_id&&Number(state.version)===0)rebaseDirtyLocalState();else if(Number(dirty.base_version)!==Number(state.version)){enterConflict(state,'LeadIntel preserved your local changes because the server workspace changed in another session.');return true;}setStatus('Unsynced changes · retrying','saving');scheduleSave();return true;}if(state.version>0&&sessionStorage.getItem(HYDRATION_KEY)!==marker){applyPayload(state.payload);clearDirtyLocalState();rememberServerVersion(bridge.workspace.id,state.version);sessionStorage.setItem(HYDRATION_KEY,marker);setStatus('Synced to LeadIntel','synced');location.reload();return false;}if(state.version===0&&hasLocalData()){markDirtyLocalState();setStatus('Unsynced changes · saving','saving');scheduleSave();return true;}rememberServerVersion(bridge.workspace.id,state.version);setStatus('Synced to LeadIntel','synced');return true;}
  async function init(){if(initialized)return;initialized=true;injectCss();injectAccountUi();patchStorage();const conflictNote=sessionStorage.getItem(CONFLICT_KEY);if(conflictNote){sessionStorage.removeItem(CONFLICT_KEY);showToast(conflictNote);}
    try{await fetchSession();if(!bridge.session?.authenticated){setStatus('Local workspace · Sign in to sync','local');renderAccount();root.dispatchEvent(new CustomEvent('leadintel:server-ready',{detail:bridge}));return;}await fetchWorkspaces();pickWorkspace();renderAccount();if(!bridge.workspace){setStatus('Signed in · No workspace','error');return;}const stay=await hydrateAuthenticated();if(!stay)return;const migration=await migrateLocalPipeline();if(!migration.ok)console.warn('LeadIntel CRM migration:',migration.error||'migration unavailable');await Promise.all([refreshGmailStatus(),refreshMicrosoftMailStatus()]);root.dispatchEvent(new CustomEvent('leadintel:server-ready',{detail:bridge}));}catch(cause){console.warn('LeadIntel server bridge:',cause);setStatus('Local cache · Server unavailable','error');renderAccount();root.dispatchEvent(new CustomEvent('leadintel:server-ready',{detail:bridge}));}
  }
  async function saveNow(){if(!bridge.session?.authenticated||!bridge.workspace||bridge.conflict)return {saved:false};clearTimeout(saveTimer);markDirtyLocalState();setStatus('Saving to LeadIntel…','saving');const payload={schema_version:1,version:bridge.stateVersion,payload:bundle()};const {response,payload:result}=await api(`/api/customer/state?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'PUT',body:JSON.stringify(payload)});
    if(response.status===409){bridge.stateVersion=Number(result.current?.version)||bridge.stateVersion;sessionStorage.setItem(CONFLICT_KEY,'Server state changed in another session. Your local changes were preserved and were not overwritten.');enterConflict(result.current);return {saved:false,conflict:true};}
    if(!response.ok){setStatus('Sync failed · Local cache safe','error');throw new Error(result.error||'Workspace save failed');}bridge.stateVersion=Number(result.version)||bridge.stateVersion+1;rememberServerVersion(bridge.workspace.id,bridge.stateVersion);sessionStorage.setItem(HYDRATION_KEY,`${bridge.workspace.id}:${bridge.stateVersion}`);clearDirtyLocalState();bridge.conflict=false;bridge.conflictState=null;renderConflictActions();setStatus('Synced to LeadIntel','synced');return {saved:true,version:bridge.stateVersion};
  }
  async function resolveConflictUseServer(){if(!bridge.workspace||!bridge.conflictState)return {resolved:false};const state=bridge.conflictState;applyPayload(state.payload);bridge.stateVersion=Number(state.version)||0;rememberServerVersion(bridge.workspace.id,bridge.stateVersion);bridge.conflict=false;bridge.conflictState=null;clearDirtyLocalState();sessionStorage.removeItem(CONFLICT_KEY);sessionStorage.setItem(HYDRATION_KEY,`${bridge.workspace.id}:${bridge.stateVersion}`);renderConflictActions();setStatus('Synced to LeadIntel','synced');showToast('Server version restored.');location.reload();return {resolved:true,source:'server'};}
  async function resolveConflictKeepLocal(){if(!bridge.workspace||!bridge.conflictState)return {resolved:false};bridge.stateVersion=Number(bridge.conflictState.version)||bridge.stateVersion;bridge.conflict=false;bridge.conflictState=null;sessionStorage.removeItem(CONFLICT_KEY);rebaseDirtyLocalState();renderConflictActions();setStatus('Saving local changes…','saving');const result=await saveNow();if(result.saved)showToast('Your local changes are now saved to LeadIntel.');return {resolved:Boolean(result.saved),source:'local',...result};}
  function signIn(provider='google'){const routes={google:'/api/auth/google/start',microsoft:'/api/auth/microsoft/start'},selected=provider==='microsoft'?'microsoft':'google';bridge.authProvider=selected;localStorage.setItem(AUTH_PROVIDER_KEY,selected);location.href=endpoint(`${routes[selected]}?return_to=${encodeURIComponent(returnTo())}`);}
  async function signOut(){await api('/api/logout',{method:'POST'});bridge.authProvider='';localStorage.removeItem(AUTH_PROVIDER_KEY);sessionStorage.removeItem(HYDRATION_KEY);location.reload();}
  async function switchProvider(provider='google'){const routes={google:'/api/auth/google/start',microsoft:'/api/auth/microsoft/start'},selected=provider==='microsoft'?'microsoft':'google';const {response}=await api('/api/logout',{method:'POST'});if(!response.ok){showToast('Unable to switch workspace account.');return {ok:false};}bridge.authProvider=selected;localStorage.setItem(AUTH_PROVIDER_KEY,selected);location.href=endpoint(`${routes[selected]}?return_to=${encodeURIComponent(returnTo())}`);return {ok:true};}
  async function selectWorkspace(id){if(!bridge.workspaces.some(item=>item.id===id)||id===bridge.workspace?.id)return;if(hasDirtyLocalState()||bridge.conflict){const message=bridge.conflict?'Resolve the current sync conflict before switching workspaces.':'Finish syncing before switching workspaces.';setStatus(message,bridge.conflict?'error':'saving');showToast(message);const select=document.getElementById('server-workspace-select');if(select&&bridge.workspace)select.value=bridge.workspace.id;return;}clearCustomerCache();localStorage.setItem(WORKSPACE_KEY,id);sessionStorage.removeItem(HYDRATION_KEY);location.reload();}
  function crmPath(path=''){if(!bridge.workspace)throw new Error('No workspace selected');const join=path.includes('?')?'&':'?';return `/api/crm${path}${join}workspace_id=${encodeURIComponent(bridge.workspace.id)}`;}
  async function crmRequest(path,options={}){if(!bridge.session?.authenticated||!bridge.workspace)return {ok:false,status:401,error:'Sign in to use Master CRM'};const {response,payload}=await api(crmPath(path),options);if(!response.ok)return {ok:false,status:response.status,...payload};return {ok:true,status:response.status,...payload};}
  async function listCrmCompanies(filters={}){const params=new URLSearchParams();if(filters.q)params.set('q',filters.q);if(filters.lifecycle)params.set('lifecycle',filters.lifecycle);if(filters.pipeline_stage||filters.pipelineStage)params.set('pipeline_stage',filters.pipeline_stage||filters.pipelineStage);if(filters.limit)params.set('limit',filters.limit);if(filters.cursor)params.set('cursor',filters.cursor);const suffix=params.toString()?`?${params.toString()}`:'';return crmRequest(`/companies${suffix}`);}
  async function getCrmCompany(id){return crmRequest(`/companies/${encodeURIComponent(id)}`);}
  async function saveCrmCompany(payload){return crmRequest('/companies',{method:'POST',body:JSON.stringify(payload||{})});}
  async function addCrmToPipeline(id,stage='Discovered'){return crmRequest(`/companies/${encodeURIComponent(id)}/pipeline`,{method:'POST',body:JSON.stringify({stage})});}
  async function removeCrmFromPipeline(id){return crmRequest(`/companies/${encodeURIComponent(id)}/pipeline`,{method:'DELETE'});}
  async function archiveCrmCompany(id){return crmRequest(`/companies/${encodeURIComponent(id)}/archive`,{method:'POST'});}
  async function restoreCrmCompany(id){return crmRequest(`/companies/${encodeURIComponent(id)}/restore`,{method:'POST'});}
  async function suppressCrmCompany(id){return crmRequest(`/companies/${encodeURIComponent(id)}/suppress`,{method:'POST'});}
  async function markCrmCustomer(id){return crmRequest(`/companies/${encodeURIComponent(id)}/mark-customer`,{method:'POST'});}
  async function saveCrmContacts(companyId,contacts){return crmRequest(`/companies/${encodeURIComponent(companyId)}/contacts`,{method:'POST',body:JSON.stringify({contacts:Array.isArray(contacts)?contacts:[]})});}
  async function enrichCrmContact(companyId,person,options={}){const selected=person&&typeof person==='object'?person:{};return crmRequest(`/companies/${encodeURIComponent(companyId)}/enrich-contact`,{method:'POST',body:JSON.stringify({person_id:String(selected.id||''),name:String(selected.name||''),title:String(selected.title||''),phone_lookup:Boolean(options.phoneLookup),allow_personal_email:Boolean(options.allowPersonalEmail)})});}
  async function recordCrmActivity(companyId,activity){return crmRequest(`/companies/${encodeURIComponent(companyId)}/activities`,{method:'POST',body:JSON.stringify(activity||{})});}
  async function deleteCrmCompany(id){return crmRequest(`/companies/${encodeURIComponent(id)}`,{method:'DELETE'});}
  function crmMigrationMap(){try{const value=JSON.parse(localStorage.getItem(CRM_MIGRATION_KEY)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch{return {};}}
  function markCrmMigrated(workspaceId){const map=crmMigrationMap();map[String(workspaceId)]=new Date().toISOString();localStorage.setItem(CRM_MIGRATION_KEY,JSON.stringify(map));}
  async function migrateLocalPipeline(){if(!bridge.session?.authenticated||!bridge.workspace)return {ok:false,migrated:0};const workspaceId=bridge.workspace.id;if(crmMigrationMap()[workspaceId])return {ok:true,migrated:0,already:true};const local=parse(KEYS.discovery);const pipeline=Array.isArray(local.pipeline)?local.pipeline:[];if(!pipeline.length){markCrmMigrated(workspaceId);return {ok:true,migrated:0};}const mapper=root.LeadIntelCrm?.mapLocalPipelineItemToCrm;if(typeof mapper!=='function')return {ok:false,migrated:0,error:'CRM migration mapper unavailable'};let migrated=0;for(const item of pipeline){const result=await saveCrmCompany(mapper(item));if(!result.ok)return {ok:false,migrated,error:result.error||'CRM migration failed'};migrated++;}markCrmMigrated(workspaceId);root.dispatchEvent(new CustomEvent('leadintel:crm-migrated',{detail:{workspace_id:workspaceId,migrated}}));return {ok:true,migrated};}
  async function refreshGmailStatus(){if(!bridge.session?.authenticated||!bridge.workspace){bridge.gmail={configured:false,connected:false,email:'',role:''};return bridge.gmail;}const {response,payload}=await api(`/api/integrations/gmail/status?workspace_id=${encodeURIComponent(bridge.workspace.id)}`);bridge.gmail=response.ok?payload:{configured:false,connected:false,email:'',role:''};root.dispatchEvent(new CustomEvent('leadintel:gmail-status',{detail:bridge.gmail}));return bridge.gmail;}
  async function refreshMicrosoftMailStatus(){if(!bridge.session?.authenticated||!bridge.workspace){bridge.microsoftMail={configured:false,connected:false,email:'',role:''};return bridge.microsoftMail;}const {response,payload}=await api(`/api/integrations/microsoft-mail/status?workspace_id=${encodeURIComponent(bridge.workspace.id)}`);bridge.microsoftMail=response.ok?payload:{configured:false,connected:false,email:'',role:''};root.dispatchEvent(new CustomEvent('leadintel:microsoft-mail-status',{detail:bridge.microsoftMail}));return bridge.microsoftMail;}
  function connectGmail(){if(!bridge.workspace)return;location.href=endpoint(`/api/integrations/gmail/start?workspace_id=${encodeURIComponent(bridge.workspace.id)}&return_to=${encodeURIComponent(returnTo())}`);}
  function connectMicrosoftMail(){if(!bridge.workspace)return;location.href=endpoint(`/api/integrations/microsoft-mail/start?workspace_id=${encodeURIComponent(bridge.workspace.id)}&return_to=${encodeURIComponent(returnTo())}`);}
  async function disconnectGmail(){if(!bridge.workspace)return {ok:false};const {response,payload}=await api(`/api/integrations/gmail/disconnect?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST'});await refreshGmailStatus();return {ok:response.ok,...payload};}
  async function disconnectMicrosoftMail(){if(!bridge.workspace)return {ok:false};const {response,payload}=await api(`/api/integrations/microsoft-mail/disconnect?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST'});await refreshMicrosoftMailStatus();return {ok:response.ok,...payload};}
  async function sendGmail({domain,recipient,subject,body,idempotencyKey}){if(!bridge.workspace)return {ok:false,error:'No workspace selected'};const {response,payload}=await api(`/api/integrations/gmail/send?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey},body:JSON.stringify({idempotency_key:idempotencyKey,domain,recipient,subject,body})});return {ok:response.ok,status:response.status,...payload};}
  async function sendMicrosoftMail({domain,recipient,subject,body,idempotencyKey}){if(!bridge.workspace)return {ok:false,error:'No workspace selected'};const {response,payload}=await api(`/api/integrations/microsoft-mail/send?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey},body:JSON.stringify({idempotency_key:idempotencyKey,domain,recipient,subject,body})});return {ok:response.ok,status:response.status,...payload};}
  async function syncReplies(){if(!bridge.workspace)return {ok:false,replies:[]};const {response,payload}=await api(`/api/integrations/gmail/sync?workspace_id=${encodeURIComponent(bridge.workspace.id)}`,{method:'POST'});return {ok:response.ok,status:response.status,replies:Array.isArray(payload.replies)?payload.replies:[],...payload};}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window);
