const {test}=require('node:test'),assert=require('node:assert/strict');const M=require('../message-studio.js');
const e={sender:'Alex Smith',company:'LegalCo',calendly:'https://calendly.com/alex/call',value:'Reduce avoidable admin time',offer:'Contract review'};
const input=subject=>JSON.stringify({subject,message:'Would you be open to a 20-minute Zoom conversation? '+e.calendly});
test('chosen approved introduction overrides a different AI subject for all four core styles',()=>{for(const mode of ['professional','curiosity','friendly','brutal']){const s=M.chooseSubject(M.normalize({mode},e),mode,'introduction');assert.equal(M.parse(input('Some invented sales subject'),e,{studio:s,context:{buyerCompany:'ClientCo'}}).subject,'Alex Smith. LegalCo');}});
test('fixed approved subjects cannot be rewritten and personal subjects remain editable',()=>{
 const s=M.chooseSubject(M.normalize({mode:'curiosity'},e),'curiosity','interrupt');assert.equal(M.parse(input('You should talk now'),e,{studio:s,context:{buyerCompany:'ClientCo'}}).subject,'If everything is on track, why talk?');
 let p=M.saveMyTemplate(M.normalize({},e),'template-1',{subject:'My custom wording',body:'My message'});p.mode='template-1';assert.equal(M.parse(input('My custom wording'),e,{studio:p,context:{buyerCompany:'ClientCo'}}).subject,'My custom wording');
});
test('benefit subject uses only the approved seller outcome, regardless of AI replacement',()=>{const s=M.chooseSubject(M.normalize({mode:'professional'},e),'professional','benefit');for(const proposed of ['Drawing and installation support','An opportunity to invent savings'])assert.equal(M.parse(input(proposed),e,{studio:s,context:{buyerCompany:'ClientCo'}}).subject,'An opportunity to '+e.value);});
test('approved choice resolves without generation when identity is known',()=>{const s=M.chooseSubject(M.normalize({mode:'professional'},e),'professional','introduction');assert.equal(M.resolveApprovedSubject(s,{buyerCompany:'ClientCo'},e),'Alex Smith. LegalCo');});
