const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const S=require('../message-studio.js'),E=require('../message-editor.js'),A=require('../approved-reference-scripts.js'),O=require('../outreach-engine.js');
const e={sender:'Alex Lane',company:'SellerCo',offer:'Drawing development; manufacturing; installation; workforce provision.',value:'SellerCo can reduce coordination burden for industrial projects by providing drawing development, manufacturing, quality control, delivery, installation, and project management through one full-service partner.',difference:'An integrated offering spanning engineering, prototyping, small- and large-volume serial production, custom manufacturing, surface treatment, welded-joint testing, international delivery, on-site installation, workforce provision, and project management.',approach:'Drawing development; serial production manufacturing; custom manufacturing and installation.',meetingValue:'relevant production data and lessons from previous projects',calendly:'https://calendly.com/alex/intro',language:'en'};
const ctx={channel:'email',firstName:'Robin',buyerName:'Robin',buyerCompany:'BuyerCo',trigger:{url:'https://buyer.test/news',verification:'source_verified',summary:'Nytt sovringsverk framtidssäkrar produktionen i Gällivare. BuyerCo satsar sex miljarder på ett nytt sovringsverk vid Malmbergsgruvan.'}};
const fields={triggerSummary:'BuyerCo is investing in a new sorting plant at Malmberget',offer:'drawing development, manufacturing, installation and workforce solutions',value:'reduce coordination burden through a single delivery partner',difference:'Their team provides engineering and manufacturing capabilities.',approach:'They support delivery and installation.',meetingValue:e.meetingValue};
function studio(mode='brutal'){return S.normalize({mode,essentials:e});}
test('screenshot regression cannot insert raw Swedish evidence or company sentences into approved fields',()=>{assert.equal(E.needsPreparation(studio(),ctx),true);assert.throws(()=>E.tailor(studio(),ctx),/Prepare concise English/);const prepared=E.parsePrepared(fields,studio(),ctx),d=E.tailor(studio(),E.preparedContext(studio(),ctx,prepared));assert.match(d.message,/A research brought me to BuyerCo is investing/);assert.match(d.message,/additional capabilities could reduce coordination burden/);assert.doesNotMatch(d.message,/could SellerCo can|satsar|sovringsverk|An integrated offering spanning|Drawing development; serial/);assert.match(d.message,/They provide drawing development, manufacturing/);});
test('all core styles preserve the protected template skeleton after field preparation',()=>{for(const mode of ['professional','curiosity','friendly','brutal']){const s=studio(mode),original=A.originalText(mode),body=S.defaults.find(t=>t.id===mode).body;const prepared=E.parsePrepared({...fields,...(mode==='professional'?{difference:''}:{})},s,ctx),d=E.tailor(s,E.preparedContext(s,ctx,prepared));assert.ok(d.message.includes(e.calendly));assert.doesNotMatch(d.message,/could SellerCo can|satsar|sovringsverk/);assert.equal(S.defaults.find(t=>t.id===mode).body,body);assert.equal(A.originalText(mode),original);assert.ok(Object.isFrozen(S.defaults.find(t=>t.id===mode)));}});
test('AI receives only field preparation authority and cannot return changed originals or whole messages',()=>{const p=E.preparationPrompt(studio(),ctx);assert.match(p.system,/Never return or rewrite a complete message/);assert.equal(JSON.parse(p.prompt).sources.triggerSummary,ctx.trigger.summary);for(const patch of [{message:'Rewritten original'},{value:'SellerCo can reduce costs'},{difference:'Their team has 99 years of experience.'},{offer:'manufacturing https://invented.test'},{triggerSummary:ctx.trigger.summary},{value:'x'.repeat(161)}])assert.throws(()=>E.parsePrepared({...fields,...patch},studio(),ctx));});
test('prepared fields cannot move to another workspace seller, buyer or reviewed evidence',()=>{const prepared=E.parsePrepared(fields,studio(),ctx);assert.throws(()=>E.preparedContext(studio(),{...ctx,trigger:{...ctx.trigger,summary:'A different project'}},prepared));const another=S.normalize({mode:'brutal',essentials:{...e,value:'a different result'}});assert.throws(()=>E.preparedContext(another,ctx,prepared));assert.throws(()=>E.preparedContext(S.normalize({mode:'brutal',essentials:{...e,company:'Another Seller'}}),ctx,prepared));assert.throws(()=>E.preparedContext(studio(),{...ctx,buyerCompany:'Other Buyer'},prepared));assert.throws(()=>E.parsePrepared({...fields,triggerSummary:'Invented project'},studio(),{...ctx,trigger:null}));});
test('Save, Rewrite acceptance, repeated template application and reload never overwrite the first protected original',()=>{const s=studio(),context=E.preparedContext(s,ctx,E.parsePrepared(fields,s,ctx)),d=E.tailor(s,context),key=E.scope('w1',{domain:'buyer.test',channel:'email'},s,ctx);let item=E.apply({domain:'buyer.test',company:'BuyerCo',channel:'email',drafts:{},messageStudioDraft:{}},d,{original:true,key,origin:'tailored'});item=E.apply(item,{subject:d.subject,message:'Manual edit'});item=E.apply(item,{subject:d.subject,message:'AI alternative'});item=E.apply(item,{subject:d.subject,message:'Reapplied draft'},{original:true,key});assert.equal(E.original(item,key).message,d.message);const restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(item),'buyer.test');assert.equal(E.original(restored,key).message,d.message);assert.equal(restored.drafts.emailBody,'Reapplied draft');const changed=E.apply(restored,{subject:'New context',message:'New original'},{original:true,key:'another-context'});assert.equal(changed.messageStudioDraft.originalHistory[0].draft.message,d.message);assert.equal(E.original(changed,'another-context').message,'New original');});
function runtime(){let item={domain:'buyer.test',channel:'email',dossier:{},drafts:{emailSubject:'Original subject',emailBody:'Original text'},messageStudioDraft:{}},scope='current',source={subject:'Original subject',message:'Original text'},resolve;
 const s=studio(),context={...ctx,eventCampaign:null},messages=[];
 const runtime={LeadIntelMessageEditor:E,LeadIntelMessageStudio:S,currentItem:()=>item,readStudio:()=>s,studioState:()=>s,studioMessageContext:()=>context,selectedCandidate:()=>({}),crmBridge:()=>({workspace:{id:'w1'}}),messageWorkspaceUsable:()=>true,scriptGenerationRequest:0,studioGenerationBusy:false,studioGenerationError:false,approvedFieldController:null,cancelPendingScriptGeneration(){runtime.scriptGenerationRequest++;},editorDraft:()=>source,AbortController,setTimeout,clearTimeout,q:()=>({textContent:''}),renderMessageWorkspace(){},renderAll(){},toast:m=>messages.push(m),applyApprovedTemplate:()=>{item.drafts.emailBody='Corrected';return true;},fetch:()=>new Promise(r=>resolve=r)};
 vm.createContext(runtime);let src=fs.readFileSync(require.resolve('../outreach-ui.js'),'utf8');vm.runInContext(src.slice(src.indexOf('async function prepareApprovedTemplateFields('),src.indexOf('function selectMandatoryEmailStyle')),runtime);
 const key=E.scope('w1',item,s,context);return {runtime,key,context,messages,get item(){return item;},resolve:()=>resolve({ok:true,json:async()=>({text:JSON.stringify(fields)})}),edit:()=>source={...source,message:'Later manual edit'}};
}
test('late field preparation cannot replace a manual edit or another buyer',async()=>{const h=runtime(),run=h.runtime.prepareApprovedTemplateFields(studio(),h.context,h.key);h.edit();h.resolve();assert.equal(await run,false);assert.equal(h.item.drafts.emailBody,'Original text');const b=runtime(),other=b.runtime.prepareApprovedTemplateFields(studio(),b.context,b.key);b.item.selectedPersonId='other';b.resolve();assert.equal(await other,false);assert.equal(b.item.drafts.emailBody,'Original text');});
test('field preparation applies only after complete validation with unchanged context',async()=>{const h=runtime(),run=h.runtime.prepareApprovedTemplateFields(studio(),h.context,h.key);assert.equal(h.item.drafts.emailBody,'Original text');h.resolve();assert.equal(await run,true);assert.equal(h.item.drafts.emailBody,'Corrected');});
