const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../discovery-ui.js'),'utf8');
function runtime({sameDomain=true,switchWorkspace=false}={}){
 const candidate={domain:'lkab.com',people:[],buyerSearchMode:'user_selected_target'},contact={external_person_id:'joakim',work_email:'joakim.winsa@lkab.com',email_status:'public_confirmed'};
 const detail={ok:true,company:{normalized_domain:sameDomain?'lkab.com':'other.example'},contacts:[contact],intelligence:{research_snapshot:{buyerResearch:{version:2,checkedAt:'2026-10-05',buyers:[{id:'joakim',name:'Joakim Winsa',title:'Project Manager',kept:true,flowSelected:true,identitySourceUrl:'https://lkab.com/jobs',emailResearch:{status:'complete'},contactEvidence:{email:contact.work_email,emailUrl:'https://lkab.com/jobs'}}],discovery:{opportunityRoles:['Project Manager']}}}}};
 const bridge={workspace:{id:'w1'},listCrmCompanies:async()=>({ok:true,companies:[]}),getCrmCompany:async()=>{if(switchWorkspace)bridge.workspace.id='w2';return detail;}};
 const ctx={Date,Promise,discoveryMounted:true,crmRefreshing:false,crmAvailable:false,crmCompanies:[],crmPipeline:[],discovery:{selectedProspects:[candidate]},crmAuthenticated:()=>true,bridge:()=>bridge,crmCompanyByDomain:()=>({id:'lkab'}),canonicalDomain:x=>x,hydrateLocalPipelineFromCrm:()=>{},saveDiscovery:()=>{},renderAll:()=>{},scheduleSavedBuyerPublicChecks:()=>{},enrichmentResults:new Map(),personKey:(c,p)=>p.id,BUYER_RESEARCH_VERSION:'test',PUBLIC_NAME_CHECK_VERSION:'test',LeadIntelDiscovery:{normalizeLinkedInUrl:x=>x||'',qualifyBuyer:()=>({eligible:true}),mergeBuyerPool:(old,rows)=>rows}};
 vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function restoreNewerBuyerResearch('),source.indexOf('function hydrateLocalPipelineFromCrm('))+source.slice(source.indexOf('async function refreshCrmState('),source.indexOf('function injectDiscoveryUI(')),ctx);return {ctx,candidate,contact};
}
test('a reselected empty buyer pool restores durable research and accepted contact evidence',async()=>{const {ctx,candidate,contact}=runtime();await ctx.refreshCrmState();assert.equal(candidate.people[0].id,'joakim');assert.equal(candidate.people[0].publicEmail,contact.work_email);assert.equal(candidate.people[0].kept,true);assert.equal(candidate.people[0].flowSelected,true);assert.equal(ctx.enrichmentResults.get('joakim').contact,contact);});
test('CRM recovery rejects another domain and a changed workspace',async()=>{for(const options of [{sameDomain:false},{switchWorkspace:true}]){const {ctx,candidate}=runtime(options);await ctx.refreshCrmState();assert.equal(candidate.people.length,0);}});
