const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
for(const status of ['sending','failed','sent'])test(`Gmail ${status} status is not misreported as delivery`,async()=>{
  let confirmed=0;
  const nodes={'delivery-company-select':{value:'example.com'},'delivery-recipient':{value:'buyer@example.com'},'send-with-gmail':{},'confirm-delivery-sent':{click(){confirmed++;}}};
  const outreachApi={normalizeOutreachState:()=>({items:[{domain:'example.com',approved:true,approvedAt:'2026-09-05',drafts:{}}]}),buildApprovedSendPayload:(_pkg,recipient)=>({recipient,subject:'Approved subject',textBody:'Approved body',htmlBody:null})};
  const window={LeadIntelOutreach:outreachApi,LeadIntelServerBridge:{gmail:{connected:true},sendGmail:async()=>({ok:true,duplicate:true,message:{status}}),saveNow:async()=>{}}};
  const source=fs.readFileSync(path.join(__dirname,'../production-gmail-ui.js'),'utf8').replace(/\}\)\(typeof window!==['"]undefined['"]\?window:globalThis\);\s*$/,'root.sendForTest=send;})(typeof window!==\'undefined\'?window:globalThis);');
  vm.runInNewContext(source,{window,document:{readyState:'loading',addEventListener(){},getElementById:id=>nodes[id]},localStorage:{getItem:()=>null},sessionStorage:{setItem(){}},LeadIntelOutreach:outreachApi,LeadIntelDelivery:{normalizeEmail:x=>x},confirm:()=>true,crypto:webcrypto,TextEncoder,setTimeout,clearTimeout});
  await window.sendForTest();assert.equal(confirmed,status==='sent'?1:0);assert.equal(nodes['send-with-gmail'].disabled,false);
});

for(const provider of ['gmail','microsoft'])test(`a context change during ${provider} confirmation prevents the provider request`,async()=>{
 const Q=require('../page-quality.js');let inputs={recipient:'buyer@example.com'},requests=0,confirmations=0;const session={ready:true,authenticated:true,workspaceId:'w1'},quality=Q.createCoordinator({session:()=>session});quality.register('delivery',{read:()=>({loaded:true,inputs})});
 const nodes={'delivery-company-select':{value:'example.com'},'delivery-recipient':{value:'buyer@example.com'},'send-with-gmail':{},'send-with-microsoft':{},'confirm-delivery-sent':{click(){confirmations++;}}},outreachApi={normalizeOutreachState:()=>({items:[{domain:'example.com',approved:true,approvedAt:'2026-09-05',drafts:{}}]}),buildApprovedSendPayload:()=>({recipient:'buyer@example.com',subject:'Subject',textBody:'Body'})},window={LeadIntelPageQuality:quality,LeadIntelOutreach:outreachApi,LeadIntelServerBridge:{gmail:{connected:true},microsoftMail:{connected:true},sendGmail:async()=>{requests++;},sendMicrosoftMail:async()=>{requests++;}}};
 const source=fs.readFileSync(path.join(__dirname,'../production-gmail-ui.js'),'utf8').replace(/\}\)\(typeof window!==['"]undefined['"]\?window:globalThis\);\s*$/,'root.sendForTest=send;})(typeof window!==\'undefined\'?window:globalThis);');
 vm.runInNewContext(source,{window,document:{readyState:'loading',addEventListener(){},getElementById:id=>nodes[id]},localStorage:{getItem:()=>null},LeadIntelOutreach:outreachApi,LeadIntelDelivery:{normalizeEmail:x=>x},confirm:()=>{inputs={recipient:'other@example.com'};return true;},crypto:webcrypto,TextEncoder,setTimeout,clearTimeout});await window.sendForTest(provider);assert.equal(requests,0);assert.equal(confirmations,0);assert.equal(nodes[provider==='microsoft'?'send-with-microsoft':'send-with-gmail'].disabled,false);
});

test('a provider response after a workspace switch cannot record delivery or save into the new workspace',async()=>{
 const Q=require('../page-quality.js');let workspace='w1',records=0,saves=0;const quality=Q.createCoordinator({session:()=>({ready:true,authenticated:true,workspaceId:workspace})});quality.register('delivery',{read:()=>({loaded:true,inputs:{recipient:'buyer@example.com'}})});
 const nodes={'delivery-company-select':{value:'example.com'},'delivery-recipient':{value:'buyer@example.com'},'send-with-gmail':{},'confirm-delivery-sent':{click(){records++;}},toast:{classList:{add(){},remove(){}}}},outreachApi={normalizeOutreachState:()=>({items:[{domain:'example.com',approved:true,approvedAt:'2026-09-05',drafts:{}}]}),buildApprovedSendPayload:()=>({recipient:'buyer@example.com',subject:'Subject',textBody:'Body'})},window={LeadIntelPageQuality:quality,LeadIntelOutreach:outreachApi,LeadIntelServerBridge:{gmail:{connected:true},sendGmail:async()=>{workspace='w2';return {ok:true,message:{status:'sent'}};},saveNow:async()=>{saves++;}}};
 const source=fs.readFileSync(path.join(__dirname,'../production-gmail-ui.js'),'utf8').replace(/\}\)\(typeof window!==['"]undefined['"]\?window:globalThis\);\s*$/,'root.sendForTest=send;})(typeof window!==\'undefined\'?window:globalThis);');vm.runInNewContext(source,{window,document:{readyState:'loading',addEventListener(){},getElementById:id=>nodes[id]},localStorage:{getItem:()=>null},LeadIntelOutreach:outreachApi,LeadIntelDelivery:{normalizeEmail:x=>x},confirm:()=>true,crypto:webcrypto,TextEncoder,setTimeout,clearTimeout});await window.sendForTest();assert.equal(records,0);assert.equal(saves,0);assert.match(nodes.toast.textContent,/Provider confirmed the send.*original workspace/);
});
