const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Facts=require('../message-facts.js'),O=require('../outreach-engine.js');
const source=fs.readFileSync(require.resolve('../outreach-ui.js'),'utf8');
function setup(search){let item={domain:'buyer.example',company:'Acme',channel:'linkedin',selectedPersonId:'p1',drafts:{linkedinMessage:'Hi Sam,\n\nI’m Alex from Legal Partners.\n\nMy original close.'},dossier:{domain:'buyer.example',evidence:[]}},workspace='w1',calls=[],nodes=new Map();
 const q=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',checked:true,value:'',scrollIntoView(){}});return nodes.get(id);};
 const root={LeadIntelMessageFacts:Facts,LeadIntelOutreach:O,LeadIntelMessageStudio:require('../message-studio.js'),studioGenerationBusy:false,AbortController,setTimeout,clearTimeout,URL,Promise,esc:String,q,messageWorkspaceUsable:()=>workspace==='w1',readDraftEdits:()=>item,currentItem:()=>item,selectedCandidate:()=>({company:'Acme',domain:'buyer.example'}),selectedContact:()=>({title:'Partner'}),crmBridge:()=>({workspace:{id:workspace}}),studioState:()=>({essentials:{language:'en',offer:'legal advisory',problem:'cross-border expansion'}}),renderMessageWorkspace(){},renderAll(){},cancelPendingScriptGeneration(){},invalidateStudioDraft(){},toast(){},upsertItem:i=>{item=O.normalizeOutreachState({selectedDomain:i.domain,items:[i]}).items[0];},dossierSearch:async meta=>{calls.push(meta);return search(meta);}};
 vm.runInNewContext(source.slice(source.indexOf('function messageFactCandidates'),source.indexOf('function injectOutreachUI')),root);
 return {root,q,calls,get item(){return item;},set workspace(v){workspace=v;},set item(v){item=v;}};
}
test('fact research preserves the latest draft, never auto-reviews sources, and reports missing events',async()=>{const h=setup(async()=>[{url:'https://buyer.example/about',text:'Acme provides advisory services for international clients.',title:'Who we are'}]);await h.root.refreshMessageFacts();assert.equal(h.calls.length,3);assert.equal(h.item.drafts.linkedinMessage,'Hi Sam,\n\nI’m Alex from Legal Partners.\n\nMy original close.');assert.equal(h.item.dossier.selectedTrigger,null);assert.match(h.q('message-fact-status').textContent,/No specific event/);});
test('late research results cannot enter another workspace',async()=>{const finishes=[];const h=setup(()=>new Promise(resolve=>finishes.push(resolve)));const pending=h.root.refreshMessageFacts();h.workspace='other';for(const finish of finishes)finish([{url:'https://buyer.example/news',text:'Acme is opening a new factory in Sweden in 2028.'}]);await pending;assert.equal(h.item.dossier.evidence.length,0);});
test('opening action preserves message body and reviewed source in saved state',()=>{const h=setup(async()=>[]),row={url:'https://buyer.example/news',text:'Acme is opening a new factory in Sweden in 2028.',title:'News'};h.item={...h.item,dossier:{...h.item.dossier,evidence:[row]}};h.item=O.reviewTrigger(h.item,row.url);h.root.updateMessageOpening();assert.match(h.item.drafts.linkedinMessage,/I noticed Acme/);assert.ok(h.item.drafts.linkedinMessage.endsWith('I’m Alex from Legal Partners.\n\nMy original close.'));assert.equal(h.item.dossier.selectedTrigger.verification,'user_reviewed');assert.match(h.q('message-fact-status').textContent,/preserved/);});
test('a late-page event survives review and CRM save/reload with its exact excerpt',()=>{const row={url:'https://buyer.example/news',text:'Company background serves clients internationally. '.repeat(30)+'Acme is opening a new factory in Sweden in 2028.',title:'News'},item={domain:'buyer.example',channel:'linkedin',dossier:{domain:'buyer.example',evidence:[row]},drafts:{linkedinMessage:'Saved body'}};const fact=Facts.candidates([row],{domain:item.domain})[0];const reviewed=O.reviewTrigger(item,row.url,'2026-10-07',fact.summary),restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(reviewed),item.domain);assert.equal(restored.dossier.selectedTrigger.excerpt,'Acme is opening a new factory in Sweden in 2028.');assert.equal(restored.drafts.linkedinMessage,'Saved body');});
test('refreshing a full persisted dossier keeps the new event',async()=>{const row={url:'https://buyer.example/news',text:'Acme is opening a new factory in Sweden in 2028.',title:'News'},h=setup(async()=>[row]);h.item={...h.item,dossier:{...h.item.dossier,evidence:Array.from({length:15},(_,i)=>({url:`https://buyer.example/about/${i}`,text:`Background information number ${i} serves international customers.`}))}};await h.root.refreshMessageFacts();assert.equal(h.item.dossier.evidence.length,15);assert.ok(h.item.dossier.evidence.some(r=>r.url===row.url));});
test('fact research cannot start while generation owns the draft',async()=>{const h=setup(async()=>[]);h.root.studioGenerationBusy=true;await h.root.refreshMessageFacts();assert.equal(h.calls.length,0);});
test('email opening update can be saved, restored and approved without regenerating the body',()=>{
 const h=setup(async()=>[]),essentials={language:'en',offer:'Legal advice',target:'businesses',problem:'admin',value:'simpler work',meetingValue:'compare requirements',nextAction:'Book a call',sender:'Alex',company:'Legal Partners',calendly:'https://calendly.com/alex/call'},row={url:'https://buyer.example/news',title:'Expansion',text:'Acme is opening a new factory in Sweden in 2028.'};
 h.root.studioState=()=>({essentials});h.item={...h.item,channel:'email',campaignScenario:{id:'core',language:'en',resolvedLanguage:'en',status:'approved'},messageStudioDraft:{essentials},localizationStatus:'complete',localizationApprovalBlocked:true,localizationProvenance:{language:'en',provider:'test-provider',model:'test-model',selectionSource:'manual'},drafts:{...h.item.drafts,emailSubject:'Idea',emailBody:'Hi Sam,\n\nI’m Alex from Legal Partners.\n\nMy custom body.\n\n30-minute Zoom: https://calendly.com/alex/call'},dossier:{...h.item.dossier,evidence:[row]}};h.item=O.reviewTrigger(h.item,row.url);h.root.updateMessageOpening();
 assert.equal(h.item.localizationApprovalBlocked,false);const restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(h.item),h.item.domain);assert.match(restored.drafts.emailBody,/My custom body/);const approved=O.approveOutreachItem(restored,restored.drafts);assert.equal(approved.approved,true,approved.error);
});
