const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),T=require('../message-translations.js'),S=require('../message-studio.js'),O=require('../outreach-engine.js');
const source=fs.readFileSync(require.resolve('../outreach-ui.js'),'utf8');
function harness(){let workspace='w1',studio={},item={domain:'buyer.example',selectedPersonId:'p1',channel:'email',drafts:{emailSubject:'Acme',emailBody:'Hi Sam'},localizationProvenance:{language:'en'}};let savedItems=[],resolve,startedResolve;const started=new Promise(r=>startedResolve=r);
 const ctx={LeadIntelMessageTranslations:T,LeadIntelMessageStudio:S,LeadIntelOutreach:O,messageWorkspaceUsable:()=>true,messageTranslationBusy:false,studioGenerationBusy:false,messageFactResearchBusy:false,messageEditor:null,currentItem:()=>item,readDraftEdits:()=>T.capture(item),studioState:()=>S.normalize(studio),persistStudio:s=>{studio=S.storageState(s);},outreach:{selectedDomain:item.domain},crmBridge:()=>({workspace:{id:workspace},saveNow:()=>new Promise(r=>{resolve=r;startedResolve();})}),cancelPendingScriptGeneration(){},renderAll(){},renderMessageWorkspace(){},upsertItem:n=>{item=O.normalizeOutreachState({items:[n]}).items[0];},saveScriptPackage:async()=>{savedItems.push(O.buildCrmScriptSnapshot(item));return{ok:true};}};
 vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('let messageLanguageSettingsBusy='),source.indexOf('function initOutreach(')),ctx);
 return{ctx,started,get studio(){return studio;},get item(){return item;},set item(value){item=value;},savedItems,complete(saved=true){resolve({saved});},workspace(value){workspace=value;},value(name){return vm.runInContext(name,ctx);}};
}
test('setting a default saves the flow preference without translating or changing the working email',async()=>{const h=harness(),add=h.ctx.manageMessageLanguage('add','sv');await h.started;h.complete();await add;const change=h.ctx.manageMessageLanguage('default','sv');h.complete();assert.equal(await change,true);assert.equal(h.studio.languageSettings.defaultLanguage,'sv');assert.equal(h.studio.languageSettings.targetLanguage,'sv');assert.equal(h.item.drafts.emailBody,'Hi Sam');assert.equal(T.book(h.item).activeLanguage,'en');assert.match(h.value('messageLanguageSettingsStatus'),/Existing messages are unchanged/);});
test('a failed preference sync stays clearly local and cannot claim the default was saved',async()=>{const h=harness(),pending=h.ctx.manageMessageLanguage('add','sv');await h.started;h.complete(false);assert.equal(await pending,false);assert.match(h.value('messageLanguageSettingsStatus'),/remain in this browser/);assert.equal(h.value('messageLanguageSettingsBusy'),false);assert.equal(h.item.drafts.emailBody,'Hi Sam');});
test('removal persists the recoverable version and original together and a late sync cannot switch another workspace',async()=>{const h=harness();h.item=T.translated(h.item,'lv',{subject:'Acme',message:'Sveiki Sam'});const pending=h.ctx.manageMessageLanguage('remove','lv');await h.started;assert.equal(h.savedItems.length,1);const restored=O.restoreCrmScriptSnapshot(h.savedItems[0],h.item.domain);assert.equal(T.book(restored).removedVersions.lv.message,'Sveiki Sam');assert.equal(restored.drafts.emailBody,'Hi Sam');h.workspace('w2');h.complete();assert.equal(await pending,false);assert.equal(h.value('messageLanguageSettingsBusy'),false);});
