const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('jsdom'),T=require('../message-translations.js'),S=require('../message-studio.js');
const ui=fs.readFileSync(require.resolve('../outreach-ui.js'),'utf8');
test('the actual composer render initializes editor state before language rendering and guards edit/preview/save',()=>{
 for(const state of [{},{editing:true},{preview:{}},{busy:true},{saving:true}]){
  const w=new JSDOM('<div class="mw-generate-bar"><label>Language<select id="message-language"></select></label></div>',{runScripts:'outside-only'}).window;w.LeadIntelMessageTranslations=T;w.eval(fs.readFileSync(require.resolve('../message-translation-ui.js'),'utf8'));w.LeadIntelMessageTranslationUI.mount(w.document,{});
  const item={domain:'buyer.test',selectedPersonId:'p1',channel:'email',dossier:{},drafts:{emailBody:'Original',emailSubject:'Subject'},localizationProvenance:{language:'en'}},studio=S.normalize({languageSettings:{languages:['en','sv'],defaultLanguage:'sv'}});
  const ctx={window:{LeadIntelMessageWorkspace:{render:()=>({canGenerate:true}),renderSubjects(){}},LeadIntelMessageTranslationUI:w.LeadIntelMessageTranslationUI},document:w.document,LeadIntelMessageTranslations:T,LeadIntelMessageStudio:S,LeadIntelMessageEditor:{original:()=>null,scope:()=>'',updateUndo:()=>null,savedDraft:()=>true},messageEditor:{state:()=>state},renderSubjectReadiness(){},currentItem:()=>item,selectedCandidate:()=>({domain:item.domain}),studioState:()=>studio,selectedContact:()=>({}),crmBridge:()=>({workspace:{id:'w1'}}),messageWorkspaceUsable:()=>true,messageLanguageSettings:()=>studio.languageSettings,messageLanguageSettingsStatus:'',messageTranslationBusy:false,messageLanguageSettingsBusy:false,studioGenerationBusy:false,messageFactResearchBusy:false,messageTranslationError:'',messageFactScope:'w1|buyer.test|p1|email',readJson:()=>({scriptBuyer:{}}),DISCOVERY_META_KEY:'meta',DELIVERY_STORAGE_KEY:'delivery',handoffContact:null,originalScriptBusy:false,editorDraft:()=>({subject:'Subject',message:'Original'}),messagePlaceholderHelp:()=>'',selectedSavedLibraryTemplate:()=>'',messageInFlow:()=>false,rankedBuyingTriggers:()=>[],chooseBuyingTrigger(){},buyerHandoffPending:false,crmAuthenticated:()=>true,mainState:()=>({brandIdentity:{}}),studioMessageContext:()=>({}),studioGenerationError:false,pendingMessageSelections:()=>false,messageFlowBusy:false,q:id=>w.document.getElementById(id)||{}};
  vm.createContext(ctx);vm.runInContext(ui.slice(ui.indexOf('function renderMessageWorkspace(){'),ui.indexOf('function prepareStudioBuyer(')),ctx);assert.doesNotThrow(()=>ctx.renderMessageWorkspace());
  assert.equal(w.document.getElementById('message-translate').textContent,'Translate into Swedish');assert.equal(w.document.getElementById('message-translate').disabled,Boolean(state.editing||state.preview||state.busy||state.saving));assert.equal(item.drafts.emailBody,'Original');w.close();
 }
});
