const test=require('node:test'),assert=require('node:assert/strict'),T=require('../message-translations.js'),O=require('../outreach-engine.js');
const item={domain:'buyer.example',selectedPersonId:'p1',channel:'email',dossier:{domain:'buyer.example',people:[{id:'p1',name:'Sam'}]},drafts:{emailSubject:'Acme',emailBody:'Hi Sam. Acme offers 30% savings. Zoom 30 minutes: https://calendly.com/alex/call'},localizationProvenance:{language:'en'}};
const lv={subject:'Acme',message:'Sveiki, Sam. Acme piedāvā 30% ietaupījumu. Zoom 30 minūtes: https://calendly.com/alex/call'};
test('translations keep English and persist through the real CRM snapshot',()=>{const translated=T.translated(item,'lv',T.validate(T.source(item),lv,{protectedTerms:['Acme','Sam']}));assert.equal(translated.drafts.emailBody,lv.message);assert.equal(T.book(translated).versions.en.message,item.drafts.emailBody);const restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(translated),item.domain);assert.equal(T.book(restored).versions.lv.message,lv.message);assert.equal(T.activate(restored,'en').drafts.emailBody,item.drafts.emailBody);});
test('English edits mark translations stale without deleting them; translation edits stay independent',()=>{let i=T.translated(item,'lv',lv);i=T.capture({...i,drafts:{...i.drafts,emailBody:lv.message+' Paldies.'}});i=T.activate(i,'en');i=T.capture({...i,drafts:{...i.drafts,emailBody:item.drafts.emailBody+' Thanks.'}});assert.equal(T.stale(i,'lv'),true);assert.ok(T.book(i).versions.lv.message.endsWith('Paldies.'));assert.equal(T.stale(T.generated(i,{subject:'New',message:'New original'}),'lv'),true);});
test('translation validation rejects changed facts, links, names and missing content',()=>{for(const message of [lv.message.replace('30%','40%'),lv.message.replace('/alex/call','/other/call'),lv.message.replace('Acme','Other'),'',lv.message+' https://invented.example'])assert.throws(()=>T.validate(T.source(item),{...lv,message},{protectedTerms:['Acme']}));});
test('legacy non-English originals retain their actual language and cannot be mislabeled English',()=>{const i={...item,localizationProvenance:{language:'lv'}};assert.equal(T.book(i).originalLanguage,'lv');assert.throws(()=>T.source(i),/English original/);assert.equal(T.book(T.generated(i,{subject:'English',message:'English draft'})).versions.lv.message,item.drafts.emailBody);});
test('translation prompt uses chosen language and preserves an empty LinkedIn subject',()=>{assert.match(T.prompt({subject:'',message:'Message'},'lv').system,/Latvian/);assert.equal(T.validate({subject:'',message:'Hello 30'},{message:'Sveiki 30'},{channel:'linkedin'}).subject,'');assert.throws(()=>T.prompt({},'xx'));});

test('percentage and currency figures keep their associations',()=>{const source={subject:'',message:'30 minutes, 50% savings, $200 or 300€'};for(const message of ['30 minutes, 50 savings, $200 or 300€','50 minutes, 30% savings, $200 or 300€','30 minutes, 50% savings, $300 or 200€'])assert.throws(()=>T.validate(source,{subject:'',message}));assert.doesNotThrow(()=>T.validate(source,{subject:'',message:'30 minūtes, 50 % ietaupījums, $200 vai 300 €'}));});
test('regeneration preserves a translated edit and activation restores provider and campaign metadata',()=>{let i=T.translated({...item,localizationProvenance:{language:'en',provider:'english-provider',model:'english-model'}},'lv',lv,{provider:'translation-provider',model:'translation-model'});assert.equal(i.localizationProvenance.provider,'translation-provider');assert.equal(i.campaignScenario.resolvedLanguage,'lv');i=T.capture({...i,drafts:{...i.drafts,emailBody:lv.message+' Paldies.'}});i=T.generated(i,{subject:'New English',message:'New English original'});assert.ok(T.book(i).versions.lv.message.endsWith('Paldies.'));i=T.activate(i,'lv');assert.equal(i.localizationProvenance.model,'translation-model');assert.equal(i.campaignScenario.language,'lv');});
test('protected names are checked again after translation edits',()=>{const terms=T.protectedTerms(item,{sender:'Alex Smith',company:'Seller'});assert.ok(terms.includes('Sam'));assert.throws(()=>T.validate(T.source(item),{...lv,message:lv.message.replace('Sam','Other')},{protectedTerms:terms}),/protected name/);});
