const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../message-studio.js'),O=require('../outreach-engine.js');const source=fs.readFileSync(require.resolve('../outreach-ui.js'),'utf8');
test('approval accepts only the current sender profile and preserves manually edited subjects',async()=>{
 for(const allowed of [true,false]){const h=harness('brutal'),c=h.ctx,url='https://www.linkedin.com/in/alex-lane/';let reached=false;
 h.item.messageStudioDraft={essentials:c.readStudio().essentials};h.item.drafts.emailSubject='My edited subject';h.item.drafts.emailBody='20-minute Zoom https://calendly.com/alex/30min '+(allowed?url:'https://www.linkedin.com/in/other-person/');
 c.studioState=c.readStudio;c.mainState=()=>({answers:{},brandIdentity:{linkedinUrl:url}});c.renderDossier=()=>{};
 c.LeadIntelOutreach={...O,approveOutreachItem:(item,drafts)=>{reached=true;assert.equal(drafts.emailSubject,'My edited subject');return {...item,approved:false,error:'Test stops before CRM approval'};}};
 vm.runInContext(source.slice(source.indexOf('async function approveOutreach()'),source.indexOf('function renderApprovedPreview(')),c);await c.approveOutreach();assert.equal(reached,allowed);}
});
test('sender LinkedIn context comes from each active workspace identity',()=>{
 const h=harness('brutal');for(const url of ['https://www.linkedin.com/in/lawyer-alex/','https://www.linkedin.com/in/consultant-blair/']){h.ctx.mainState=()=>({answers:{},brandIdentity:{linkedinUrl:url}});assert.equal(h.ctx.studioMessageContext(h.item).senderLinkedInUrl,url);}
 h.ctx.mainState=()=>({answers:{}});assert.equal(h.ctx.studioMessageContext(h.item).senderLinkedInUrl,'');
});
function harness(mode='professional',channel='email'){const essentials={offer:'Stock planning',target:'retail teams',problem:'Stock scattered across tools',value:'One stock view',sender:'Alex',company:'StockCo',meetingValue:'a potential fit',calendly:'https://calendly.com/alex/30min',language:'en'};const studio=M.normalize({mode},essentials);let item={domain:'retail.example',selectedPersonId:'p1',channel,dossier:{people:[{id:'p1',name:'Sam Buyer'}]},drafts:{emailSubject:'Before',emailBody:'Keep this edit'},approved:false};let workspace='w1',resolve,body,saves=0;const controls=new Map();const ctx={LeadIntelMessageFacts:require('../message-facts.js'),messageFactResearchBusy:false,messageWorkspaceUsable:()=>false,mainState:()=>({answers:{}}),LeadIntelMessageStudio:M,LeadIntelMessageEditor:require('../message-editor.js'),LeadIntelOutreach:O,AbortController,setTimeout,clearTimeout,readStudio:()=>studio,studioState:()=>studio,readDraftEdits:()=>item,selectedCandidate:()=>({company:'RetailCo',fitScore:65}),crmBridge:()=>({workspace:{id:workspace}}),crmAuthenticated:()=>true,handoffContact:{domain:item.domain,personId:'p1'},DISCOVERY_META_KEY:'meta',readJson:()=>({scriptBuyer:{workspaceId:'w1',domain:item.domain,personId:'p1',channel}}),persistStudio(){},scriptGenerationRequest:0,outreach:{selectedDomain:item.domain},selectedContact:()=>item.dossier.people[0],currentItem:()=>item,activeCampaignScenario:()=>({language:'en'}),upsertItem:next=>{item=next;},renderAll(){},saveScriptPackage:async()=>{saves++;},toast(){},q:id=>{if(!controls.has(id))controls.set(id,{textContent:'',disabled:false});return controls.get(id);},fetch:async(url,args)=>{body=JSON.parse(args.body);return new Promise(r=>resolve=r);}};vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function workingSuggestedSubject('),source.indexOf('function readDraftEdits(')),ctx);vm.runInContext(source.slice(source.indexOf('function senderLinkedInFooter('),source.indexOf('function studioMessageContext(')),ctx);vm.runInContext(source.slice(source.indexOf('function studioMessageContext('),source.indexOf('function renderPersonalSlots(')),ctx);vm.runInContext(source.slice(source.indexOf('async function generateStudioMessage('),source.indexOf('function initOutreach(')),ctx);return {ctx,get resolver(){return resolve;},get item(){return item;},get body(){return body;},get saves(){return saves;},set workspace(v){workspace=v;},complete(data){resolve({ok:true,json:async()=>({text:JSON.stringify(data||{subject:'StockCo and RetailCo',subjectOptions:['StockCo and RetailCo','Compare approaches','Talk with Alex','An idea for your team','Explore a partnership'],message:'Hi Sam, a 20-minute Zoom meeting? '+essentials.calendly}),provider:'test-provider'})});}};}
test('template preparation protects an existing edit and proposes current facts without AI or CRM save',async()=>{const h=harness();await h.ctx.generateStudioMessage();assert.equal(h.body,undefined);assert.equal(h.item.drafts.emailBody,'Keep this edit');assert.equal(h.item.messageStudioDraft.pendingTemplateUpdate.style,'professional');assert.match(h.item.messageStudioDraft.pendingTemplateUpdate.draft.message,/Sam|StockCo/);assert.equal(h.item.approved,false);assert.equal(h.saves,0);assert.equal(h.item.messageStudioDraft.tailoredOriginal,undefined);});
test('generation cannot overwrite evidence while fact research is pending',async()=>{const h=harness();h.ctx.messageFactResearchBusy=true;await h.ctx.generateStudioMessage();assert.equal(h.body,undefined);assert.equal(h.item.drafts.emailBody,'Keep this edit');assert.equal(h.saves,0);});
test('late AI response cannot overwrite a later edit, changed buyer or changed workspace',async()=>{for(const mode of ['edit','workspace','buyer']){const h=harness('original');const pending=h.ctx.generateStudioMessage();if(mode==='edit')h.ctx.scriptGenerationRequest++;if(mode==='workspace')h.workspace='w2';if(mode==='buyer')h.item.selectedPersonId='p2';h.complete();await pending;assert.equal(h.item.drafts.emailBody,'Keep this edit');assert.equal(h.saves,0);}});

test('AI Original generated subject choices are persisted with the buyer draft',async()=>{const h=harness('original'),pending=h.ctx.generateStudioMessage();const subjectOptions=['A practical idea','Compare approaches','A conversation with Alex','An idea for your team','Explore a partnership'];h.complete({subject:subjectOptions[0],subjectOptions,message:'20-minute Zoom https://calendly.com/alex/30min'});await pending;assert.deepEqual(h.item.messageStudioDraft.subjectOptions,subjectOptions);assert.equal(h.saves,0);});

test('LinkedIn generation accepts a message-only response and never imports email subject choices',async()=>{const h=harness('original','linkedin'),pending=h.ctx.generateStudioMessage();const payload=JSON.parse(h.body.prompt);assert.deepEqual(payload.responseSchema,{message:'draft'});h.complete({message:'Hi Sam, a 20-minute Zoom conversation? https://calendly.com/alex/30min'});await pending;assert.equal(h.item.drafts.linkedinMessage,'Hi Sam, a 20-minute Zoom conversation? https://calendly.com/alex/30min');assert.equal(h.item.messageStudioDraft.subjectOptions.length,0);assert.equal(h.item.drafts.emailSubject,'Before');assert.equal(h.saves,0);});

 test('a canceled generation cannot clear the busy state of a newer request',async()=>{
 const h=harness('original');h.ctx.studioGenerationBusy=false;h.ctx.studioGenerationError=false;h.ctx.renderMessageWorkspace=()=>{};
 const first=h.ctx.generateStudioMessage(),resolveFirst=h.resolver;h.ctx.scriptGenerationRequest++;h.ctx.studioGenerationBusy=false;
 const second=h.ctx.generateStudioMessage();assert.equal(h.ctx.studioGenerationBusy,true);
 resolveFirst({ok:true,json:async()=>({text:JSON.stringify({subject:'First',message:'20-minute Zoom https://calendly.com/alex/30min'})})});await first;assert.equal(h.ctx.studioGenerationBusy,true);assert.equal(h.item.drafts.emailSubject,'Before');
 h.complete();await second;assert.equal(h.ctx.studioGenerationBusy,false);assert.equal(h.saves,0);
 });

 test('approved subject onchange applies only the subject and captures translation state',()=>{
 const h=harness(),c=h.ctx;let captured;
 c.LeadIntelMessageTranslations={capture:item=>{captured=item;return {...item,translationCaptured:true};}};
 c.q('message-subject-choice').value='introduction';
 const handler=source.split('\n').find(line=>line.includes("q('message-subject-choice').onchange="));vm.runInContext(handler,c);
 c.q('message-subject-choice').onchange();
 assert.equal(h.item.drafts.emailSubject,'Alex. StockCo');assert.equal(h.item.drafts.emailBody,'Keep this edit');assert.equal(captured.drafts.emailSubject,'Alex. StockCo');assert.equal(h.item.translationCaptured,true);assert.equal(c.scriptGenerationRequest,1);assert.equal(h.item.approved,false);
 });
