const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const S=require('../message-studio.js'),O=require('../outreach-engine.js'),A=require('../approved-reference-scripts.js');
const E=fs.existsSync(require.resolve('../message-studio.js').replace('message-studio.js','message-editor.js'))?require('../message-editor.js'):{};
const essentials={sender:'Marta Kalna',company:'North Advisory',offer:'business consulting',target:'business owners',problem:'complex operations',value:'simplify operations',difference:'An experienced consulting team.',approach:'Practical workshops',proof:'',meetingValue:'a comparison of your requirements and our approach',nextAction:'Choose a suitable time here: {{calendly}}',calendly:'https://calendly.com/north/intro',language:'en'};
const context={channel:'email',firstName:'Alex',buyerName:'Alex Jones',buyerCompany:'Example',buyerRole:'CEO',sellerWebsite:'https://north.example/',senderLinkedInUrl:'https://www.linkedin.com/in/marta-kalna/',trigger:{url:'https://example.com/news',verification:'source_verified',summary:'Example announced an expansion of its service centre.',excerpt:'Example announced an expansion of its service centre.',title:'Expansion'}};
function studio(mode='professional'){return S.normalize({mode,essentials});}
function item(){return {domain:'example.com',selectedPersonId:'alex',channel:'email',dossier:{company:'Example',domain:'example.com',people:[]},drafts:{emailSubject:'  Keep my subject  ',emailBody:'  Preserve\n\nthis exact text.\n'},approved:true,approvedAt:'yesterday',messageStudioDraft:{}};}
test('approved templates are tailored deterministically with current facts and unchanged fixed wording',()=>{assert.equal(typeof E.tailor,'function');for(const style of ['professional','curiosity','friendly','brutal']){const before=A.originalText(style),d=E.tailor(studio(style),context);assert.match(d.message,/Alex/);assert.match(d.message,/North Advisory/);assert.match(d.message,/Example announced an expansion/);assert.doesNotMatch(d.message,/ERCON|Joakim|LKAB|30 years|2028|Scandinavia|Malmberget/);assert.ok(d.message.includes(essentials.calendly));assert.equal(A.originalText(style),before);if(style==='professional')assert.ok(d.message.includes('Together, we can identify where our cooperation could bring the most value to your team.'));if(style==='brutal')assert.match(d.message,/I’m LeadIntel, an AI-powered system/);assert.deepEqual(E.tailor(studio(style),context),d);}});
test('unreviewed triggers and unavailable claims are omitted without borrowing sample facts',()=>{const d=E.tailor(studio(),{...context,trigger:{...context.trigger,verification:'public_unverified'}});assert.doesNotMatch(d.message,/Example announced|I noticed|30 years|real numbers/);assert.ok(!d.message.includes('{{'));});
test('tailoring works across professions and changed names without manufacturer defaults',()=>{for(const offer of ['legal advice','software integration','metal fabrication']){const d=E.tailor(S.normalize({mode:'professional',essentials:{...essentials,company:'New Partner',offer}}),{...context,firstName:'Taylor',buyerCompany:'Other Buyer'});assert.ok(d.message.includes(offer));assert.match(d.message,/New Partner/);assert.doesNotMatch(d.message,/North Advisory|Alex|ERCON|qualified workforce/);}});
test('missing booking link stays explicit and never acquires another customer calendar',()=>{const d=E.tailor(S.normalize({mode:'friendly',essentials:{...essentials,calendly:''}}),context);assert.match(d.message,/\[Add your Calendly link\]/);assert.doesNotMatch(d.message,/edgars|calendly.com\/north/);});
test('personal versions fill variables without changing their literal wording',()=>{const s=S.savePersonalStyle(studio(),'professional',{subject:'For {{buyerCompany}}',body:'Dear {{firstName}},\n\nExactly my wording. {{offer}}\n{{calendly}}'});const d=E.tailor(s,context);assert.equal(d.message,'Dear Alex,\n\nExactly my wording. business consulting\nhttps://calendly.com/north/intro');});
test('original snapshots survive normalizing, saving and reloading and do not point to previous edits',()=>{const draft=E.tailor(studio(),context),key=E.scope('w1',item(),studio(),context);const first=E.apply(item(),draft,{key,style:'professional',essentials,original:true});const edited=E.apply(first,{subject:'Changed',message:'Manual edit'},{key});const reloaded=O.normalizeOutreachState(JSON.parse(JSON.stringify({items:[edited]}))).items[0];assert.deepEqual(E.original(reloaded,key),draft);assert.equal(E.original(reloaded,key+'other'),null);assert.equal(edited.approved,false);});
test('Save/manual changes retain displayed whitespace through durable snapshot normalization',()=>{const draft={subject:item().drafts.emailSubject,message:item().drafts.emailBody};const saved=E.apply(item(),draft,{key:'k'});const restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(saved),'example.com');assert.equal(restored.drafts.emailSubject,draft.subject);assert.equal(restored.drafts.emailBody,draft.message);});
function controllerHarness(){let scope='w1|alex',draft={subject:'Subject',message:'Original body'},applied=[],saved=[],pending=[];const c=E.createController({scope:()=>scope,read:()=>({...draft}),apply:d=>{draft={...d};applied.push(d);},save:async d=>{saved.push(d);return {ok:true};},rewrite:async input=>new Promise(r=>pending.push({input,resolve:r})),usable:()=>true,changed(){}});return {c,pending,applied,saved,get draft(){return draft;},set scope(s){scope=s;},set draft(d){draft=d;}};}
test('Save stores exactly what is displayed without calling AI',async()=>{assert.equal(typeof E.createController,'function');const h=controllerHarness();await h.c.save();assert.deepEqual(h.saved,[{subject:'Subject',message:'Original body'}]);assert.equal(h.pending.length,0);});
test('manual Edit can be cancelled without saving or changing the baseline',()=>{const h=controllerHarness();h.c.edit();assert.equal(h.c.state().editing,true);h.draft={subject:'Edited',message:'Deleted body'};h.c.cancelEdit();assert.equal(h.draft.message,'Original body');assert.equal(h.saved.length,0);});
test('Rewrite is preview-only until explicitly accepted',async()=>{const h=controllerHarness(),running=h.c.rewrite();h.pending[0].resolve({subject:'Subject',message:'New version'});await running;assert.equal(h.draft.message,'Original body');assert.equal(h.c.state().preview.message,'New version');h.c.accept();assert.equal(h.draft.message,'New version');assert.equal(h.saved.length,0);});
test('Try another sends variation and prior version, and rejects identical output',async()=>{const h=controllerHarness();let p=h.c.rewrite();h.pending[0].resolve({subject:'Subject',message:'Different'});await p;p=h.c.rewrite();assert.notEqual(h.pending[1].input.attempt,h.pending[0].input.attempt);assert.equal(h.pending[1].input.avoid[0],'Different');h.pending[1].resolve({subject:'Subject',message:'Different'});await p;assert.match(h.c.state().error,/repeated/i);assert.equal(h.draft.message,'Original body');});
test('late rewrite responses cannot cross buyers or workspaces',async()=>{const h=controllerHarness(),p=h.c.rewrite();h.scope='w2|other';h.pending[0].resolve({subject:'Subject',message:'Wrong workspace'});await p;assert.equal(h.c.state().preview,null);assert.equal(h.applied.length,0);});
test('cancelled previews and late requests leave the working text untouched',async()=>{const h=controllerHarness(),p=h.c.rewrite();h.c.cancelPreview();h.pending[0].resolve({subject:'Subject',message:'Late'});await p;assert.equal(h.c.state().preview,null);assert.equal(h.draft.message,'Original body');});
test('a text change while rewriting invalidates the pending proposal',async()=>{const h=controllerHarness(),p=h.c.rewrite();h.draft={subject:'Subject',message:'New manual edit'};h.pending[0].resolve({subject:'Subject',message:'Stale'});await p;assert.equal(h.c.state().preview,null);assert.equal(h.draft.message,'New manual edit');});
test('a preview cannot replace working text that changed after generation',async()=>{const h=controllerHarness(),p=h.c.rewrite();h.pending[0].resolve({subject:'Subject',message:'Preview version'});await p;h.draft={subject:'Subject',message:'Later local edit'};assert.equal(h.c.accept(),false);assert.equal(h.draft.message,'Later local edit');assert.equal(h.c.state().preview,null);});
test('a failed CRM Save retains editing and reports failure without calling AI',async()=>{let draft={subject:'Exact',message:'Local draft'},calls=0;const c=E.createController({scope:()=> 'w1',read:()=>draft,usable:()=>true,apply:d=>{draft=d},save:async()=>({ok:true,localOnly:true}),rewrite:async()=>{calls++}});c.edit();assert.equal(await c.save(),false);assert.equal(c.state().editing,true);assert.match(c.state().error,/CRM save failed/);assert.equal(calls,0);});
