const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const M=require('../message-studio.js'),O=require('../outreach-engine.js');const source=fs.readFileSync(require.resolve('../outreach-ui.js'),'utf8');
function harness(mode='professional',channel='email'){const essentials={offer:'Stock planning',target:'retail teams',problem:'Stock scattered across tools',value:'One stock view',sender:'Alex',company:'StockCo',meetingValue:'a potential fit',calendly:'https://calendly.com/alex/30min',language:'en'};const studio=M.normalize({mode},essentials);let item={domain:'retail.example',selectedPersonId:'p1',channel,dossier:{people:[{id:'p1',name:'Sam Buyer'}]},drafts:{emailSubject:'Before',emailBody:'Keep this edit'},approved:false};let workspace='w1',resolve,body,saves=0;const controls=new Map();const ctx={mainState:()=>({answers:{}}),LeadIntelMessageStudio:M,LeadIntelOutreach:O,AbortController,setTimeout,clearTimeout,readStudio:()=>studio,readDraftEdits:()=>item,selectedCandidate:()=>({company:'RetailCo',fitScore:65}),crmBridge:()=>({workspace:{id:workspace}}),crmAuthenticated:()=>true,handoffContact:{domain:item.domain,personId:'p1'},DISCOVERY_META_KEY:'meta',readJson:()=>({scriptBuyer:{workspaceId:'w1',domain:item.domain,personId:'p1',channel}}),persistStudio(){},scriptGenerationRequest:0,outreach:{selectedDomain:item.domain},selectedContact:()=>item.dossier.people[0],currentItem:()=>item,activeCampaignScenario:()=>({language:'en'}),upsertItem:next=>{item=next;},renderAll(){},saveScriptPackage:async()=>{saves++;},toast(){},q:id=>{if(!controls.has(id))controls.set(id,{textContent:'',disabled:false});return controls.get(id);},fetch:async(url,args)=>{body=JSON.parse(args.body);return new Promise(r=>resolve=r);}};vm.createContext(ctx);vm.runInContext(source.slice(source.indexOf('function studioMessageContext('),source.indexOf('function renderPersonalSlots(')),ctx);vm.runInContext(source.slice(source.indexOf('async function generateStudioMessage('),source.indexOf('function initOutreach(')),ctx);return {ctx,get item(){return item;},get body(){return body;},get saves(){return saves;},set workspace(v){workspace=v;},complete(data){resolve({ok:true,json:async()=>({text:JSON.stringify(data||{subject:'StockCo and RetailCo',message:'Hi Sam, a 30-minute Zoom meeting? '+essentials.calendly}),provider:'test-provider'})});}};}
test('AI generation applies the selected template to one buyer and saves the resulting CRM draft',async()=>{const h=harness();const pending=h.ctx.generateStudioMessage();assert.equal(h.body.task,'outreach-generation');assert.equal(JSON.parse(h.body.prompt).context.buyerName,'Sam Buyer');assert.equal(JSON.parse(h.body.prompt).context.fitScore,65);h.complete();await pending;assert.equal(h.item.messageStudioDraft.mode,'professional');assert.equal(h.item.drafts.emailSubject,'StockCo and RetailCo');assert.equal(h.item.approved,false);assert.equal(h.saves,1);});
test('late AI response cannot overwrite a later edit, changed buyer or changed workspace',async()=>{for(const mode of ['edit','workspace','buyer']){const h=harness();const pending=h.ctx.generateStudioMessage();if(mode==='edit')h.ctx.scriptGenerationRequest++;if(mode==='workspace')h.workspace='w2';if(mode==='buyer')h.item.selectedPersonId='p2';h.complete();await pending;assert.equal(h.item.drafts.emailBody,'Keep this edit');assert.equal(h.saves,0);}});

test('AI Original generated subject choices are persisted with the buyer draft',async()=>{const h=harness('original'),pending=h.ctx.generateStudioMessage();const subjectOptions=['A practical idea','Compare approaches','A conversation with Alex','An idea for your team','Explore a partnership'];h.complete({subject:subjectOptions[0],subjectOptions,message:'30-minute Zoom https://calendly.com/alex/30min'});await pending;assert.deepEqual(h.item.messageStudioDraft.subjectOptions,subjectOptions);assert.equal(h.saves,1);});

test('LinkedIn generation accepts a message-only response and never imports email subject choices',async()=>{const h=harness('original','linkedin'),pending=h.ctx.generateStudioMessage();const payload=JSON.parse(h.body.prompt);assert.deepEqual(payload.responseSchema,{message:'draft'});h.complete({message:'Hi Sam, a 30-minute Zoom conversation? https://calendly.com/alex/30min'});await pending;assert.equal(h.item.drafts.linkedinMessage,'Hi Sam, a 30-minute Zoom conversation? https://calendly.com/alex/30min');assert.equal(h.item.messageStudioDraft.subjectOptions.length,0);assert.equal(h.item.drafts.emailSubject,'Before');assert.equal(h.saves,1);});
