const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../message-studio.js');
const essentials={offer:'Inventory software',target:'retail teams',problem:'Stock spread across separate tools',value:'See stock in one place',nextAction:'Choose a suitable time here: {{calendly}}',sender:'Alex',company:'StockCo',meetingValue:'whether the workflow fits',calendly:'https://calendly.com/alex/30min'};
test('four independent saved templates survive normalization without copying another seller',()=>{const a=M.normalize({},essentials);assert.equal(a.templates.length,4);const saved=M.savePersonalTemplate(a,a.templates[0].id,'My subject','Custom {{offer}}');const b=M.normalize(JSON.parse(JSON.stringify(saved)));assert.equal(b.templates[0].body,'Custom {{offer}}');assert.notEqual(b.templates[1].body,b.templates[0].body);assert.equal(M.normalize().essentials.company,'');assert.equal(M.normalize().essentials.calendly,'');});
test('essential facts and an actual Calendly event URL gate generation',()=>{assert.deepEqual(M.missing(essentials),[]);assert.ok(M.missing({...essentials,calendly:'https://evil.test/a'}).includes('calendly'));assert.ok(M.missing({...essentials,offer:''}).includes('offer'));});
test('original mode does not inherit a template and only receives explicitly supplied facts',()=>{const s=M.normalize({mode:'original'},essentials);const p=JSON.parse(M.prompt(s,{buyerCompany:'HospitalCo'}).prompt);assert.equal(p.template,null);assert.equal(p.context.buyerCompany,'HospitalCo');assert.equal(p.essentials.company,'StockCo');});
test('generated draft rejects invented scheduling links and incomplete placeholders',()=>{const draft={subject:'Hello',message:'A 30-minute Zoom? '+essentials.calendly};assert.equal(M.parse(JSON.stringify(draft),essentials).subject,'Hello');assert.throws(()=>M.parse(JSON.stringify({...draft,message:draft.message+' https://calendly.com/other/meeting'}),essentials));assert.throws(()=>M.parse(JSON.stringify({...draft,message:'{{offer}} '+draft.message}),essentials));assert.throws(()=>M.parse('{}',essentials));});
test('core settings, templates and draft provenance survive browser and CRM snapshot reloads',()=>{const O=require('../outreach-engine.js');const studio=M.normalize({},essentials);const item={domain:'retail.example',selectedPersonId:'buyer1',channel:'email',dossier:{domain:'retail.example',people:[{id:'buyer1'}]},campaignScenario:{language:'en'},localizationStatus:'complete',messageStudioDraft:{mode:'professional',essentials,status:'Generated'},drafts:{emailSubject:'Hello',emailBody:'Saved edit'}};const state=O.normalizeOutreachState(JSON.parse(JSON.stringify({selectedDomain:item.domain,messageStudio:studio,items:[item]})));assert.deepEqual(state.messageStudio,studio);assert.equal(state.items[0].drafts.emailBody,'Saved edit');const restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(state.items[0]),item.domain);assert.equal(restored.messageStudioDraft.essentials.company,'StockCo');assert.equal(restored.drafts.emailBody,'Saved edit');});
test('confirmed commercial answers prefill actual seller context across different industries',()=>{for(const [company,offer] of [['RetailSoft','Inventory software'],['MetalWorks','Custom metal fabrication']]){const seed=M.seed({profile:{companyName:company},answers:{priority_offers:offer,ideal_customer:'Operations teams',value_proposition:'Make project delivery simpler',proof_points:'Approved ISO certification'}},{language:'auto'},'Alex');assert.equal(seed.offer,offer);assert.equal(seed.company,company);assert.equal(seed.language,'en');assert.equal(seed.sender,'Alex');assert.equal(seed.calendly,'');}});
test('preview drafts can use an explicit missing-calendar marker but cannot invent a booking link',()=>{const e={...essentials,calendly:''};const s=M.normalize({},e);assert.equal(JSON.parse(M.prompt(s).prompt).essentials.calendly,'[Add your Calendly link]');assert.equal(M.parse(JSON.stringify({subject:'Preview',message:'A 30-minute Zoom? [Add your Calendly link]'}),e).subject,'Preview');assert.throws(()=>M.parse(JSON.stringify({subject:'Preview',message:'A 30-minute Zoom? https://calendly.com/invented/call'}),e));assert.ok(M.missing(e).includes('calendly'));});
test('seven pitch elements survive reload and produce a preview with the next action directly after meeting value',()=>{
 const studio=M.normalize({},essentials),restored=M.normalize(JSON.parse(JSON.stringify(studio)));
 assert.equal(restored.essentials.problem,essentials.problem);assert.equal(restored.essentials.nextAction,essentials.nextAction);
 const preview=M.preview(restored.essentials);assert.ok(preview.includes(essentials.problem));
 assert.ok(preview.endsWith('whether the workflow fits. Choose a suitable time here: https://calendly.com/alex/30min'));
 assert.ok(M.missing({...essentials,problem:''}).includes('problem'));assert.ok(M.missing({...essentials,nextAction:''}).includes('nextAction'));
});
test('legacy core information and customized templates are preserved while new pitch fields remain honest',()=>{
 const legacy={version:1,essentials:{offer:'Fabrication',target:'Factories',value:'One partner',proof:'ISO certificate'},templates:[{id:'professional',subject:'My subject',body:'My custom {{offer}}'}]};
 const migrated=M.normalize(legacy);assert.equal(migrated.essentials.proof,'ISO certificate');assert.equal(migrated.essentials.problem,'');assert.ok(migrated.essentials.nextAction.includes('{{calendly}}'));assert.equal(migrated.templates.find(t=>t.id==='professional').body,'My custom {{offer}}');
});
test('seller differentiation and proof remain separate without assuming a buyer problem in either industry',()=>{
 for(const company of ['ManufacturingCo','SoftwareCo']){const seed=M.seed({profile:{companyName:company},answers:{differentiation:'One accountable partner',proof_points:'Approved case study'}});
 assert.equal(seed.proof,'Approved case study');assert.equal(seed.difference,'One accountable partner');assert.equal(seed.problem,'');assert.equal(seed.company,company);}
});
test('all default styles place a single action after meeting value and expose problem as a hypothesis',()=>{
 const s=M.normalize({},essentials);for(const t of s.templates){assert.ok(t.body.includes(t.id==='professional'?'{{roleQuestion}}':t.id==='curiosity'?'{{deliveryChallenge}}':'{{problem}}'));assert.ok(t.body.indexOf('{{nextAction}}')>t.body.lastIndexOf('{{meetingValue}}'));}
 const p=M.prompt(s);assert.match(p.system,/hypothesis/i);assert.match(p.system,/immediately after/i);
});
