const test=require('node:test');const assert=require('node:assert/strict');const F=require('../my-flows.js');
const base={main:{website:'https://seller.test',approved:true,profile:{companyName:'Seller',priorityOffers:'Equipment',targetMarkets:'Sweden'},targetMarkets:['Sweden'],answers:{priority_offers:'Equipment',buyer_roles:'COO',value_proposition:'Reliable'},market:{strategyApproved:true,researchResults:[{title:'Sweden factory'}],signals:[{id:'x',name:'Expansion',active:true}]},brandIdentity:{senderName:'Alex'}},discovery:{pipeline:[{company:'Swedish Buyer'}]},outreach:{messageStudio:{mode:'professional',originalScripts:{professional:{body:'literal'}},items:[{company:'Swedish Buyer'}]}},delivery:{queue:[{recipient:'sweden@test'}]},meta:{discovery:{selected:'sweden'}}};
test('duplicate retains configuration and shared originals, but never carries recipients, evidence or approval',()=>{const copy=F.duplicatePayload(base,['Finland']);assert.deepEqual(copy.main.targetMarkets,['Finland']);assert.equal(copy.main.profile.targetMarkets,'Finland');assert.equal(copy.main.market.strategyApproved,false);assert.equal(copy.main.targetingConfirmation,null);assert.deepEqual(copy.main.market.researchResults,[]);assert.deepEqual(copy.discovery,{});assert.deepEqual(copy.delivery,{});assert.equal(copy.outreach.messageStudio.originalScripts.professional.body,'literal');assert.equal(copy.outreach.messageStudio.mode,'professional');assert.equal(copy.outreach.messageStudio.items,undefined);assert.equal(base.main.targetMarkets[0],'Sweden');});
test('opening a saved flow keeps its progress and targets and overlays shared seller details',()=>{const current=structuredClone(base);current.main.brandIdentity.senderName='New sender';current.main.website='https://new.test';current.main.targetMarkets=['Norway'];const opened=F.composePayload(base,current,{id:'fi',name:'Finland',state_version:4});assert.deepEqual(opened.main.targetMarkets,['Sweden']);assert.equal(opened.main.website,'https://new.test');assert.equal(opened.main.brandIdentity.senderName,'New sender');assert.equal(opened.discovery.pipeline[0].company,'Swedish Buyer');assert.equal(opened.main.myFlow.id,'fi');});
test('business fingerprint ignores current-flow progress and targets, and notices seller changes',()=>{const other=structuredClone(base);other.main.targetMarkets=['Finland'];other.main.market.signals=[];other.discovery={};assert.deepEqual(F.sharedBusiness(other),F.sharedBusiness(base));other.main.answers.value_proposition='New';assert.notDeepEqual(F.sharedBusiness(other),F.sharedBusiness(base));});
test('review is explicit; zero metrics are distinct from unsupported tracking',()=>{const checks=F.reviewChecklist(base);assert.ok(checks.some(x=>x.id==='markets'));assert.ok(checks.some(x=>x.id==='sources'));assert.equal(F.rate(2,40),'5%');assert.equal(F.rate(0,0),'—');assert.equal(F.MAX_SAVED_FLOWS,10);assert.equal(F.MAX_ACTIVE_FLOWS,2);});

test('language defaults are flow-specific, survive duplicate and reopen, and appear in the saved-flow summary',()=>{
 const sweden=structuredClone(base);sweden.outreach.messageStudio.essentials={language:'en'};sweden.outreach.messageStudio.languageSettings={languages:['en','sv','de','lv'],defaultLanguage:'sv',targetLanguage:'sv'};
 const germany=structuredClone(sweden);germany.outreach.messageStudio.languageSettings.defaultLanguage='de';germany.outreach.messageStudio.languageSettings.targetLanguage='de';
 const opened=F.composePayload(sweden,germany,{id:'sweden',name:'Sweden',state_version:2});assert.equal(opened.outreach.messageStudio.languageSettings.defaultLanguage,'sv');assert.equal(germany.outreach.messageStudio.languageSettings.defaultLanguage,'de');assert.equal(F.summary(opened).language,'sv');assert.equal(opened.outreach.messageStudio.essentials.language,'en');
 const copy=F.duplicatePayload(sweden,['Finland']);assert.deepEqual(copy.outreach.messageStudio.languageSettings,sweden.outreach.messageStudio.languageSettings);copy.outreach.messageStudio.languageSettings.defaultLanguage='fi';assert.equal(sweden.outreach.messageStudio.languageSettings.defaultLanguage,'sv');assert.ok(F.reviewChecklist(copy).some(c=>c.id==='language'));
});
