const {test}=require('node:test'),assert=require('node:assert/strict');const M=require('../message-studio.js');const O=require('../outreach-engine.js');
function library(){assert.ok(M.Library,'Personal template library must be available');return M.Library;}
const e={sender:'Alex Lane',company:'SellerCo',calendly:'https://calendly.com/alex/30min'};
const draft={subject:'A practical idea',message:'Would you be open to a 20-minute Zoom conversation? '+e.calendly,subjectOptions:['A practical idea','Compare approaches','A conversation with Alex','An idea for your team','Explore a partnership']};
test('a saved personal pattern cannot modify a protected core in either workspace',()=>{assert.equal(typeof M.saveMyTemplate,'function');const before=M.normalize(),s=M.saveMyTemplate(before,'template-1',{name:'Short introduction',subject:'My subject',body:'My {{offer}}'});assert.equal(s.myTemplates['template-1'].name,'Short introduction');assert.equal(M.normalize(JSON.parse(JSON.stringify(s))).templates.find(t=>t.id==='template-1').body,'My {{offer}}');assert.equal(s.templates.find(t=>t.id==='professional').body,before.templates[0].body);assert.equal(M.normalize().templates.length,4);});
test('twenty slots are available without implicit overwrite and older five stay intact',()=>{const L=library();let slots={};for(let i=1;i<=5;i++)slots=L.save(slots,'template-'+i,{subject:'Subject '+i,body:'Body '+i});assert.equal(L.nextSlot(slots),'template-6');for(let i=6;i<=20;i++)slots=L.save(slots,'template-'+i,{subject:'Subject '+i,body:'Body '+i,name:'Template '+i});assert.equal(L.nextSlot(slots),'');assert.equal(L.ids.length,20);assert.equal(slots['template-20'].name,'Template 20');assert.throws(()=>L.save(slots,'template-1',{subject:'New',body:'New'}),/occupied/);slots=L.save(slots,'template-1',{name:'Renamed',subject:'New',body:'New'},true);assert.equal(slots['template-1'].name,'Renamed');assert.equal(slots['template-2'].body,'Body 2');assert.throws(()=>L.save(slots,'template-21',{subject:'Extra',body:'Extra'}));assert.throws(()=>L.save({},'template-1',{subject:'',body:'Body'}));});
test('deletion survives normalization and stale legacy fields do not resurrect it, undo restores exact content',()=>{assert.equal(typeof M.deleteMyTemplate,'function');let s=M.saveMyTemplate({},'template-1',{name:'Keepable',subject:'S',body:'B'});s.mode='template-1';s=M.deleteMyTemplate(s,'template-1');s=M.normalize(JSON.parse(JSON.stringify({...s,personalTemplates:[{id:'professional',body:'Old',subject:'Old'}]})));assert.equal(s.mode,'original');assert.equal(s.templates.some(t=>t.id==='template-1'),false);assert.equal(s.myTemplates['template-1'].deleted,true);s=M.undoDeleteTemplate(s,'template-1');assert.equal(s.templates.find(t=>t.id==='template-1').body,'B');assert.equal(s.myTemplates['template-1'].name,'Keepable');});
test('legacy body edits migrate once while chosen core subjects do not consume slots',()=>{const original=M.defaults.find(t=>t.id==='friendly');const s=M.normalize({version:5,personalTemplates:[{id:'professional',sourceId:'professional',subject:'Custom',body:'My custom body'},{id:'friendly',sourceId:'friendly',subject:'{{company}}. A long-term partnership?',body:original.body}],subjectChoices:{friendly:'partnership'}});assert.equal(s.templates.find(t=>t.id==='professional').body,M.defaults[0].body);assert.ok(s.myTemplates);assert.equal(Object.keys(s.myTemplates).length,1);assert.equal(s.myTemplates['template-1'].body,'My custom body');assert.equal(s.subjectChoices.friendly,'partnership');assert.deepEqual(M.normalize(JSON.parse(JSON.stringify(s))),s);});
test('core choices stay independent of personal slots and restore does not delete personal work',()=>{assert.equal(typeof M.saveMyTemplate,'function');let s=M.chooseSubject({},'brutal','fit');s=M.chooseSubject(s,'friendly','partnership');s=M.saveMyTemplate(s,'template-1',{subject:'Mine',body:'Mine'});s=M.restoreOriginal(s,'friendly');assert.equal(s.subjectChoices.brutal,'fit');assert.equal(s.myTemplates['template-1'].body,'Mine');assert.equal(s.templates.find(t=>t.id==='brutal').isPersonal,false);assert.equal(s.templates.find(t=>t.id==='friendly').isPersonal,false);});
test('reusable conversion replaces identities project website calendar and score without changing duration or substrings',()=>{const L=library(),c={buyerName:'Joakim Winsa',firstName:'Joakim',buyerCompany:'LKAB',buyerRole:'Project Manager',verifiedProject:'Malmberget plant',fitScore:65,sellerWebsite:'https://seller.example/projects'};const r=L.reusable('LKAB — fit: 65/100','Hi Joakim Winsa, Joakim. LKAB: Malmberget plant. Alex Lane at SellerCo. Project Manager. 30-minute Zoom. https://seller.example/projects '+e.calendly,c,e);assert.equal(r.subject,'{{buyerCompany}} — fit: {{fitScore}}/100');assert.doesNotMatch(r.body,/Joakim|LKAB|Malmberget|Alex Lane|SellerCo|https:/);assert.match(r.body,/30-minute Zoom/);assert.match(r.body,/\{\{firstName\}\}/);assert.equal(L.reusable('Li','A liability conversation for Li.',{firstName:'Li'}).body,'A liability conversation for {{firstName}}.');assert.equal(L.reusable('{{sender}}','Hello {{buyerCompany}}',c,e).body,'Hello {{buyerCompany}}');});
test('personal generation uses current workspace and recipient facts rather than old source context',()=>{assert.equal(typeof M.saveMyTemplate,'function');const saved=M.saveMyTemplate({},'template-1',{subject:'{{verifiedProject}}',body:'Hi {{firstName}}, {{company}} offers {{offer}}. {{proof}} {{calendly}}'});for(const [company,offer,buyer] of [['LegalCo','Contract review','LawClient'],['SoftwareCo','Inventory software','RetailClient'],['FactoryCo','Fabrication','BuildClient']]){const s=M.foundation({myTemplates:saved.myTemplates,version:6,mode:'template-1'},{profile:{companyName:company},answers:{priority_offers:offer}});const p=JSON.parse(M.prompt(s,{buyerCompany:buyer}).prompt);assert.equal(p.essentials.company,company);assert.equal(p.essentials.offer,offer);assert.equal(p.context.buyerCompany,buyer);assert.equal(p.template.id,'template-1');assert.doesNotMatch(JSON.stringify(p),/Joakim|LKAB|ERCON/);}});
test('AI Original returns five choices and preserves them in a CRM script snapshot',()=>{const s=M.normalize({mode:'original'},e);const r=M.parse(JSON.stringify(draft),e,{studio:s});assert.deepEqual(r.subjectOptions,draft.subjectOptions);const item={domain:'buyer.example',selectedPersonId:'p',drafts:{emailSubject:r.subject,emailBody:r.message},messageStudioDraft:{mode:'original',subjectOptions:r.subjectOptions}};const restored=O.restoreCrmScriptSnapshot(O.buildCrmScriptSnapshot(item),'buyer.example');assert.deepEqual(restored.messageStudioDraft.subjectOptions,draft.subjectOptions);});
test('AI Original rejects missing duplicate or unsafe options before changing the draft',()=>{const s=M.normalize({mode:'original'},e);for(const subjectOptions of [undefined,[],['A','A','B','C','D'],['{{buyerCompany}}','B','C','D','E'],['https://fake.example','B','C','D','E']])assert.throws(()=>M.parse(JSON.stringify({...draft,subjectOptions}),e,{studio:s}));assert.throws(()=>M.parse(JSON.stringify({...draft,subject:'Not one of the options'}),e,{studio:s}));});
test('AI template preparation accepts reusable fields and rejects incomplete responses',()=>{const L=library();assert.deepEqual(L.parsePreparation('{"subject":"{{buyerCompany}}","message":"Hi {{firstName}}"}'),{subject:'{{buyerCompany}}',body:'Hi {{firstName}}'});assert.throws(()=>L.parsePreparation('{"subject":"","message":"Text"}'));const p=JSON.parse(L.preparationPrompt('S','B',{buyerCompany:'Client'},e).prompt);assert.equal(p.context.buyerCompany,'Client');assert.equal(p.message,'B');});
test('independent slot edits merge but simultaneous edits to one template conflict atomically',()=>{const Sync=require('../workspace-sync.js'),b={outreach:{messageStudio:{myTemplates:{'template-1':{id:'template-1',subject:'A',body:'A'},'template-2':{id:'template-2',subject:'B',body:'B'}}}}};const l=structuredClone(b),r=structuredClone(b);l.outreach.messageStudio.myTemplates['template-1'].body='Local';r.outreach.messageStudio.myTemplates['template-2'].body='Remote';let merged=Sync.merge(b,l,r);assert.deepEqual(merged.conflicts,[]);assert.equal(merged.payload.outreach.messageStudio.myTemplates['template-2'].body,'Remote');r.outreach.messageStudio.myTemplates['template-1'].subject='Remote subject';merged=Sync.merge(b,l,r);assert.ok(merged.conflicts.some(p=>p.endsWith('template-1')));assert.equal(merged.payload.outreach.messageStudio.myTemplates['template-1'].subject,'A');});
test('persisted studio omits derived core and preview arrays so different slots can synchronize independently',()=>{assert.equal(typeof M.storageState,'function');const s=M.saveMyTemplate({},'template-1',{subject:'One',body:'First'});const stored=M.storageState(s);assert.equal('templates' in stored,false);assert.equal('personalTemplates' in stored,false);assert.equal(M.normalize(stored).templates.find(t=>t.id==='template-1').body,'First');});
test('a saved fit pattern still uses the actual current company score after AI generation',()=>{let s=M.saveMyTemplate(M.normalize({},e),'template-1',{subject:'{{buyerCompany}} — fit: {{fitScore}}/100',body:'Hi {{firstName}}'});s.mode='template-1';s=M.normalize(s);const r=M.parse(JSON.stringify({...draft,subject:'BuyerCo — fit: 99/100'}),e,{studio:s,context:{buyerCompany:'BuyerCo',fitScore:65}});assert.equal(r.subject,'BuyerCo — fit: 65/100');});
test('saving an existing draft retains its generated style even when a different core is selected',()=>{const L=library();assert.equal(typeof L.fromDraft,'function');const r=L.fromDraft({channel:'email',drafts:{emailSubject:'Hi ClientCo',emailBody:'Hi Sam'},messageStudioDraft:{mode:'professional'}},M.normalize({mode:'brutal'},e),{firstName:'Sam',buyerCompany:'ClientCo'});assert.equal(r.sourceStyle,'professional');assert.equal(r.subject,'Hi {{buyerCompany}}');assert.equal(r.body,'Hi {{firstName}}');assert.throws(()=>L.fromDraft({drafts:{}},M.normalize(),{}));});

test('library conversion removes prepared event, project and seller facts while retaining reusable placeholders',()=>{
 const L=library(),context={firstName:'Joakim',buyerCompany:'LKAB',projectName:'Malmberget',reusableDevelopment:'LKAB’s investment in a new sorting plant at Malmberget',sourceFields:{offer:'drawing development and installation',difference:'Our team has 30 years of supplied experience.'},senderLinkedInUrl:'https://linkedin.com/in/alex'};
 const r=L.reusable('Malmberget: another success story?','Hi Joakim,\n\nI noticed LKAB’s investment in a new sorting plant at Malmberget. We provide drawing development and installation. Our team has 30 years of supplied experience.\n\n20-minute Zoom. https://linkedin.com/in/alex',context,e);
 assert.equal(r.subject,'{{subjectProject}}: another success story?');assert.doesNotMatch(r.body,/Joakim|LKAB|Malmberget|30 years|https:/);assert.match(r.body,/\{\{development\}\}/);assert.match(r.body,/\{\{difference\}\}/);assert.match(r.body,/20-minute Zoom/);
});
