const {test}=require('node:test'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');const {mountWritingReferences}=require('../writing-references-ui.js');
function setup(){const dom=new JSDOM('<main id="refs"></main>');let rows=[],revision=0;const root=dom.window.document.querySelector('#refs');const api={list:async()=>({cards:rows,referenceRevision:revision}),patch:async(id,change)=>{const c=rows.find(c=>c.id===id);Object.assign(c,change);revision++;return {cards:rows,referenceRevision:revision};},upload:async(slot,file)=>{rows=[{slot,id:'s'+slot,filename:file.name,status:'Ready',active:false,revision:1,summary:'Ask useful questions',instruction:'',coverage:{total:1,readable:1,unreadable:0}}];return {cards:rows,referenceRevision:++revision};},delete:async()=>{rows=[];return {cards:rows,referenceRevision:++revision};}};return {dom,root,api,setRows:r=>rows=r};}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('renders three slots and does not activate newly uploaded documents',async()=>{const {root,api}=setup();const app=mountWritingReferences({root,api,confirmDelete:()=>true});await app.refresh();assert.equal(root.querySelectorAll('[data-slot]').length,3);await app.upload(2,{name:'guide.txt'});assert.equal(root.querySelector('[data-active]').checked,false);assert.match(root.textContent,/Ask useful questions/);assert.equal(root.querySelectorAll('[data-slot]').length,3);app.destroy();});
test('activation is explicit and deletion cancellation preserves source',async()=>{const {root,api,dom,setRows}=setup();setRows([{slot:1,id:'s1',filename:'<script>.txt',status:'Ready',active:false,revision:1,summary:'Questions',instruction:''}]);let changes=[];const app=mountWritingReferences({root,api,onChange:v=>changes.push(v),confirmDelete:()=>false});await app.refresh();assert.equal(root.querySelector('script'),null);const toggle=root.querySelector('[data-active]');toggle.checked=true;toggle.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await tick();assert.equal(changes.at(-1).activeCount,1);root.querySelector('[data-delete]').click();await tick();assert.match(root.textContent,/<script>.txt/);app.destroy();});
test('incomplete sources cannot activate and duplicate mounts do not duplicate cards',async()=>{const {root,api,setRows}=setup();setRows([{slot:1,id:'s1',filename:'scan.pdf',status:'Needs attention',active:false,revision:1,summary:'Unreadable pages'}]);const a=mountWritingReferences({root,api});assert.equal(mountWritingReferences({root,api}),a);await a.refresh();assert.equal(root.querySelector('[data-active]').disabled,true);assert.equal(root.querySelectorAll('[data-slot]').length,3);a.destroy();});
test('late refresh after destroy cannot reinsert private data',async()=>{const {root}=setup();let release;const app=mountWritingReferences({root,api:{list:()=>new Promise(resolve=>release=resolve)}});const request=app.refresh();app.destroy();release({cards:[{slot:1,id:'secret',filename:'private.pdf'}],referenceRevision:1});await request;assert.equal(root.textContent,'');});
test('failed analysis shows an actionable error and retry preserves the source revision',async()=>{const {root,api,setRows}=setup();setRows([{slot:1,id:'s1',filename:'guide.txt',status:'Failed',active:false,revision:4,error:'Check provider quota'}]);let retry;api.retry=async(id,body)=>{retry={id,body};return {cards:[{slot:1,id:'s1',filename:'guide.txt',status:'Processing',active:false,revision:5}],referenceRevision:2};};const app=mountWritingReferences({root,api});await app.refresh();assert.match(root.textContent,/Check provider quota/);assert.ok(root.querySelector('[data-retry]'));root.querySelector('[data-retry]').click();await tick();assert.deepEqual(retry,{id:'s1',body:{expectedRevision:4}});assert.match(root.textContent,/Processing/);app.destroy();});
